// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module full_pose_accel_load_weight_blob_Pipeline_FC3_LOAD_WEIGHT_OUT_FC3_LOAD_WEIGHT_IN (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem1_AWVALID,
        m_axi_gmem1_AWREADY,
        m_axi_gmem1_AWADDR,
        m_axi_gmem1_AWID,
        m_axi_gmem1_AWLEN,
        m_axi_gmem1_AWSIZE,
        m_axi_gmem1_AWBURST,
        m_axi_gmem1_AWLOCK,
        m_axi_gmem1_AWCACHE,
        m_axi_gmem1_AWPROT,
        m_axi_gmem1_AWQOS,
        m_axi_gmem1_AWREGION,
        m_axi_gmem1_AWUSER,
        m_axi_gmem1_WVALID,
        m_axi_gmem1_WREADY,
        m_axi_gmem1_WDATA,
        m_axi_gmem1_WSTRB,
        m_axi_gmem1_WLAST,
        m_axi_gmem1_WID,
        m_axi_gmem1_WUSER,
        m_axi_gmem1_ARVALID,
        m_axi_gmem1_ARREADY,
        m_axi_gmem1_ARADDR,
        m_axi_gmem1_ARID,
        m_axi_gmem1_ARLEN,
        m_axi_gmem1_ARSIZE,
        m_axi_gmem1_ARBURST,
        m_axi_gmem1_ARLOCK,
        m_axi_gmem1_ARCACHE,
        m_axi_gmem1_ARPROT,
        m_axi_gmem1_ARQOS,
        m_axi_gmem1_ARREGION,
        m_axi_gmem1_ARUSER,
        m_axi_gmem1_RVALID,
        m_axi_gmem1_RREADY,
        m_axi_gmem1_RDATA,
        m_axi_gmem1_RLAST,
        m_axi_gmem1_RID,
        m_axi_gmem1_RFIFONUM,
        m_axi_gmem1_RUSER,
        m_axi_gmem1_RRESP,
        m_axi_gmem1_BVALID,
        m_axi_gmem1_BREADY,
        m_axi_gmem1_BRESP,
        m_axi_gmem1_BID,
        m_axi_gmem1_BUSER,
        weights,
        p_ZL17g_fc3_weight_int8_0_address0,
        p_ZL17g_fc3_weight_int8_0_ce0,
        p_ZL17g_fc3_weight_int8_0_we0,
        p_ZL17g_fc3_weight_int8_0_d0,
        p_ZL17g_fc3_weight_int8_1_address0,
        p_ZL17g_fc3_weight_int8_1_ce0,
        p_ZL17g_fc3_weight_int8_1_we0,
        p_ZL17g_fc3_weight_int8_1_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem1_AWVALID;
input   m_axi_gmem1_AWREADY;
output  [63:0] m_axi_gmem1_AWADDR;
output  [0:0] m_axi_gmem1_AWID;
output  [31:0] m_axi_gmem1_AWLEN;
output  [2:0] m_axi_gmem1_AWSIZE;
output  [1:0] m_axi_gmem1_AWBURST;
output  [1:0] m_axi_gmem1_AWLOCK;
output  [3:0] m_axi_gmem1_AWCACHE;
output  [2:0] m_axi_gmem1_AWPROT;
output  [3:0] m_axi_gmem1_AWQOS;
output  [3:0] m_axi_gmem1_AWREGION;
output  [0:0] m_axi_gmem1_AWUSER;
output   m_axi_gmem1_WVALID;
input   m_axi_gmem1_WREADY;
output  [31:0] m_axi_gmem1_WDATA;
output  [3:0] m_axi_gmem1_WSTRB;
output   m_axi_gmem1_WLAST;
output  [0:0] m_axi_gmem1_WID;
output  [0:0] m_axi_gmem1_WUSER;
output   m_axi_gmem1_ARVALID;
input   m_axi_gmem1_ARREADY;
output  [63:0] m_axi_gmem1_ARADDR;
output  [0:0] m_axi_gmem1_ARID;
output  [31:0] m_axi_gmem1_ARLEN;
output  [2:0] m_axi_gmem1_ARSIZE;
output  [1:0] m_axi_gmem1_ARBURST;
output  [1:0] m_axi_gmem1_ARLOCK;
output  [3:0] m_axi_gmem1_ARCACHE;
output  [2:0] m_axi_gmem1_ARPROT;
output  [3:0] m_axi_gmem1_ARQOS;
output  [3:0] m_axi_gmem1_ARREGION;
output  [0:0] m_axi_gmem1_ARUSER;
input   m_axi_gmem1_RVALID;
output   m_axi_gmem1_RREADY;
input  [31:0] m_axi_gmem1_RDATA;
input   m_axi_gmem1_RLAST;
input  [0:0] m_axi_gmem1_RID;
input  [8:0] m_axi_gmem1_RFIFONUM;
input  [0:0] m_axi_gmem1_RUSER;
input  [1:0] m_axi_gmem1_RRESP;
input   m_axi_gmem1_BVALID;
output   m_axi_gmem1_BREADY;
input  [1:0] m_axi_gmem1_BRESP;
input  [0:0] m_axi_gmem1_BID;
input  [0:0] m_axi_gmem1_BUSER;
input  [63:0] weights;
output  [10:0] p_ZL17g_fc3_weight_int8_0_address0;
output   p_ZL17g_fc3_weight_int8_0_ce0;
output   p_ZL17g_fc3_weight_int8_0_we0;
output  [7:0] p_ZL17g_fc3_weight_int8_0_d0;
output  [10:0] p_ZL17g_fc3_weight_int8_1_address0;
output   p_ZL17g_fc3_weight_int8_1_ce0;
output   p_ZL17g_fc3_weight_int8_1_we0;
output  [7:0] p_ZL17g_fc3_weight_int8_1_d0;

reg ap_idle;
reg m_axi_gmem1_ARVALID;
reg m_axi_gmem1_RREADY;
reg p_ZL17g_fc3_weight_int8_0_ce0;
reg p_ZL17g_fc3_weight_int8_0_we0;
reg p_ZL17g_fc3_weight_int8_1_ce0;
reg p_ZL17g_fc3_weight_int8_1_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
wire    ap_block_state9_pp0_stage0_iter8;
reg    ap_block_state10_pp0_stage0_iter9;
wire    ap_block_state11_pp0_stage0_iter10;
wire    ap_block_state12_pp0_stage0_iter11;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln255_fu_164_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    gmem1_blk_n_AR;
wire    ap_block_pp0_stage0;
reg    gmem1_blk_n_R;
reg    ap_block_pp0_stage0_11001;
wire   [4:0] select_ln255_1_fu_202_p3;
reg   [4:0] select_ln255_1_reg_378;
reg   [4:0] select_ln255_1_reg_378_pp0_iter1_reg;
reg   [4:0] select_ln255_1_reg_378_pp0_iter2_reg;
reg   [4:0] select_ln255_1_reg_378_pp0_iter3_reg;
reg   [4:0] select_ln255_1_reg_378_pp0_iter4_reg;
reg   [4:0] select_ln255_1_reg_378_pp0_iter5_reg;
reg   [4:0] select_ln255_1_reg_378_pp0_iter6_reg;
reg   [4:0] select_ln255_1_reg_378_pp0_iter7_reg;
reg   [4:0] select_ln255_1_reg_378_pp0_iter8_reg;
reg   [4:0] select_ln255_1_reg_378_pp0_iter9_reg;
reg   [4:0] select_ln255_1_reg_378_pp0_iter10_reg;
reg   [4:0] tmp_4_reg_384;
wire   [1:0] trunc_ln99_fu_220_p1;
reg   [1:0] trunc_ln99_reg_389;
reg   [1:0] trunc_ln99_reg_389_pp0_iter1_reg;
reg   [1:0] trunc_ln99_reg_389_pp0_iter2_reg;
reg   [1:0] trunc_ln99_reg_389_pp0_iter3_reg;
reg   [1:0] trunc_ln99_reg_389_pp0_iter4_reg;
reg   [1:0] trunc_ln99_reg_389_pp0_iter5_reg;
reg   [1:0] trunc_ln99_reg_389_pp0_iter6_reg;
reg   [1:0] trunc_ln99_reg_389_pp0_iter7_reg;
reg   [1:0] trunc_ln99_reg_389_pp0_iter8_reg;
reg   [1:0] trunc_ln99_reg_389_pp0_iter9_reg;
reg   [5:0] lshr_ln1_reg_394;
reg   [5:0] lshr_ln1_reg_394_pp0_iter1_reg;
reg   [5:0] lshr_ln1_reg_394_pp0_iter2_reg;
reg   [5:0] lshr_ln1_reg_394_pp0_iter3_reg;
reg   [5:0] lshr_ln1_reg_394_pp0_iter4_reg;
reg   [5:0] lshr_ln1_reg_394_pp0_iter5_reg;
reg   [5:0] lshr_ln1_reg_394_pp0_iter6_reg;
reg   [5:0] lshr_ln1_reg_394_pp0_iter7_reg;
reg   [5:0] lshr_ln1_reg_394_pp0_iter8_reg;
reg   [5:0] lshr_ln1_reg_394_pp0_iter9_reg;
reg   [5:0] lshr_ln1_reg_394_pp0_iter10_reg;
wire   [0:0] trunc_ln259_fu_234_p1;
reg   [0:0] trunc_ln259_reg_399;
reg   [0:0] trunc_ln259_reg_399_pp0_iter1_reg;
reg   [0:0] trunc_ln259_reg_399_pp0_iter2_reg;
reg   [0:0] trunc_ln259_reg_399_pp0_iter3_reg;
reg   [0:0] trunc_ln259_reg_399_pp0_iter4_reg;
reg   [0:0] trunc_ln259_reg_399_pp0_iter5_reg;
reg   [0:0] trunc_ln259_reg_399_pp0_iter6_reg;
reg   [0:0] trunc_ln259_reg_399_pp0_iter7_reg;
reg   [0:0] trunc_ln259_reg_399_pp0_iter8_reg;
reg   [0:0] trunc_ln259_reg_399_pp0_iter9_reg;
reg   [0:0] trunc_ln259_reg_399_pp0_iter10_reg;
reg   [63:0] gmem1_addr_reg_403;
reg   [31:0] word_V_reg_409;
wire   [7:0] bits_V_fu_332_p1;
reg   [7:0] bits_V_reg_414;
wire   [63:0] zext_ln259_fu_342_p1;
wire  signed [63:0] p_cast3_cast_fu_306_p1;
reg   [7:0] i_1_fu_90;
wire   [7:0] add_ln257_fu_238_p2;
wire    ap_loop_init;
reg   [7:0] ap_sig_allocacmp_i_1_load;
reg   [4:0] o_fu_94;
reg   [4:0] ap_sig_allocacmp_o_load;
reg   [11:0] indvar_flatten6_fu_98;
wire   [11:0] add_ln255_1_fu_170_p2;
reg   [11:0] ap_sig_allocacmp_indvar_flatten6_load;
wire   [0:0] icmp_ln257_fu_188_p2;
wire   [4:0] add_ln255_fu_182_p2;
wire   [7:0] select_ln255_fu_194_p3;
wire   [9:0] div_i_i8_udiv_fu_259_p3;
wire   [15:0] zext_ln126_2_fu_265_p1;
wire   [15:0] add_ln126_fu_269_p2;
wire   [17:0] tmp_5_fu_275_p3;
wire  signed [18:0] sext_ln126_fu_283_p1;
wire   [63:0] zext_ln126_fu_287_p1;
wire   [63:0] add_ln126_3_fu_291_p2;
wire   [61:0] p_cast3_fu_296_p4;
wire   [4:0] shl_ln99_2_fu_316_p3;
wire   [31:0] zext_ln628_fu_323_p1;
wire   [31:0] lshr_ln628_fu_327_p2;
wire   [10:0] tmp_7_fu_336_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_done_reg = 1'b0;
end

full_pose_accel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter10_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln255_fu_164_p2 == 1'd0))) begin
            i_1_fu_90 <= add_ln257_fu_238_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_1_fu_90 <= 8'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln255_fu_164_p2 == 1'd0))) begin
            indvar_flatten6_fu_98 <= add_ln255_1_fu_170_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten6_fu_98 <= 12'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln255_fu_164_p2 == 1'd0))) begin
            o_fu_94 <= select_ln255_1_fu_202_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            o_fu_94 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        bits_V_reg_414 <= bits_V_fu_332_p1;
        lshr_ln1_reg_394_pp0_iter10_reg <= lshr_ln1_reg_394_pp0_iter9_reg;
        lshr_ln1_reg_394_pp0_iter2_reg <= lshr_ln1_reg_394_pp0_iter1_reg;
        lshr_ln1_reg_394_pp0_iter3_reg <= lshr_ln1_reg_394_pp0_iter2_reg;
        lshr_ln1_reg_394_pp0_iter4_reg <= lshr_ln1_reg_394_pp0_iter3_reg;
        lshr_ln1_reg_394_pp0_iter5_reg <= lshr_ln1_reg_394_pp0_iter4_reg;
        lshr_ln1_reg_394_pp0_iter6_reg <= lshr_ln1_reg_394_pp0_iter5_reg;
        lshr_ln1_reg_394_pp0_iter7_reg <= lshr_ln1_reg_394_pp0_iter6_reg;
        lshr_ln1_reg_394_pp0_iter8_reg <= lshr_ln1_reg_394_pp0_iter7_reg;
        lshr_ln1_reg_394_pp0_iter9_reg <= lshr_ln1_reg_394_pp0_iter8_reg;
        select_ln255_1_reg_378_pp0_iter10_reg <= select_ln255_1_reg_378_pp0_iter9_reg;
        select_ln255_1_reg_378_pp0_iter2_reg <= select_ln255_1_reg_378_pp0_iter1_reg;
        select_ln255_1_reg_378_pp0_iter3_reg <= select_ln255_1_reg_378_pp0_iter2_reg;
        select_ln255_1_reg_378_pp0_iter4_reg <= select_ln255_1_reg_378_pp0_iter3_reg;
        select_ln255_1_reg_378_pp0_iter5_reg <= select_ln255_1_reg_378_pp0_iter4_reg;
        select_ln255_1_reg_378_pp0_iter6_reg <= select_ln255_1_reg_378_pp0_iter5_reg;
        select_ln255_1_reg_378_pp0_iter7_reg <= select_ln255_1_reg_378_pp0_iter6_reg;
        select_ln255_1_reg_378_pp0_iter8_reg <= select_ln255_1_reg_378_pp0_iter7_reg;
        select_ln255_1_reg_378_pp0_iter9_reg <= select_ln255_1_reg_378_pp0_iter8_reg;
        trunc_ln259_reg_399_pp0_iter10_reg <= trunc_ln259_reg_399_pp0_iter9_reg;
        trunc_ln259_reg_399_pp0_iter2_reg <= trunc_ln259_reg_399_pp0_iter1_reg;
        trunc_ln259_reg_399_pp0_iter3_reg <= trunc_ln259_reg_399_pp0_iter2_reg;
        trunc_ln259_reg_399_pp0_iter4_reg <= trunc_ln259_reg_399_pp0_iter3_reg;
        trunc_ln259_reg_399_pp0_iter5_reg <= trunc_ln259_reg_399_pp0_iter4_reg;
        trunc_ln259_reg_399_pp0_iter6_reg <= trunc_ln259_reg_399_pp0_iter5_reg;
        trunc_ln259_reg_399_pp0_iter7_reg <= trunc_ln259_reg_399_pp0_iter6_reg;
        trunc_ln259_reg_399_pp0_iter8_reg <= trunc_ln259_reg_399_pp0_iter7_reg;
        trunc_ln259_reg_399_pp0_iter9_reg <= trunc_ln259_reg_399_pp0_iter8_reg;
        trunc_ln99_reg_389_pp0_iter2_reg <= trunc_ln99_reg_389_pp0_iter1_reg;
        trunc_ln99_reg_389_pp0_iter3_reg <= trunc_ln99_reg_389_pp0_iter2_reg;
        trunc_ln99_reg_389_pp0_iter4_reg <= trunc_ln99_reg_389_pp0_iter3_reg;
        trunc_ln99_reg_389_pp0_iter5_reg <= trunc_ln99_reg_389_pp0_iter4_reg;
        trunc_ln99_reg_389_pp0_iter6_reg <= trunc_ln99_reg_389_pp0_iter5_reg;
        trunc_ln99_reg_389_pp0_iter7_reg <= trunc_ln99_reg_389_pp0_iter6_reg;
        trunc_ln99_reg_389_pp0_iter8_reg <= trunc_ln99_reg_389_pp0_iter7_reg;
        trunc_ln99_reg_389_pp0_iter9_reg <= trunc_ln99_reg_389_pp0_iter8_reg;
        word_V_reg_409 <= m_axi_gmem1_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        gmem1_addr_reg_403 <= p_cast3_cast_fu_306_p1;
        lshr_ln1_reg_394_pp0_iter1_reg <= lshr_ln1_reg_394;
        select_ln255_1_reg_378_pp0_iter1_reg <= select_ln255_1_reg_378;
        trunc_ln259_reg_399_pp0_iter1_reg <= trunc_ln259_reg_399;
        trunc_ln99_reg_389_pp0_iter1_reg <= trunc_ln99_reg_389;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln255_fu_164_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        lshr_ln1_reg_394 <= {{select_ln255_fu_194_p3[6:1]}};
        select_ln255_1_reg_378 <= select_ln255_1_fu_202_p3;
        tmp_4_reg_384 <= {{select_ln255_fu_194_p3[6:2]}};
        trunc_ln259_reg_399 <= trunc_ln259_fu_234_p1;
        trunc_ln99_reg_389 <= trunc_ln99_fu_220_p1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln255_fu_164_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter10_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_i_1_load = 8'd0;
    end else begin
        ap_sig_allocacmp_i_1_load = i_1_fu_90;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten6_load = 12'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten6_load = indvar_flatten6_fu_98;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_o_load = 5'd0;
    end else begin
        ap_sig_allocacmp_o_load = o_fu_94;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        gmem1_blk_n_AR = m_axi_gmem1_ARREADY;
    end else begin
        gmem1_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        gmem1_blk_n_R = m_axi_gmem1_RVALID;
    end else begin
        gmem1_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        m_axi_gmem1_ARVALID = 1'b1;
    end else begin
        m_axi_gmem1_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        m_axi_gmem1_RREADY = 1'b1;
    end else begin
        m_axi_gmem1_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_ZL17g_fc3_weight_int8_0_ce0 = 1'b1;
    end else begin
        p_ZL17g_fc3_weight_int8_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (trunc_ln259_reg_399_pp0_iter10_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_ZL17g_fc3_weight_int8_0_we0 = 1'b1;
    end else begin
        p_ZL17g_fc3_weight_int8_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_ZL17g_fc3_weight_int8_1_ce0 = 1'b1;
    end else begin
        p_ZL17g_fc3_weight_int8_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (trunc_ln259_reg_399_pp0_iter10_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_ZL17g_fc3_weight_int8_1_we0 = 1'b1;
    end else begin
        p_ZL17g_fc3_weight_int8_1_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln126_3_fu_291_p2 = (zext_ln126_fu_287_p1 + weights);

assign add_ln126_fu_269_p2 = ($signed(zext_ln126_2_fu_265_p1) + $signed(16'd39116));

assign add_ln255_1_fu_170_p2 = (ap_sig_allocacmp_indvar_flatten6_load + 12'd1);

assign add_ln255_fu_182_p2 = (ap_sig_allocacmp_o_load + 5'd1);

assign add_ln257_fu_238_p2 = (select_ln255_fu_194_p3 + 8'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((m_axi_gmem1_RVALID == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b1)) | ((m_axi_gmem1_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((m_axi_gmem1_RVALID == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b1)) | ((m_axi_gmem1_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)));
end

always @ (*) begin
    ap_block_state10_pp0_stage0_iter9 = (m_axi_gmem1_RVALID == 1'b0);
end

assign ap_block_state11_pp0_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign bits_V_fu_332_p1 = lshr_ln628_fu_327_p2[7:0];

assign div_i_i8_udiv_fu_259_p3 = {{select_ln255_1_reg_378}, {tmp_4_reg_384}};

assign icmp_ln255_fu_164_p2 = ((ap_sig_allocacmp_indvar_flatten6_load == 12'd3072) ? 1'b1 : 1'b0);

assign icmp_ln257_fu_188_p2 = ((ap_sig_allocacmp_i_1_load == 8'd128) ? 1'b1 : 1'b0);

assign lshr_ln628_fu_327_p2 = word_V_reg_409 >> zext_ln628_fu_323_p1;

assign m_axi_gmem1_ARADDR = gmem1_addr_reg_403;

assign m_axi_gmem1_ARBURST = 2'd0;

assign m_axi_gmem1_ARCACHE = 4'd0;

assign m_axi_gmem1_ARID = 1'd0;

assign m_axi_gmem1_ARLEN = 32'd1;

assign m_axi_gmem1_ARLOCK = 2'd0;

assign m_axi_gmem1_ARPROT = 3'd0;

assign m_axi_gmem1_ARQOS = 4'd0;

assign m_axi_gmem1_ARREGION = 4'd0;

assign m_axi_gmem1_ARSIZE = 3'd0;

assign m_axi_gmem1_ARUSER = 1'd0;

assign m_axi_gmem1_AWADDR = 64'd0;

assign m_axi_gmem1_AWBURST = 2'd0;

assign m_axi_gmem1_AWCACHE = 4'd0;

assign m_axi_gmem1_AWID = 1'd0;

assign m_axi_gmem1_AWLEN = 32'd0;

assign m_axi_gmem1_AWLOCK = 2'd0;

assign m_axi_gmem1_AWPROT = 3'd0;

assign m_axi_gmem1_AWQOS = 4'd0;

assign m_axi_gmem1_AWREGION = 4'd0;

assign m_axi_gmem1_AWSIZE = 3'd0;

assign m_axi_gmem1_AWUSER = 1'd0;

assign m_axi_gmem1_AWVALID = 1'b0;

assign m_axi_gmem1_BREADY = 1'b0;

assign m_axi_gmem1_WDATA = 32'd0;

assign m_axi_gmem1_WID = 1'd0;

assign m_axi_gmem1_WLAST = 1'b0;

assign m_axi_gmem1_WSTRB = 4'd0;

assign m_axi_gmem1_WUSER = 1'd0;

assign m_axi_gmem1_WVALID = 1'b0;

assign p_ZL17g_fc3_weight_int8_0_address0 = zext_ln259_fu_342_p1;

assign p_ZL17g_fc3_weight_int8_0_d0 = bits_V_reg_414;

assign p_ZL17g_fc3_weight_int8_1_address0 = zext_ln259_fu_342_p1;

assign p_ZL17g_fc3_weight_int8_1_d0 = bits_V_reg_414;

assign p_cast3_cast_fu_306_p1 = $signed(p_cast3_fu_296_p4);

assign p_cast3_fu_296_p4 = {{add_ln126_3_fu_291_p2[63:2]}};

assign select_ln255_1_fu_202_p3 = ((icmp_ln257_fu_188_p2[0:0] == 1'b1) ? add_ln255_fu_182_p2 : ap_sig_allocacmp_o_load);

assign select_ln255_fu_194_p3 = ((icmp_ln257_fu_188_p2[0:0] == 1'b1) ? 8'd0 : ap_sig_allocacmp_i_1_load);

assign sext_ln126_fu_283_p1 = $signed(tmp_5_fu_275_p3);

assign shl_ln99_2_fu_316_p3 = {{trunc_ln99_reg_389_pp0_iter9_reg}, {3'd0}};

assign tmp_5_fu_275_p3 = {{add_ln126_fu_269_p2}, {2'd0}};

assign tmp_7_fu_336_p3 = {{select_ln255_1_reg_378_pp0_iter10_reg}, {lshr_ln1_reg_394_pp0_iter10_reg}};

assign trunc_ln259_fu_234_p1 = select_ln255_fu_194_p3[0:0];

assign trunc_ln99_fu_220_p1 = select_ln255_fu_194_p3[1:0];

assign zext_ln126_2_fu_265_p1 = div_i_i8_udiv_fu_259_p3;

assign zext_ln126_fu_287_p1 = $unsigned(sext_ln126_fu_283_p1);

assign zext_ln259_fu_342_p1 = tmp_7_fu_336_p3;

assign zext_ln628_fu_323_p1 = shl_ln99_2_fu_316_p3;

endmodule //full_pose_accel_load_weight_blob_Pipeline_FC3_LOAD_WEIGHT_OUT_FC3_LOAD_WEIGHT_IN
