// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module full_pose_accel_conv2_receiver_2_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        select_ln378_2,
        select_ln376_1,
        trunc_ln397,
        p_mid146,
        notlhs_mid150,
        notrhs_mid152,
        zext_ln380_1,
        input_0_address0,
        input_0_ce0,
        input_0_q0,
        input_1_address0,
        input_1_ce0,
        input_1_q0,
        input_2_address0,
        input_2_ce0,
        input_2_q0,
        input_3_address0,
        input_3_ce0,
        input_3_q0,
        input_4_address0,
        input_4_ce0,
        input_4_q0,
        input_5_address0,
        input_5_ce0,
        input_5_q0,
        input_6_address0,
        input_6_ce0,
        input_6_q0,
        input_7_address0,
        input_7_ce0,
        input_7_q0,
        p_out,
        p_out_ap_vld,
        p_out1,
        p_out1_ap_vld,
        p_out2,
        p_out2_ap_vld,
        p_out3,
        p_out3_ap_vld,
        p_out4,
        p_out4_ap_vld,
        p_out5,
        p_out5_ap_vld,
        p_out6,
        p_out6_ap_vld,
        add_i2513_out,
        add_i2513_out_ap_vld,
        p_ZL19g_conv2_weight_int8_2_0_address0,
        p_ZL19g_conv2_weight_int8_2_0_ce0,
        p_ZL19g_conv2_weight_int8_2_0_q0,
        p_ZL19g_conv2_weight_int8_2_1_address0,
        p_ZL19g_conv2_weight_int8_2_1_ce0,
        p_ZL19g_conv2_weight_int8_2_1_q0,
        p_ZL19g_conv2_weight_int8_2_2_address0,
        p_ZL19g_conv2_weight_int8_2_2_ce0,
        p_ZL19g_conv2_weight_int8_2_2_q0,
        p_ZL19g_conv2_weight_int8_2_3_address0,
        p_ZL19g_conv2_weight_int8_2_3_ce0,
        p_ZL19g_conv2_weight_int8_2_3_q0,
        p_ZL19g_conv2_weight_int8_2_4_address0,
        p_ZL19g_conv2_weight_int8_2_4_ce0,
        p_ZL19g_conv2_weight_int8_2_4_q0,
        p_ZL19g_conv2_weight_int8_2_5_address0,
        p_ZL19g_conv2_weight_int8_2_5_ce0,
        p_ZL19g_conv2_weight_int8_2_5_q0,
        p_ZL19g_conv2_weight_int8_2_6_address0,
        p_ZL19g_conv2_weight_int8_2_6_ce0,
        p_ZL19g_conv2_weight_int8_2_6_q0,
        p_ZL19g_conv2_weight_int8_2_7_address0,
        p_ZL19g_conv2_weight_int8_2_7_ce0,
        p_ZL19g_conv2_weight_int8_2_7_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] select_ln378_2;
input  [5:0] select_ln376_1;
input  [2:0] trunc_ln397;
input  [8:0] p_mid146;
input  [0:0] notlhs_mid150;
input  [0:0] notrhs_mid152;
input  [3:0] zext_ln380_1;
output  [11:0] input_0_address0;
output   input_0_ce0;
input  [7:0] input_0_q0;
output  [11:0] input_1_address0;
output   input_1_ce0;
input  [7:0] input_1_q0;
output  [11:0] input_2_address0;
output   input_2_ce0;
input  [7:0] input_2_q0;
output  [11:0] input_3_address0;
output   input_3_ce0;
input  [7:0] input_3_q0;
output  [11:0] input_4_address0;
output   input_4_ce0;
input  [7:0] input_4_q0;
output  [11:0] input_5_address0;
output   input_5_ce0;
input  [7:0] input_5_q0;
output  [11:0] input_6_address0;
output   input_6_ce0;
input  [7:0] input_6_q0;
output  [11:0] input_7_address0;
output   input_7_ce0;
input  [7:0] input_7_q0;
output  [31:0] p_out;
output   p_out_ap_vld;
output  [31:0] p_out1;
output   p_out1_ap_vld;
output  [31:0] p_out2;
output   p_out2_ap_vld;
output  [31:0] p_out3;
output   p_out3_ap_vld;
output  [31:0] p_out4;
output   p_out4_ap_vld;
output  [31:0] p_out5;
output   p_out5_ap_vld;
output  [31:0] p_out6;
output   p_out6_ap_vld;
output  [31:0] add_i2513_out;
output   add_i2513_out_ap_vld;
output  [9:0] p_ZL19g_conv2_weight_int8_2_0_address0;
output   p_ZL19g_conv2_weight_int8_2_0_ce0;
input  [7:0] p_ZL19g_conv2_weight_int8_2_0_q0;
output  [9:0] p_ZL19g_conv2_weight_int8_2_1_address0;
output   p_ZL19g_conv2_weight_int8_2_1_ce0;
input  [7:0] p_ZL19g_conv2_weight_int8_2_1_q0;
output  [9:0] p_ZL19g_conv2_weight_int8_2_2_address0;
output   p_ZL19g_conv2_weight_int8_2_2_ce0;
input  [7:0] p_ZL19g_conv2_weight_int8_2_2_q0;
output  [9:0] p_ZL19g_conv2_weight_int8_2_3_address0;
output   p_ZL19g_conv2_weight_int8_2_3_ce0;
input  [7:0] p_ZL19g_conv2_weight_int8_2_3_q0;
output  [9:0] p_ZL19g_conv2_weight_int8_2_4_address0;
output   p_ZL19g_conv2_weight_int8_2_4_ce0;
input  [7:0] p_ZL19g_conv2_weight_int8_2_4_q0;
output  [9:0] p_ZL19g_conv2_weight_int8_2_5_address0;
output   p_ZL19g_conv2_weight_int8_2_5_ce0;
input  [7:0] p_ZL19g_conv2_weight_int8_2_5_q0;
output  [9:0] p_ZL19g_conv2_weight_int8_2_6_address0;
output   p_ZL19g_conv2_weight_int8_2_6_ce0;
input  [7:0] p_ZL19g_conv2_weight_int8_2_6_q0;
output  [9:0] p_ZL19g_conv2_weight_int8_2_7_address0;
output   p_ZL19g_conv2_weight_int8_2_7_ce0;
input  [7:0] p_ZL19g_conv2_weight_int8_2_7_q0;

reg ap_idle;
reg input_0_ce0;
reg input_1_ce0;
reg input_2_ce0;
reg input_3_ce0;
reg input_4_ce0;
reg input_5_ce0;
reg input_6_ce0;
reg input_7_ce0;
reg p_out_ap_vld;
reg p_out1_ap_vld;
reg p_out2_ap_vld;
reg p_out3_ap_vld;
reg p_out4_ap_vld;
reg p_out5_ap_vld;
reg p_out6_ap_vld;
reg add_i2513_out_ap_vld;
reg p_ZL19g_conv2_weight_int8_2_0_ce0;
reg p_ZL19g_conv2_weight_int8_2_1_ce0;
reg p_ZL19g_conv2_weight_int8_2_2_ce0;
reg p_ZL19g_conv2_weight_int8_2_3_ce0;
reg p_ZL19g_conv2_weight_int8_2_4_ce0;
reg p_ZL19g_conv2_weight_int8_2_5_ce0;
reg p_ZL19g_conv2_weight_int8_2_6_ce0;
reg p_ZL19g_conv2_weight_int8_2_7_ce0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln385_fu_618_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [4:0] zext_ln380_1_cast_fu_546_p1;
reg   [4:0] zext_ln380_1_cast_reg_1487;
reg   [0:0] icmp_ln385_reg_1492;
reg   [0:0] icmp_ln385_reg_1492_pp0_iter1_reg;
reg   [0:0] icmp_ln385_reg_1492_pp0_iter2_reg;
reg   [0:0] icmp_ln385_reg_1492_pp0_iter3_reg;
reg   [0:0] icmp_ln385_reg_1492_pp0_iter4_reg;
reg   [0:0] icmp_ln385_reg_1492_pp0_iter5_reg;
wire   [0:0] icmp_ln387_fu_633_p2;
reg   [0:0] icmp_ln387_reg_1496;
reg   [0:0] icmp_ln387_reg_1496_pp0_iter1_reg;
reg   [0:0] icmp_ln387_reg_1496_pp0_iter2_reg;
wire   [7:0] empty_148_fu_670_p2;
reg   [7:0] empty_148_reg_1507;
reg   [0:0] tmp_37_reg_1513;
wire   [0:0] and_ln385_fu_720_p2;
reg   [0:0] and_ln385_reg_1520;
reg   [0:0] and_ln385_reg_1520_pp0_iter2_reg;
wire   [1:0] select_ln387_fu_737_p3;
reg   [1:0] select_ln387_reg_1527;
reg   [1:0] select_ln387_reg_1527_pp0_iter2_reg;
wire   [1:0] select_ln387_1_fu_745_p3;
reg   [1:0] select_ln387_1_reg_1533;
wire   [7:0] p_mid1_fu_757_p2;
reg   [7:0] p_mid1_reg_1538;
wire   [0:0] notlhs_fu_792_p2;
reg   [0:0] notlhs_reg_1544;
wire   [0:0] icmp_fu_807_p2;
reg   [0:0] icmp_reg_1549;
wire   [9:0] trunc_ln397_1_fu_884_p1;
reg   [9:0] trunc_ln397_1_reg_1554;
wire   [7:0] trunc_ln397_2_fu_888_p1;
reg   [7:0] trunc_ln397_2_reg_1559;
wire   [9:0] add_ln397_1_fu_912_p2;
reg   [9:0] add_ln397_1_reg_1564;
wire   [8:0] trunc_ln397_3_fu_918_p1;
reg   [8:0] trunc_ln397_3_reg_1569;
wire   [0:0] notlhs_mid1_fu_922_p2;
reg   [0:0] notlhs_mid1_reg_1574;
wire   [0:0] icmp32_fu_937_p2;
reg   [0:0] icmp32_reg_1579;
wire  signed [4:0] add_ln392_1_fu_956_p2;
reg  signed [4:0] add_ln392_1_reg_1584;
wire   [9:0] add_ln397_3_fu_1016_p2;
reg   [9:0] add_ln397_3_reg_1590;
wire   [11:0] add_ln397_4_fu_1031_p2;
reg   [11:0] add_ln397_4_reg_1595;
wire   [0:0] and_ln393_fu_1048_p2;
reg   [0:0] and_ln393_reg_1600;
reg   [0:0] and_ln393_reg_1600_pp0_iter4_reg;
reg   [0:0] and_ln393_reg_1600_pp0_iter5_reg;
reg   [0:0] and_ln393_reg_1600_pp0_iter6_reg;
reg    ap_condition_exit_pp0_iter2_stage0;
wire   [63:0] zext_ln397_6_fu_1054_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln397_7_fu_1065_p1;
reg  signed [31:0] add_i2513_fu_188;
wire   [31:0] select_ln393_7_fu_1206_p3;
wire    ap_loop_init;
reg  signed [31:0] empty_fu_192;
wire   [31:0] select_ln393_6_fu_1200_p3;
reg  signed [31:0] empty_142_fu_196;
wire   [31:0] select_ln393_5_fu_1194_p3;
reg  signed [31:0] empty_143_fu_200;
wire   [31:0] select_ln393_4_fu_1188_p3;
reg  signed [31:0] empty_144_fu_204;
wire   [31:0] select_ln393_3_fu_1182_p3;
reg  signed [31:0] empty_145_fu_208;
wire   [31:0] select_ln393_2_fu_1176_p3;
reg  signed [31:0] empty_146_fu_212;
wire   [31:0] select_ln393_1_fu_1170_p3;
reg  signed [31:0] empty_147_fu_216;
wire   [31:0] select_ln393_fu_1164_p3;
reg   [1:0] kw_fu_220;
wire   [1:0] add_ln389_fu_762_p2;
reg   [1:0] kh_fu_224;
reg   [3:0] indvar_flatten_fu_228;
wire   [3:0] select_ln387_5_fu_645_p3;
reg   [3:0] ap_sig_allocacmp_indvar_flatten_load;
reg   [4:0] ic_fu_232;
wire   [4:0] select_ln385_1_fu_694_p3;
reg   [4:0] indvar_flatten56_fu_236;
wire   [4:0] add_ln385_1_fu_624_p2;
reg   [4:0] ap_sig_allocacmp_indvar_flatten56_load;
wire    ap_block_pp0_stage0_01001;
wire   [3:0] add_ln387_1_fu_639_p2;
wire   [7:0] zext_ln387_fu_666_p1;
wire   [4:0] add_ln385_fu_681_p2;
wire   [0:0] icmp_ln389_fu_714_p2;
wire   [0:0] xor_ln385_fu_709_p2;
wire   [1:0] select_ln385_fu_687_p3;
wire   [0:0] or_ln387_fu_732_p2;
wire   [1:0] add_ln387_fu_726_p2;
wire   [7:0] zext_ln387_1_fu_753_p1;
wire   [8:0] p_cast_fu_783_p1;
wire   [8:0] empty_149_fu_786_p2;
wire   [1:0] tmp_fu_797_p4;
wire   [2:0] tmp_s_fu_813_p4;
wire   [6:0] tmp_6_fu_822_p4;
wire   [8:0] tmp_7_fu_834_p5;
wire   [9:0] zext_ln397_1_fu_844_p1;
wire   [9:0] zext_ln397_fu_830_p1;
wire   [9:0] sub_ln397_fu_848_p2;
wire   [7:0] tmp_8_fu_858_p3;
wire  signed [10:0] sext_ln397_fu_854_p1;
wire   [10:0] zext_ln397_2_fu_875_p1;
wire   [10:0] add_ln397_fu_878_p2;
wire   [8:0] p_cast_mid1_fu_892_p1;
wire   [8:0] p_mid110_fu_895_p2;
wire   [8:0] select_ln385_2_fu_869_p3;
wire   [8:0] select_ln387_2_fu_901_p3;
wire   [9:0] zext_ln385_fu_865_p1;
wire   [9:0] zext_ln397_3_fu_908_p1;
wire   [1:0] tmp_39_fu_927_p4;
wire   [2:0] zext_ln389_fu_943_p1;
wire   [2:0] add_ln392_fu_946_p2;
wire  signed [4:0] sext_ln392_fu_952_p1;
wire   [9:0] p_shl6_fu_971_p3;
wire   [10:0] tmp_38_fu_990_p3;
wire   [0:0] select_ln385_3_fu_961_p3;
wire   [0:0] select_ln385_4_fu_966_p3;
wire   [9:0] sub_ln397_1_fu_978_p2;
wire   [9:0] zext_ln397_5_fu_1013_p1;
wire   [11:0] p_shl4_fu_983_p3;
wire   [11:0] zext_ln397_4_fu_997_p1;
wire   [11:0] add_ln397_2_fu_1025_p2;
wire  signed [11:0] sext_ln397_1_fu_1022_p1;
wire   [0:0] select_ln387_3_fu_1001_p3;
wire   [0:0] icmp_ln393_fu_1037_p2;
wire   [0:0] and_ln393_1_fu_1042_p2;
wire   [0:0] select_ln387_4_fu_1007_p3;
wire  signed [31:0] grp_fu_1347_p3;
wire  signed [31:0] grp_fu_1338_p3;
wire  signed [31:0] grp_fu_1329_p3;
wire  signed [31:0] grp_fu_1320_p3;
wire  signed [31:0] grp_fu_1311_p3;
wire  signed [31:0] grp_fu_1302_p3;
wire  signed [31:0] grp_fu_1293_p3;
wire  signed [31:0] grp_fu_1284_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_done_reg = 1'b0;
end

full_pose_accel_mac_muladd_8s_8s_32s_32_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mac_muladd_8s_8s_32s_32_3_1_U518(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(p_ZL19g_conv2_weight_int8_2_0_q0),
    .din1(input_0_q0),
    .din2(add_i2513_fu_188),
    .ce(1'b1),
    .dout(grp_fu_1284_p3)
);

full_pose_accel_mac_muladd_8s_8s_32s_32_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mac_muladd_8s_8s_32s_32_3_1_U519(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(p_ZL19g_conv2_weight_int8_2_1_q0),
    .din1(input_1_q0),
    .din2(empty_fu_192),
    .ce(1'b1),
    .dout(grp_fu_1293_p3)
);

full_pose_accel_mac_muladd_8s_8s_32s_32_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mac_muladd_8s_8s_32s_32_3_1_U520(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(p_ZL19g_conv2_weight_int8_2_2_q0),
    .din1(input_2_q0),
    .din2(empty_142_fu_196),
    .ce(1'b1),
    .dout(grp_fu_1302_p3)
);

full_pose_accel_mac_muladd_8s_8s_32s_32_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mac_muladd_8s_8s_32s_32_3_1_U521(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(p_ZL19g_conv2_weight_int8_2_3_q0),
    .din1(input_3_q0),
    .din2(empty_143_fu_200),
    .ce(1'b1),
    .dout(grp_fu_1311_p3)
);

full_pose_accel_mac_muladd_8s_8s_32s_32_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mac_muladd_8s_8s_32s_32_3_1_U522(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(p_ZL19g_conv2_weight_int8_2_4_q0),
    .din1(input_4_q0),
    .din2(empty_144_fu_204),
    .ce(1'b1),
    .dout(grp_fu_1320_p3)
);

full_pose_accel_mac_muladd_8s_8s_32s_32_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mac_muladd_8s_8s_32s_32_3_1_U523(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(p_ZL19g_conv2_weight_int8_2_5_q0),
    .din1(input_5_q0),
    .din2(empty_145_fu_208),
    .ce(1'b1),
    .dout(grp_fu_1329_p3)
);

full_pose_accel_mac_muladd_8s_8s_32s_32_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mac_muladd_8s_8s_32s_32_3_1_U524(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(p_ZL19g_conv2_weight_int8_2_6_q0),
    .din1(input_6_q0),
    .din2(empty_146_fu_212),
    .ce(1'b1),
    .dout(grp_fu_1338_p3)
);

full_pose_accel_mac_muladd_8s_8s_32s_32_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mac_muladd_8s_8s_32s_32_3_1_U525(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(p_ZL19g_conv2_weight_int8_2_7_q0),
    .din1(input_7_q0),
    .din2(empty_147_fu_216),
    .ce(1'b1),
    .dout(grp_fu_1347_p3)
);

full_pose_accel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter6_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter2_stage0)) begin
            ap_enable_reg_pp0_iter3 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            add_i2513_fu_188 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter7 == 1'b1)) begin
            add_i2513_fu_188 <= select_ln393_7_fu_1206_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            empty_142_fu_196 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter7 == 1'b1)) begin
            empty_142_fu_196 <= select_ln393_5_fu_1194_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            empty_143_fu_200 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter7 == 1'b1)) begin
            empty_143_fu_200 <= select_ln393_4_fu_1188_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            empty_144_fu_204 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter7 == 1'b1)) begin
            empty_144_fu_204 <= select_ln393_3_fu_1182_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            empty_145_fu_208 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter7 == 1'b1)) begin
            empty_145_fu_208 <= select_ln393_2_fu_1176_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            empty_146_fu_212 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter7 == 1'b1)) begin
            empty_146_fu_212 <= select_ln393_1_fu_1170_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            empty_147_fu_216 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter7 == 1'b1)) begin
            empty_147_fu_216 <= select_ln393_fu_1164_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            empty_fu_192 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter7 == 1'b1)) begin
            empty_fu_192 <= select_ln393_6_fu_1200_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            ic_fu_232 <= 5'd0;
        end else if (((icmp_ln385_reg_1492 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            ic_fu_232 <= select_ln385_1_fu_694_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln385_fu_618_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten56_fu_236 <= add_ln385_1_fu_624_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten56_fu_236 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln385_fu_618_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten_fu_228 <= select_ln387_5_fu_645_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_228 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            kh_fu_224 <= 2'd0;
        end else if (((icmp_ln385_reg_1492 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            kh_fu_224 <= select_ln387_1_fu_745_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            kw_fu_220 <= 2'd0;
        end else if (((icmp_ln385_reg_1492 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            kw_fu_220 <= add_ln389_fu_762_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln385_reg_1492_pp0_iter1_reg == 1'd0))) begin
        add_ln392_1_reg_1584 <= add_ln392_1_fu_956_p2;
        add_ln397_1_reg_1564 <= add_ln397_1_fu_912_p2;
        trunc_ln397_1_reg_1554 <= trunc_ln397_1_fu_884_p1;
        trunc_ln397_2_reg_1559 <= trunc_ln397_2_fu_888_p1;
        trunc_ln397_3_reg_1569 <= trunc_ln397_3_fu_918_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln397_3_reg_1590 <= add_ln397_3_fu_1016_p2;
        add_ln397_4_reg_1595 <= add_ln397_4_fu_1031_p2;
        and_ln385_reg_1520_pp0_iter2_reg <= and_ln385_reg_1520;
        and_ln393_reg_1600 <= and_ln393_fu_1048_p2;
        and_ln393_reg_1600_pp0_iter4_reg <= and_ln393_reg_1600;
        and_ln393_reg_1600_pp0_iter5_reg <= and_ln393_reg_1600_pp0_iter4_reg;
        and_ln393_reg_1600_pp0_iter6_reg <= and_ln393_reg_1600_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        icmp_ln385_reg_1492_pp0_iter2_reg <= icmp_ln385_reg_1492_pp0_iter1_reg;
        icmp_ln385_reg_1492_pp0_iter3_reg <= icmp_ln385_reg_1492_pp0_iter2_reg;
        icmp_ln385_reg_1492_pp0_iter4_reg <= icmp_ln385_reg_1492_pp0_iter3_reg;
        icmp_ln385_reg_1492_pp0_iter5_reg <= icmp_ln385_reg_1492_pp0_iter4_reg;
        icmp_ln387_reg_1496_pp0_iter2_reg <= icmp_ln387_reg_1496_pp0_iter1_reg;
        select_ln387_reg_1527_pp0_iter2_reg <= select_ln387_reg_1527;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln385_reg_1492 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        and_ln385_reg_1520 <= and_ln385_fu_720_p2;
        p_mid1_reg_1538 <= p_mid1_fu_757_p2;
        select_ln387_1_reg_1533 <= select_ln387_1_fu_745_p3;
        select_ln387_reg_1527 <= select_ln387_fu_737_p3;
        tmp_37_reg_1513 <= select_ln385_1_fu_694_p3[32'd3];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        empty_148_reg_1507 <= empty_148_fu_670_p2;
        icmp_ln385_reg_1492 <= icmp_ln385_fu_618_p2;
        icmp_ln385_reg_1492_pp0_iter1_reg <= icmp_ln385_reg_1492;
        icmp_ln387_reg_1496_pp0_iter1_reg <= icmp_ln387_reg_1496;
        zext_ln380_1_cast_reg_1487[3 : 0] <= zext_ln380_1_cast_fu_546_p1[3 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == and_ln385_reg_1520) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln385_reg_1492_pp0_iter1_reg == 1'd0))) begin
        icmp32_reg_1579 <= icmp32_fu_937_p2;
        notlhs_mid1_reg_1574 <= notlhs_mid1_fu_922_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln385_fu_618_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln387_reg_1496 <= icmp_ln387_fu_633_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln387_reg_1496_pp0_iter1_reg == 1'd0) & (1'd0 == and_ln385_reg_1520))) begin
        icmp_reg_1549 <= icmp_fu_807_p2;
        notlhs_reg_1544 <= notlhs_fu_792_p2;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln385_reg_1492_pp0_iter5_reg == 1'd1))) begin
        add_i2513_out_ap_vld = 1'b1;
    end else begin
        add_i2513_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln385_fu_618_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln385_reg_1492_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_condition_exit_pp0_iter2_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter2_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter6_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten56_load = 5'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten56_load = indvar_flatten56_fu_236;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten_load = 4'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_228;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        input_0_ce0 = 1'b1;
    end else begin
        input_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        input_1_ce0 = 1'b1;
    end else begin
        input_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        input_2_ce0 = 1'b1;
    end else begin
        input_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        input_3_ce0 = 1'b1;
    end else begin
        input_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        input_4_ce0 = 1'b1;
    end else begin
        input_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        input_5_ce0 = 1'b1;
    end else begin
        input_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        input_6_ce0 = 1'b1;
    end else begin
        input_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        input_7_ce0 = 1'b1;
    end else begin
        input_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        p_ZL19g_conv2_weight_int8_2_0_ce0 = 1'b1;
    end else begin
        p_ZL19g_conv2_weight_int8_2_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        p_ZL19g_conv2_weight_int8_2_1_ce0 = 1'b1;
    end else begin
        p_ZL19g_conv2_weight_int8_2_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        p_ZL19g_conv2_weight_int8_2_2_ce0 = 1'b1;
    end else begin
        p_ZL19g_conv2_weight_int8_2_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        p_ZL19g_conv2_weight_int8_2_3_ce0 = 1'b1;
    end else begin
        p_ZL19g_conv2_weight_int8_2_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        p_ZL19g_conv2_weight_int8_2_4_ce0 = 1'b1;
    end else begin
        p_ZL19g_conv2_weight_int8_2_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        p_ZL19g_conv2_weight_int8_2_5_ce0 = 1'b1;
    end else begin
        p_ZL19g_conv2_weight_int8_2_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        p_ZL19g_conv2_weight_int8_2_6_ce0 = 1'b1;
    end else begin
        p_ZL19g_conv2_weight_int8_2_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        p_ZL19g_conv2_weight_int8_2_7_ce0 = 1'b1;
    end else begin
        p_ZL19g_conv2_weight_int8_2_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln385_reg_1492_pp0_iter5_reg == 1'd1))) begin
        p_out1_ap_vld = 1'b1;
    end else begin
        p_out1_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln385_reg_1492_pp0_iter5_reg == 1'd1))) begin
        p_out2_ap_vld = 1'b1;
    end else begin
        p_out2_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln385_reg_1492_pp0_iter5_reg == 1'd1))) begin
        p_out3_ap_vld = 1'b1;
    end else begin
        p_out3_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln385_reg_1492_pp0_iter5_reg == 1'd1))) begin
        p_out4_ap_vld = 1'b1;
    end else begin
        p_out4_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln385_reg_1492_pp0_iter5_reg == 1'd1))) begin
        p_out5_ap_vld = 1'b1;
    end else begin
        p_out5_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln385_reg_1492_pp0_iter5_reg == 1'd1))) begin
        p_out6_ap_vld = 1'b1;
    end else begin
        p_out6_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln385_reg_1492_pp0_iter5_reg == 1'd1))) begin
        p_out_ap_vld = 1'b1;
    end else begin
        p_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_i2513_out = add_i2513_fu_188;

assign add_ln385_1_fu_624_p2 = (ap_sig_allocacmp_indvar_flatten56_load + 5'd1);

assign add_ln385_fu_681_p2 = (ic_fu_232 + 5'd8);

assign add_ln387_1_fu_639_p2 = (ap_sig_allocacmp_indvar_flatten_load + 4'd1);

assign add_ln387_fu_726_p2 = (select_ln385_fu_687_p3 + 2'd1);

assign add_ln389_fu_762_p2 = (select_ln387_fu_737_p3 + 2'd1);

assign add_ln392_1_fu_956_p2 = ($signed(sext_ln392_fu_952_p1) + $signed(zext_ln380_1_cast_reg_1487));

assign add_ln392_fu_946_p2 = ($signed(zext_ln389_fu_943_p1) + $signed(3'd7));

assign add_ln397_1_fu_912_p2 = (zext_ln385_fu_865_p1 + zext_ln397_3_fu_908_p1);

assign add_ln397_2_fu_1025_p2 = (p_shl4_fu_983_p3 + zext_ln397_4_fu_997_p1);

assign add_ln397_3_fu_1016_p2 = (sub_ln397_1_fu_978_p2 + zext_ln397_5_fu_1013_p1);

assign add_ln397_4_fu_1031_p2 = ($signed(add_ln397_2_fu_1025_p2) + $signed(sext_ln397_1_fu_1022_p1));

assign add_ln397_fu_878_p2 = ($signed(sext_ln397_fu_854_p1) + $signed(zext_ln397_2_fu_875_p1));

assign and_ln385_fu_720_p2 = (xor_ln385_fu_709_p2 & icmp_ln389_fu_714_p2);

assign and_ln393_1_fu_1042_p2 = (select_ln387_3_fu_1001_p3 & icmp_ln393_fu_1037_p2);

assign and_ln393_fu_1048_p2 = (select_ln387_4_fu_1007_p3 & and_ln393_1_fu_1042_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign empty_148_fu_670_p2 = (select_ln378_2 + zext_ln387_fu_666_p1);

assign empty_149_fu_786_p2 = ($signed(p_cast_fu_783_p1) + $signed(9'd511));

assign icmp32_fu_937_p2 = ((tmp_39_fu_927_p4 != 2'd1) ? 1'b1 : 1'b0);

assign icmp_fu_807_p2 = ((tmp_fu_797_p4 != 2'd1) ? 1'b1 : 1'b0);

assign icmp_ln385_fu_618_p2 = ((ap_sig_allocacmp_indvar_flatten56_load == 5'd18) ? 1'b1 : 1'b0);

assign icmp_ln387_fu_633_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 4'd9) ? 1'b1 : 1'b0);

assign icmp_ln389_fu_714_p2 = ((kw_fu_220 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln393_fu_1037_p2 = ((add_ln392_1_reg_1584 < 5'd10) ? 1'b1 : 1'b0);

assign input_0_address0 = zext_ln397_7_fu_1065_p1;

assign input_1_address0 = zext_ln397_7_fu_1065_p1;

assign input_2_address0 = zext_ln397_7_fu_1065_p1;

assign input_3_address0 = zext_ln397_7_fu_1065_p1;

assign input_4_address0 = zext_ln397_7_fu_1065_p1;

assign input_5_address0 = zext_ln397_7_fu_1065_p1;

assign input_6_address0 = zext_ln397_7_fu_1065_p1;

assign input_7_address0 = zext_ln397_7_fu_1065_p1;

assign notlhs_fu_792_p2 = ((empty_148_reg_1507 != 8'd0) ? 1'b1 : 1'b0);

assign notlhs_mid1_fu_922_p2 = ((p_mid1_reg_1538 != 8'd0) ? 1'b1 : 1'b0);

assign or_ln387_fu_732_p2 = (icmp_ln387_reg_1496 | and_ln385_fu_720_p2);

assign p_ZL19g_conv2_weight_int8_2_0_address0 = zext_ln397_6_fu_1054_p1;

assign p_ZL19g_conv2_weight_int8_2_1_address0 = zext_ln397_6_fu_1054_p1;

assign p_ZL19g_conv2_weight_int8_2_2_address0 = zext_ln397_6_fu_1054_p1;

assign p_ZL19g_conv2_weight_int8_2_3_address0 = zext_ln397_6_fu_1054_p1;

assign p_ZL19g_conv2_weight_int8_2_4_address0 = zext_ln397_6_fu_1054_p1;

assign p_ZL19g_conv2_weight_int8_2_5_address0 = zext_ln397_6_fu_1054_p1;

assign p_ZL19g_conv2_weight_int8_2_6_address0 = zext_ln397_6_fu_1054_p1;

assign p_ZL19g_conv2_weight_int8_2_7_address0 = zext_ln397_6_fu_1054_p1;

assign p_cast_fu_783_p1 = empty_148_reg_1507;

assign p_cast_mid1_fu_892_p1 = p_mid1_reg_1538;

assign p_mid110_fu_895_p2 = ($signed(p_cast_mid1_fu_892_p1) + $signed(9'd511));

assign p_mid1_fu_757_p2 = (select_ln378_2 + zext_ln387_1_fu_753_p1);

assign p_out = empty_147_fu_216;

assign p_out1 = empty_146_fu_212;

assign p_out2 = empty_145_fu_208;

assign p_out3 = empty_144_fu_204;

assign p_out4 = empty_143_fu_200;

assign p_out5 = empty_142_fu_196;

assign p_out6 = empty_fu_192;

assign p_shl4_fu_983_p3 = {{trunc_ln397_3_reg_1569}, {3'd0}};

assign p_shl6_fu_971_p3 = {{trunc_ln397_2_reg_1559}, {2'd0}};

assign select_ln385_1_fu_694_p3 = ((icmp_ln387_reg_1496[0:0] == 1'b1) ? add_ln385_fu_681_p2 : ic_fu_232);

assign select_ln385_2_fu_869_p3 = ((icmp_ln387_reg_1496_pp0_iter1_reg[0:0] == 1'b1) ? p_mid146 : empty_149_fu_786_p2);

assign select_ln385_3_fu_961_p3 = ((icmp_ln387_reg_1496_pp0_iter2_reg[0:0] == 1'b1) ? notlhs_mid150 : notlhs_reg_1544);

assign select_ln385_4_fu_966_p3 = ((icmp_ln387_reg_1496_pp0_iter2_reg[0:0] == 1'b1) ? notrhs_mid152 : icmp_reg_1549);

assign select_ln385_fu_687_p3 = ((icmp_ln387_reg_1496[0:0] == 1'b1) ? 2'd0 : kh_fu_224);

assign select_ln387_1_fu_745_p3 = ((and_ln385_fu_720_p2[0:0] == 1'b1) ? add_ln387_fu_726_p2 : select_ln385_fu_687_p3);

assign select_ln387_2_fu_901_p3 = ((and_ln385_reg_1520[0:0] == 1'b1) ? p_mid110_fu_895_p2 : select_ln385_2_fu_869_p3);

assign select_ln387_3_fu_1001_p3 = ((and_ln385_reg_1520_pp0_iter2_reg[0:0] == 1'b1) ? notlhs_mid1_reg_1574 : select_ln385_3_fu_961_p3);

assign select_ln387_4_fu_1007_p3 = ((and_ln385_reg_1520_pp0_iter2_reg[0:0] == 1'b1) ? icmp32_reg_1579 : select_ln385_4_fu_966_p3);

assign select_ln387_5_fu_645_p3 = ((icmp_ln387_fu_633_p2[0:0] == 1'b1) ? 4'd1 : add_ln387_1_fu_639_p2);

assign select_ln387_fu_737_p3 = ((or_ln387_fu_732_p2[0:0] == 1'b1) ? 2'd0 : kw_fu_220);

assign select_ln393_1_fu_1170_p3 = ((and_ln393_reg_1600_pp0_iter6_reg[0:0] == 1'b1) ? grp_fu_1338_p3 : empty_146_fu_212);

assign select_ln393_2_fu_1176_p3 = ((and_ln393_reg_1600_pp0_iter6_reg[0:0] == 1'b1) ? grp_fu_1329_p3 : empty_145_fu_208);

assign select_ln393_3_fu_1182_p3 = ((and_ln393_reg_1600_pp0_iter6_reg[0:0] == 1'b1) ? grp_fu_1320_p3 : empty_144_fu_204);

assign select_ln393_4_fu_1188_p3 = ((and_ln393_reg_1600_pp0_iter6_reg[0:0] == 1'b1) ? grp_fu_1311_p3 : empty_143_fu_200);

assign select_ln393_5_fu_1194_p3 = ((and_ln393_reg_1600_pp0_iter6_reg[0:0] == 1'b1) ? grp_fu_1302_p3 : empty_142_fu_196);

assign select_ln393_6_fu_1200_p3 = ((and_ln393_reg_1600_pp0_iter6_reg[0:0] == 1'b1) ? grp_fu_1293_p3 : empty_fu_192);

assign select_ln393_7_fu_1206_p3 = ((and_ln393_reg_1600_pp0_iter6_reg[0:0] == 1'b1) ? grp_fu_1284_p3 : add_i2513_fu_188);

assign select_ln393_fu_1164_p3 = ((and_ln393_reg_1600_pp0_iter6_reg[0:0] == 1'b1) ? grp_fu_1347_p3 : empty_147_fu_216);

assign sext_ln392_fu_952_p1 = $signed(add_ln392_fu_946_p2);

assign sext_ln397_1_fu_1022_p1 = add_ln392_1_reg_1584;

assign sext_ln397_fu_854_p1 = $signed(sub_ln397_fu_848_p2);

assign sub_ln397_1_fu_978_p2 = (p_shl6_fu_971_p3 - trunc_ln397_1_reg_1554);

assign sub_ln397_fu_848_p2 = (zext_ln397_1_fu_844_p1 - zext_ln397_fu_830_p1);

assign tmp_38_fu_990_p3 = {{add_ln397_1_reg_1564}, {1'd0}};

assign tmp_39_fu_927_p4 = {{p_mid110_fu_895_p2[8:7]}};

assign tmp_6_fu_822_p4 = {{{tmp_s_fu_813_p4}, {trunc_ln397}}, {tmp_37_reg_1513}};

assign tmp_7_fu_834_p5 = {{{{tmp_s_fu_813_p4}, {trunc_ln397}}, {tmp_37_reg_1513}}, {2'd0}};

assign tmp_8_fu_858_p3 = {{tmp_37_reg_1513}, {7'd0}};

assign tmp_fu_797_p4 = {{empty_149_fu_786_p2[8:7]}};

assign tmp_s_fu_813_p4 = {{select_ln376_1[5:3]}};

assign trunc_ln397_1_fu_884_p1 = add_ln397_fu_878_p2[9:0];

assign trunc_ln397_2_fu_888_p1 = add_ln397_fu_878_p2[7:0];

assign trunc_ln397_3_fu_918_p1 = add_ln397_1_fu_912_p2[8:0];

assign xor_ln385_fu_709_p2 = (icmp_ln387_reg_1496 ^ 1'd1);

assign zext_ln380_1_cast_fu_546_p1 = zext_ln380_1;

assign zext_ln385_fu_865_p1 = tmp_8_fu_858_p3;

assign zext_ln387_1_fu_753_p1 = add_ln387_fu_726_p2;

assign zext_ln387_fu_666_p1 = kh_fu_224;

assign zext_ln389_fu_943_p1 = select_ln387_reg_1527;

assign zext_ln397_1_fu_844_p1 = tmp_7_fu_834_p5;

assign zext_ln397_2_fu_875_p1 = select_ln387_1_reg_1533;

assign zext_ln397_3_fu_908_p1 = select_ln387_2_fu_901_p3;

assign zext_ln397_4_fu_997_p1 = tmp_38_fu_990_p3;

assign zext_ln397_5_fu_1013_p1 = select_ln387_reg_1527_pp0_iter2_reg;

assign zext_ln397_6_fu_1054_p1 = add_ln397_3_reg_1590;

assign zext_ln397_7_fu_1065_p1 = add_ln397_4_reg_1595;

assign zext_ln397_fu_830_p1 = tmp_6_fu_822_p4;

always @ (posedge ap_clk) begin
    zext_ln380_1_cast_reg_1487[4] <= 1'b0;
end

endmodule //full_pose_accel_conv2_receiver_2_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW
