// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module full_pose_accel_apply_head_gelu1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        input_0_address0,
        input_0_ce0,
        input_0_q0,
        input_1_address0,
        input_1_ce0,
        input_1_q0,
        input_2_address0,
        input_2_ce0,
        input_2_q0,
        input_3_address0,
        input_3_ce0,
        input_3_q0,
        output_0_address0,
        output_0_ce0,
        output_0_we0,
        output_0_d0,
        output_1_address0,
        output_1_ce0,
        output_1_we0,
        output_1_d0,
        output_2_address0,
        output_2_ce0,
        output_2_we0,
        output_2_d0,
        output_3_address0,
        output_3_ce0,
        output_3_we0,
        output_3_d0,
        g_lut_head_gelu1_int8_address0,
        g_lut_head_gelu1_int8_ce0,
        g_lut_head_gelu1_int8_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [4:0] input_0_address0;
output   input_0_ce0;
input  [7:0] input_0_q0;
output  [4:0] input_1_address0;
output   input_1_ce0;
input  [7:0] input_1_q0;
output  [4:0] input_2_address0;
output   input_2_ce0;
input  [7:0] input_2_q0;
output  [4:0] input_3_address0;
output   input_3_ce0;
input  [7:0] input_3_q0;
output  [4:0] output_0_address0;
output   output_0_ce0;
output   output_0_we0;
output  [7:0] output_0_d0;
output  [4:0] output_1_address0;
output   output_1_ce0;
output   output_1_we0;
output  [7:0] output_1_d0;
output  [4:0] output_2_address0;
output   output_2_ce0;
output   output_2_we0;
output  [7:0] output_2_d0;
output  [4:0] output_3_address0;
output   output_3_ce0;
output   output_3_we0;
output  [7:0] output_3_d0;
output  [7:0] g_lut_head_gelu1_int8_address0;
output   g_lut_head_gelu1_int8_ce0;
input  [7:0] g_lut_head_gelu1_int8_q0;

reg ap_idle;
reg input_0_ce0;
reg input_1_ce0;
reg input_2_ce0;
reg input_3_ce0;
reg output_0_ce0;
reg output_0_we0;
reg output_1_ce0;
reg output_1_we0;
reg output_2_ce0;
reg output_2_we0;
reg output_3_ce0;
reg output_3_we0;
reg g_lut_head_gelu1_int8_ce0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln568_fu_181_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [1:0] trunc_ln541_fu_215_p1;
reg   [1:0] trunc_ln541_reg_278;
reg   [1:0] trunc_ln541_reg_278_pp0_iter1_reg;
reg   [1:0] trunc_ln541_reg_278_pp0_iter2_reg;
reg   [1:0] trunc_ln541_reg_278_pp0_iter3_reg;
reg   [4:0] output_0_addr_reg_283;
reg   [4:0] output_0_addr_reg_283_pp0_iter1_reg;
reg   [4:0] output_0_addr_reg_283_pp0_iter2_reg;
reg   [4:0] output_0_addr_reg_283_pp0_iter3_reg;
reg   [4:0] output_1_addr_reg_288;
reg   [4:0] output_1_addr_reg_288_pp0_iter1_reg;
reg   [4:0] output_1_addr_reg_288_pp0_iter2_reg;
reg   [4:0] output_1_addr_reg_288_pp0_iter3_reg;
reg   [4:0] output_2_addr_reg_293;
reg   [4:0] output_2_addr_reg_293_pp0_iter1_reg;
reg   [4:0] output_2_addr_reg_293_pp0_iter2_reg;
reg   [4:0] output_2_addr_reg_293_pp0_iter3_reg;
reg   [4:0] output_3_addr_reg_298;
reg   [4:0] output_3_addr_reg_298_pp0_iter1_reg;
reg   [4:0] output_3_addr_reg_298_pp0_iter2_reg;
reg   [4:0] output_3_addr_reg_298_pp0_iter3_reg;
wire   [7:0] tmp_fu_224_p6;
reg   [7:0] tmp_reg_303;
reg   [7:0] g_lut_head_gelu1_int8_load_reg_313;
wire   [63:0] zext_ln541_fu_203_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln570_fu_242_p1;
reg   [7:0] i_fu_56;
wire   [7:0] add_ln568_fu_187_p2;
wire    ap_loop_init;
reg   [7:0] ap_sig_allocacmp_i_11;
wire   [4:0] lshr_ln_fu_193_p4;
wire   [7:0] xor_ln570_fu_237_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_done_reg = 1'b0;
end

full_pose_accel_mux_42_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
mux_42_8_1_1_U711(
    .din0(input_0_q0),
    .din1(input_1_q0),
    .din2(input_2_q0),
    .din3(input_3_q0),
    .din4(trunc_ln541_reg_278),
    .dout(tmp_fu_224_p6)
);

full_pose_accel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln568_fu_181_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_56 <= add_ln568_fu_187_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_56 <= 8'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        output_0_addr_reg_283_pp0_iter1_reg <= output_0_addr_reg_283;
        output_1_addr_reg_288_pp0_iter1_reg <= output_1_addr_reg_288;
        output_2_addr_reg_293_pp0_iter1_reg <= output_2_addr_reg_293;
        output_3_addr_reg_298_pp0_iter1_reg <= output_3_addr_reg_298;
        tmp_reg_303 <= tmp_fu_224_p6;
        trunc_ln541_reg_278_pp0_iter1_reg <= trunc_ln541_reg_278;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        g_lut_head_gelu1_int8_load_reg_313 <= g_lut_head_gelu1_int8_q0;
        output_0_addr_reg_283_pp0_iter2_reg <= output_0_addr_reg_283_pp0_iter1_reg;
        output_0_addr_reg_283_pp0_iter3_reg <= output_0_addr_reg_283_pp0_iter2_reg;
        output_1_addr_reg_288_pp0_iter2_reg <= output_1_addr_reg_288_pp0_iter1_reg;
        output_1_addr_reg_288_pp0_iter3_reg <= output_1_addr_reg_288_pp0_iter2_reg;
        output_2_addr_reg_293_pp0_iter2_reg <= output_2_addr_reg_293_pp0_iter1_reg;
        output_2_addr_reg_293_pp0_iter3_reg <= output_2_addr_reg_293_pp0_iter2_reg;
        output_3_addr_reg_298_pp0_iter2_reg <= output_3_addr_reg_298_pp0_iter1_reg;
        output_3_addr_reg_298_pp0_iter3_reg <= output_3_addr_reg_298_pp0_iter2_reg;
        trunc_ln541_reg_278_pp0_iter2_reg <= trunc_ln541_reg_278_pp0_iter1_reg;
        trunc_ln541_reg_278_pp0_iter3_reg <= trunc_ln541_reg_278_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln568_fu_181_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        output_0_addr_reg_283 <= zext_ln541_fu_203_p1;
        output_1_addr_reg_288 <= zext_ln541_fu_203_p1;
        output_2_addr_reg_293 <= zext_ln541_fu_203_p1;
        output_3_addr_reg_298 <= zext_ln541_fu_203_p1;
        trunc_ln541_reg_278 <= trunc_ln541_fu_215_p1;
    end
end

always @ (*) begin
    if (((icmp_ln568_fu_181_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_11 = 8'd0;
    end else begin
        ap_sig_allocacmp_i_11 = i_fu_56;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        g_lut_head_gelu1_int8_ce0 = 1'b1;
    end else begin
        g_lut_head_gelu1_int8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_0_ce0 = 1'b1;
    end else begin
        input_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_1_ce0 = 1'b1;
    end else begin
        input_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_2_ce0 = 1'b1;
    end else begin
        input_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_3_ce0 = 1'b1;
    end else begin
        input_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        output_0_ce0 = 1'b1;
    end else begin
        output_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (trunc_ln541_reg_278_pp0_iter3_reg == 2'd0))) begin
        output_0_we0 = 1'b1;
    end else begin
        output_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        output_1_ce0 = 1'b1;
    end else begin
        output_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (trunc_ln541_reg_278_pp0_iter3_reg == 2'd1))) begin
        output_1_we0 = 1'b1;
    end else begin
        output_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        output_2_ce0 = 1'b1;
    end else begin
        output_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (trunc_ln541_reg_278_pp0_iter3_reg == 2'd2))) begin
        output_2_we0 = 1'b1;
    end else begin
        output_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        output_3_ce0 = 1'b1;
    end else begin
        output_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (trunc_ln541_reg_278_pp0_iter3_reg == 2'd3))) begin
        output_3_we0 = 1'b1;
    end else begin
        output_3_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln568_fu_187_p2 = (ap_sig_allocacmp_i_11 + 8'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign g_lut_head_gelu1_int8_address0 = zext_ln570_fu_242_p1;

assign icmp_ln568_fu_181_p2 = ((ap_sig_allocacmp_i_11 == 8'd128) ? 1'b1 : 1'b0);

assign input_0_address0 = zext_ln541_fu_203_p1;

assign input_1_address0 = zext_ln541_fu_203_p1;

assign input_2_address0 = zext_ln541_fu_203_p1;

assign input_3_address0 = zext_ln541_fu_203_p1;

assign lshr_ln_fu_193_p4 = {{ap_sig_allocacmp_i_11[6:2]}};

assign output_0_address0 = output_0_addr_reg_283_pp0_iter3_reg;

assign output_0_d0 = g_lut_head_gelu1_int8_load_reg_313;

assign output_1_address0 = output_1_addr_reg_288_pp0_iter3_reg;

assign output_1_d0 = g_lut_head_gelu1_int8_load_reg_313;

assign output_2_address0 = output_2_addr_reg_293_pp0_iter3_reg;

assign output_2_d0 = g_lut_head_gelu1_int8_load_reg_313;

assign output_3_address0 = output_3_addr_reg_298_pp0_iter3_reg;

assign output_3_d0 = g_lut_head_gelu1_int8_load_reg_313;

assign trunc_ln541_fu_215_p1 = ap_sig_allocacmp_i_11[1:0];

assign xor_ln570_fu_237_p2 = (tmp_reg_303 ^ 8'd128);

assign zext_ln541_fu_203_p1 = lshr_ln_fu_193_p4;

assign zext_ln570_fu_242_p1 = xor_ln570_fu_237_p2;

endmodule //full_pose_accel_apply_head_gelu1
