-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity full_pose_accel_fc2_requant is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    input_0_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    input_0_ce0 : OUT STD_LOGIC;
    input_0_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    input_1_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    input_1_ce0 : OUT STD_LOGIC;
    input_1_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    input_2_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    input_2_ce0 : OUT STD_LOGIC;
    input_2_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    input_3_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    input_3_ce0 : OUT STD_LOGIC;
    input_3_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    output_0_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    output_0_ce0 : OUT STD_LOGIC;
    output_0_we0 : OUT STD_LOGIC;
    output_0_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    output_1_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    output_1_ce0 : OUT STD_LOGIC;
    output_1_we0 : OUT STD_LOGIC;
    output_1_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    output_2_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    output_2_ce0 : OUT STD_LOGIC;
    output_2_we0 : OUT STD_LOGIC;
    output_2_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    output_3_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    output_3_ce0 : OUT STD_LOGIC;
    output_3_we0 : OUT STD_LOGIC;
    output_3_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_ZL17g_fc2_weight_int8_0_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    p_ZL17g_fc2_weight_int8_0_ce0 : OUT STD_LOGIC;
    p_ZL17g_fc2_weight_int8_0_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_ZL17g_fc2_weight_int8_1_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    p_ZL17g_fc2_weight_int8_1_ce0 : OUT STD_LOGIC;
    p_ZL17g_fc2_weight_int8_1_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    g_fc2_bias_int32_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    g_fc2_bias_int32_ce0 : OUT STD_LOGIC;
    g_fc2_bias_int32_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    g_fc2_requant_mult_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    g_fc2_requant_mult_ce0 : OUT STD_LOGIC;
    g_fc2_requant_mult_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    g_fc2_requant_shift_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    g_fc2_requant_shift_ce0 : OUT STD_LOGIC;
    g_fc2_requant_shift_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1277_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1277_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1277_p_dout0 : IN STD_LOGIC_VECTOR (63 downto 0);
    grp_fu_1277_p_ce : OUT STD_LOGIC );
end;


architecture behav of full_pose_accel_fc2_requant is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (12 downto 0) := "0000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (12 downto 0) := "0000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (12 downto 0) := "0000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (12 downto 0) := "0000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (12 downto 0) := "0000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (12 downto 0) := "0000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (12 downto 0) := "0001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (12 downto 0) := "0010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (12 downto 0) := "0100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (12 downto 0) := "1000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv64_1 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv8_80 : STD_LOGIC_VECTOR (7 downto 0) := "10000000";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv31_7FFFFFFF : STD_LOGIC_VECTOR (30 downto 0) := "1111111111111111111111111111111";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv57_0 : STD_LOGIC_VECTOR (56 downto 0) := "000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv64_FFFFFFFFFFFFFF81 : STD_LOGIC_VECTOR (63 downto 0) := "1111111111111111111111111111111111111111111111111111111110000001";
    constant ap_const_lv8_7F : STD_LOGIC_VECTOR (7 downto 0) := "01111111";
    constant ap_const_lv8_81 : STD_LOGIC_VECTOR (7 downto 0) := "10000001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (12 downto 0) := "0000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal trunc_ln305_fu_223_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln305_reg_462 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal add_ln305_fu_234_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln305_reg_470 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln305_fu_240_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln305_reg_475 : STD_LOGIC_VECTOR (63 downto 0);
    signal icmp_ln305_fu_228_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln312_fu_245_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln312_reg_481 : STD_LOGIC_VECTOR (0 downto 0);
    signal lshr_ln2_reg_491 : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln316_fu_260_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln316_reg_496 : STD_LOGIC_VECTOR (1 downto 0);
    signal g_fc2_bias_int32_load_reg_500 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal acc_V_fu_288_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_V_reg_515 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal g_fc2_requant_mult_load_reg_520 : STD_LOGIC_VECTOR (31 downto 0);
    signal g_fc2_requant_shift_load_reg_525 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_fu_293_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal empty_reg_532 : STD_LOGIC_VECTOR (30 downto 0);
    signal sext_ln541_fu_297_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln85_fu_300_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln53_fu_309_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal add_ln53_reg_547 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal product_reg_552 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal offset_fu_317_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal offset_reg_560 : STD_LOGIC_VECTOR (63 downto 0);
    signal icmp_ln50_fu_323_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln50_reg_566 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal sub_ln51_fu_328_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln51_reg_572 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln57_fu_333_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal sub_ln57_reg_577 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln55_fu_345_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln55_reg_582 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal add_ln55_fu_348_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln55_reg_587 : STD_LOGIC_VECTOR (63 downto 0);
    signal select_ln50_fu_357_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal select_ln50_reg_592 : STD_LOGIC_VECTOR (63 downto 0);
    signal select_ln54_fu_380_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal select_ln54_reg_597 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal tmp_5_reg_603 : STD_LOGIC_VECTOR (56 downto 0);
    signal select_ln39_fu_424_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln39_reg_608 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state12 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state12 : signal is "none";
    signal grp_fc2_requant_Pipeline_LINEAR_REQUANT_IN_fu_195_ap_start : STD_LOGIC;
    signal grp_fc2_requant_Pipeline_LINEAR_REQUANT_IN_fu_195_ap_done : STD_LOGIC;
    signal grp_fc2_requant_Pipeline_LINEAR_REQUANT_IN_fu_195_ap_idle : STD_LOGIC;
    signal grp_fc2_requant_Pipeline_LINEAR_REQUANT_IN_fu_195_ap_ready : STD_LOGIC;
    signal grp_fc2_requant_Pipeline_LINEAR_REQUANT_IN_fu_195_input_0_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_fc2_requant_Pipeline_LINEAR_REQUANT_IN_fu_195_input_0_ce0 : STD_LOGIC;
    signal grp_fc2_requant_Pipeline_LINEAR_REQUANT_IN_fu_195_input_2_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_fc2_requant_Pipeline_LINEAR_REQUANT_IN_fu_195_input_2_ce0 : STD_LOGIC;
    signal grp_fc2_requant_Pipeline_LINEAR_REQUANT_IN_fu_195_input_1_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_fc2_requant_Pipeline_LINEAR_REQUANT_IN_fu_195_input_1_ce0 : STD_LOGIC;
    signal grp_fc2_requant_Pipeline_LINEAR_REQUANT_IN_fu_195_input_3_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_fc2_requant_Pipeline_LINEAR_REQUANT_IN_fu_195_input_3_ce0 : STD_LOGIC;
    signal grp_fc2_requant_Pipeline_LINEAR_REQUANT_IN_fu_195_acc1_V_out : STD_LOGIC_VECTOR (21 downto 0);
    signal grp_fc2_requant_Pipeline_LINEAR_REQUANT_IN_fu_195_acc1_V_out_ap_vld : STD_LOGIC;
    signal grp_fc2_requant_Pipeline_LINEAR_REQUANT_IN_fu_195_acc0_V_out : STD_LOGIC_VECTOR (21 downto 0);
    signal grp_fc2_requant_Pipeline_LINEAR_REQUANT_IN_fu_195_acc0_V_out_ap_vld : STD_LOGIC;
    signal grp_fc2_requant_Pipeline_LINEAR_REQUANT_IN_fu_195_p_ZL17g_fc2_weight_int8_0_address0 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_fc2_requant_Pipeline_LINEAR_REQUANT_IN_fu_195_p_ZL17g_fc2_weight_int8_0_ce0 : STD_LOGIC;
    signal grp_fc2_requant_Pipeline_LINEAR_REQUANT_IN_fu_195_p_ZL17g_fc2_weight_int8_1_address0 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_fc2_requant_Pipeline_LINEAR_REQUANT_IN_fu_195_p_ZL17g_fc2_weight_int8_1_ce0 : STD_LOGIC;
    signal grp_fc2_requant_Pipeline_LINEAR_REQUANT_IN_fu_195_ap_start_reg : STD_LOGIC := '0';
    signal zext_ln316_fu_432_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state13 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state13 : signal is "none";
    signal o_fu_92 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln310_2_fu_274_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal sext_ln310_fu_270_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal add_ln315_fu_278_p2 : STD_LOGIC_VECTOR (22 downto 0);
    signal sext_ln315_fu_284_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln53_fu_314_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln51_fu_337_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal shl_ln51_fu_340_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal ashr_ln57_fu_352_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_fu_364_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln54_fu_375_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ashr_ln55_fu_371_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal icmp_ln39_fu_397_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln42_fu_402_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln39_fu_418_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln39_2_fu_410_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln218_fu_407_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal ap_ST_fsm_state12_blk : STD_LOGIC;
    signal ap_ST_fsm_state13_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component full_pose_accel_fc2_requant_Pipeline_LINEAR_REQUANT_IN IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        input_0_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        input_0_ce0 : OUT STD_LOGIC;
        input_0_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        input_2_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        input_2_ce0 : OUT STD_LOGIC;
        input_2_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        o : IN STD_LOGIC_VECTOR (6 downto 0);
        trunc_ln312 : IN STD_LOGIC_VECTOR (0 downto 0);
        input_1_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        input_1_ce0 : OUT STD_LOGIC;
        input_1_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        input_3_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        input_3_ce0 : OUT STD_LOGIC;
        input_3_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        acc1_V_out : OUT STD_LOGIC_VECTOR (21 downto 0);
        acc1_V_out_ap_vld : OUT STD_LOGIC;
        acc0_V_out : OUT STD_LOGIC_VECTOR (21 downto 0);
        acc0_V_out_ap_vld : OUT STD_LOGIC;
        p_ZL17g_fc2_weight_int8_0_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
        p_ZL17g_fc2_weight_int8_0_ce0 : OUT STD_LOGIC;
        p_ZL17g_fc2_weight_int8_0_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_ZL17g_fc2_weight_int8_1_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
        p_ZL17g_fc2_weight_int8_1_ce0 : OUT STD_LOGIC;
        p_ZL17g_fc2_weight_int8_1_q0 : IN STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component full_pose_accel_mul_32s_32s_64_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;



begin
    grp_fc2_requant_Pipeline_LINEAR_REQUANT_IN_fu_195 : component full_pose_accel_fc2_requant_Pipeline_LINEAR_REQUANT_IN
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_fc2_requant_Pipeline_LINEAR_REQUANT_IN_fu_195_ap_start,
        ap_done => grp_fc2_requant_Pipeline_LINEAR_REQUANT_IN_fu_195_ap_done,
        ap_idle => grp_fc2_requant_Pipeline_LINEAR_REQUANT_IN_fu_195_ap_idle,
        ap_ready => grp_fc2_requant_Pipeline_LINEAR_REQUANT_IN_fu_195_ap_ready,
        input_0_address0 => grp_fc2_requant_Pipeline_LINEAR_REQUANT_IN_fu_195_input_0_address0,
        input_0_ce0 => grp_fc2_requant_Pipeline_LINEAR_REQUANT_IN_fu_195_input_0_ce0,
        input_0_q0 => input_0_q0,
        input_2_address0 => grp_fc2_requant_Pipeline_LINEAR_REQUANT_IN_fu_195_input_2_address0,
        input_2_ce0 => grp_fc2_requant_Pipeline_LINEAR_REQUANT_IN_fu_195_input_2_ce0,
        input_2_q0 => input_2_q0,
        o => trunc_ln305_reg_462,
        trunc_ln312 => trunc_ln312_reg_481,
        input_1_address0 => grp_fc2_requant_Pipeline_LINEAR_REQUANT_IN_fu_195_input_1_address0,
        input_1_ce0 => grp_fc2_requant_Pipeline_LINEAR_REQUANT_IN_fu_195_input_1_ce0,
        input_1_q0 => input_1_q0,
        input_3_address0 => grp_fc2_requant_Pipeline_LINEAR_REQUANT_IN_fu_195_input_3_address0,
        input_3_ce0 => grp_fc2_requant_Pipeline_LINEAR_REQUANT_IN_fu_195_input_3_ce0,
        input_3_q0 => input_3_q0,
        acc1_V_out => grp_fc2_requant_Pipeline_LINEAR_REQUANT_IN_fu_195_acc1_V_out,
        acc1_V_out_ap_vld => grp_fc2_requant_Pipeline_LINEAR_REQUANT_IN_fu_195_acc1_V_out_ap_vld,
        acc0_V_out => grp_fc2_requant_Pipeline_LINEAR_REQUANT_IN_fu_195_acc0_V_out,
        acc0_V_out_ap_vld => grp_fc2_requant_Pipeline_LINEAR_REQUANT_IN_fu_195_acc0_V_out_ap_vld,
        p_ZL17g_fc2_weight_int8_0_address0 => grp_fc2_requant_Pipeline_LINEAR_REQUANT_IN_fu_195_p_ZL17g_fc2_weight_int8_0_address0,
        p_ZL17g_fc2_weight_int8_0_ce0 => grp_fc2_requant_Pipeline_LINEAR_REQUANT_IN_fu_195_p_ZL17g_fc2_weight_int8_0_ce0,
        p_ZL17g_fc2_weight_int8_0_q0 => p_ZL17g_fc2_weight_int8_0_q0,
        p_ZL17g_fc2_weight_int8_1_address0 => grp_fc2_requant_Pipeline_LINEAR_REQUANT_IN_fu_195_p_ZL17g_fc2_weight_int8_1_address0,
        p_ZL17g_fc2_weight_int8_1_ce0 => grp_fc2_requant_Pipeline_LINEAR_REQUANT_IN_fu_195_p_ZL17g_fc2_weight_int8_1_ce0,
        p_ZL17g_fc2_weight_int8_1_q0 => p_ZL17g_fc2_weight_int8_1_q0);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_fc2_requant_Pipeline_LINEAR_REQUANT_IN_fu_195_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_fc2_requant_Pipeline_LINEAR_REQUANT_IN_fu_195_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln305_fu_228_p2 = ap_const_lv1_0))) then 
                    grp_fc2_requant_Pipeline_LINEAR_REQUANT_IN_fu_195_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_fc2_requant_Pipeline_LINEAR_REQUANT_IN_fu_195_ap_ready = ap_const_logic_1)) then 
                    grp_fc2_requant_Pipeline_LINEAR_REQUANT_IN_fu_195_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    o_fu_92_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                o_fu_92 <= ap_const_lv8_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
                o_fu_92 <= add_ln305_reg_470;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                acc_V_reg_515 <= acc_V_fu_288_p2;
                empty_reg_532 <= empty_fu_293_p1;
                g_fc2_requant_mult_load_reg_520 <= g_fc2_requant_mult_q0;
                g_fc2_requant_shift_load_reg_525 <= g_fc2_requant_shift_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                add_ln305_reg_470 <= add_ln305_fu_234_p2;
                trunc_ln305_reg_462 <= trunc_ln305_fu_223_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state7)) then
                add_ln53_reg_547 <= add_ln53_fu_309_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state10)) then
                add_ln55_reg_587 <= add_ln55_fu_348_p2;
                select_ln50_reg_592 <= select_ln50_fu_357_p3;
                    zext_ln55_reg_582(31 downto 0) <= zext_ln55_fu_345_p1(31 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                g_fc2_bias_int32_load_reg_500 <= g_fc2_bias_int32_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state9)) then
                icmp_ln50_reg_566 <= icmp_ln50_fu_323_p2;
                sub_ln51_reg_572 <= sub_ln51_fu_328_p2;
                sub_ln57_reg_577 <= sub_ln57_fu_333_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln305_fu_228_p2 = ap_const_lv1_0))) then
                lshr_ln2_reg_491 <= o_fu_92(6 downto 2);
                trunc_ln312_reg_481 <= trunc_ln312_fu_245_p1;
                trunc_ln316_reg_496 <= trunc_ln316_fu_260_p1;
                    zext_ln305_reg_475(7 downto 0) <= zext_ln305_fu_240_p1(7 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state8)) then
                offset_reg_560 <= offset_fu_317_p2;
                product_reg_552 <= grp_fu_1277_p_dout0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state12)) then
                select_ln39_reg_608 <= select_ln39_fu_424_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state11)) then
                select_ln54_reg_597 <= select_ln54_fu_380_p3;
                tmp_5_reg_603 <= select_ln54_fu_380_p3(63 downto 7);
            end if;
        end if;
    end process;
    zext_ln305_reg_475(63 downto 8) <= "00000000000000000000000000000000000000000000000000000000";
    zext_ln55_reg_582(63 downto 32) <= "00000000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, icmp_ln305_fu_228_p2, ap_CS_fsm_state3, grp_fc2_requant_Pipeline_LINEAR_REQUANT_IN_fu_195_ap_done)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln305_fu_228_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                if (((grp_fc2_requant_Pipeline_LINEAR_REQUANT_IN_fu_195_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state12;
            when ap_ST_fsm_state12 => 
                ap_NS_fsm <= ap_ST_fsm_state13;
            when ap_ST_fsm_state13 => 
                ap_NS_fsm <= ap_ST_fsm_state2;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXX";
        end case;
    end process;
    acc_V_fu_288_p2 <= std_logic_vector(unsigned(g_fc2_bias_int32_load_reg_500) + unsigned(sext_ln315_fu_284_p1));
    add_ln305_fu_234_p2 <= std_logic_vector(unsigned(o_fu_92) + unsigned(ap_const_lv8_1));
    add_ln315_fu_278_p2 <= std_logic_vector(signed(sext_ln310_2_fu_274_p1) + signed(sext_ln310_fu_270_p1));
    add_ln53_fu_309_p2 <= std_logic_vector(unsigned(empty_reg_532) + unsigned(ap_const_lv31_7FFFFFFF));
    add_ln55_fu_348_p2 <= std_logic_vector(unsigned(offset_reg_560) + unsigned(product_reg_552));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state12 <= ap_CS_fsm(11);
    ap_CS_fsm_state13 <= ap_CS_fsm(12);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);
    ap_ST_fsm_state10_blk <= ap_const_logic_0;
    ap_ST_fsm_state11_blk <= ap_const_logic_0;
    ap_ST_fsm_state12_blk <= ap_const_logic_0;
    ap_ST_fsm_state13_blk <= ap_const_logic_0;

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(grp_fc2_requant_Pipeline_LINEAR_REQUANT_IN_fu_195_ap_done)
    begin
        if ((grp_fc2_requant_Pipeline_LINEAR_REQUANT_IN_fu_195_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;
    ap_ST_fsm_state8_blk <= ap_const_logic_0;
    ap_ST_fsm_state9_blk <= ap_const_logic_0;

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state2, icmp_ln305_fu_228_p2)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln305_fu_228_p2 = ap_const_lv1_1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2, icmp_ln305_fu_228_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln305_fu_228_p2 = ap_const_lv1_1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    ashr_ln55_fu_371_p2 <= std_logic_vector(shift_right(signed(add_ln55_reg_587),to_integer(unsigned('0' & zext_ln55_reg_582(31-1 downto 0)))));
    ashr_ln57_fu_352_p2 <= std_logic_vector(shift_right(signed(sub_ln57_reg_577),to_integer(unsigned('0' & zext_ln55_fu_345_p1(31-1 downto 0)))));
    empty_fu_293_p1 <= g_fc2_requant_shift_q0(31 - 1 downto 0);
    g_fc2_bias_int32_address0 <= zext_ln305_fu_240_p1(7 - 1 downto 0);

    g_fc2_bias_int32_ce0_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            g_fc2_bias_int32_ce0 <= ap_const_logic_1;
        else 
            g_fc2_bias_int32_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    g_fc2_requant_mult_address0 <= zext_ln305_reg_475(7 - 1 downto 0);

    g_fc2_requant_mult_ce0_assign_proc : process(ap_CS_fsm_state3, grp_fc2_requant_Pipeline_LINEAR_REQUANT_IN_fu_195_ap_done)
    begin
        if (((grp_fc2_requant_Pipeline_LINEAR_REQUANT_IN_fu_195_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            g_fc2_requant_mult_ce0 <= ap_const_logic_1;
        else 
            g_fc2_requant_mult_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    g_fc2_requant_shift_address0 <= zext_ln305_reg_475(7 - 1 downto 0);

    g_fc2_requant_shift_ce0_assign_proc : process(ap_CS_fsm_state3, grp_fc2_requant_Pipeline_LINEAR_REQUANT_IN_fu_195_ap_done)
    begin
        if (((grp_fc2_requant_Pipeline_LINEAR_REQUANT_IN_fu_195_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            g_fc2_requant_shift_ce0 <= ap_const_logic_1;
        else 
            g_fc2_requant_shift_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    grp_fc2_requant_Pipeline_LINEAR_REQUANT_IN_fu_195_ap_start <= grp_fc2_requant_Pipeline_LINEAR_REQUANT_IN_fu_195_ap_start_reg;
    grp_fu_1277_p_ce <= ap_const_logic_1;
    grp_fu_1277_p_din0 <= sext_ln85_fu_300_p1(32 - 1 downto 0);
    grp_fu_1277_p_din1 <= sext_ln541_fu_297_p1(32 - 1 downto 0);
    icmp_ln305_fu_228_p2 <= "1" when (o_fu_92 = ap_const_lv8_80) else "0";
    icmp_ln39_fu_397_p2 <= "1" when (signed(tmp_5_reg_603) > signed(ap_const_lv57_0)) else "0";
    icmp_ln42_fu_402_p2 <= "1" when (signed(select_ln54_reg_597) < signed(ap_const_lv64_FFFFFFFFFFFFFF81)) else "0";
    icmp_ln50_fu_323_p2 <= "1" when (signed(g_fc2_requant_shift_load_reg_525) < signed(ap_const_lv32_1)) else "0";
    input_0_address0 <= grp_fc2_requant_Pipeline_LINEAR_REQUANT_IN_fu_195_input_0_address0;
    input_0_ce0 <= grp_fc2_requant_Pipeline_LINEAR_REQUANT_IN_fu_195_input_0_ce0;
    input_1_address0 <= grp_fc2_requant_Pipeline_LINEAR_REQUANT_IN_fu_195_input_1_address0;
    input_1_ce0 <= grp_fc2_requant_Pipeline_LINEAR_REQUANT_IN_fu_195_input_1_ce0;
    input_2_address0 <= grp_fc2_requant_Pipeline_LINEAR_REQUANT_IN_fu_195_input_2_address0;
    input_2_ce0 <= grp_fc2_requant_Pipeline_LINEAR_REQUANT_IN_fu_195_input_2_ce0;
    input_3_address0 <= grp_fc2_requant_Pipeline_LINEAR_REQUANT_IN_fu_195_input_3_address0;
    input_3_ce0 <= grp_fc2_requant_Pipeline_LINEAR_REQUANT_IN_fu_195_input_3_ce0;
    offset_fu_317_p2 <= std_logic_vector(shift_left(unsigned(ap_const_lv64_1),to_integer(unsigned('0' & zext_ln53_fu_314_p1(31-1 downto 0)))));
    or_ln39_fu_418_p2 <= (icmp_ln42_fu_402_p2 or icmp_ln39_fu_397_p2);
    or_ln54_fu_375_p2 <= (tmp_fu_364_p3 or icmp_ln50_reg_566);
    output_0_address0 <= zext_ln316_fu_432_p1(5 - 1 downto 0);

    output_0_ce0_assign_proc : process(ap_CS_fsm_state13)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            output_0_ce0 <= ap_const_logic_1;
        else 
            output_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    output_0_d0 <= select_ln39_reg_608;

    output_0_we0_assign_proc : process(trunc_ln316_reg_496, ap_CS_fsm_state13)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state13) and (trunc_ln316_reg_496 = ap_const_lv2_0))) then 
            output_0_we0 <= ap_const_logic_1;
        else 
            output_0_we0 <= ap_const_logic_0;
        end if; 
    end process;

    output_1_address0 <= zext_ln316_fu_432_p1(5 - 1 downto 0);

    output_1_ce0_assign_proc : process(ap_CS_fsm_state13)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            output_1_ce0 <= ap_const_logic_1;
        else 
            output_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    output_1_d0 <= select_ln39_reg_608;

    output_1_we0_assign_proc : process(trunc_ln316_reg_496, ap_CS_fsm_state13)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state13) and (trunc_ln316_reg_496 = ap_const_lv2_1))) then 
            output_1_we0 <= ap_const_logic_1;
        else 
            output_1_we0 <= ap_const_logic_0;
        end if; 
    end process;

    output_2_address0 <= zext_ln316_fu_432_p1(5 - 1 downto 0);

    output_2_ce0_assign_proc : process(ap_CS_fsm_state13)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            output_2_ce0 <= ap_const_logic_1;
        else 
            output_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    output_2_d0 <= select_ln39_reg_608;

    output_2_we0_assign_proc : process(trunc_ln316_reg_496, ap_CS_fsm_state13)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state13) and (trunc_ln316_reg_496 = ap_const_lv2_2))) then 
            output_2_we0 <= ap_const_logic_1;
        else 
            output_2_we0 <= ap_const_logic_0;
        end if; 
    end process;

    output_3_address0 <= zext_ln316_fu_432_p1(5 - 1 downto 0);

    output_3_ce0_assign_proc : process(ap_CS_fsm_state13)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            output_3_ce0 <= ap_const_logic_1;
        else 
            output_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    output_3_d0 <= select_ln39_reg_608;

    output_3_we0_assign_proc : process(trunc_ln316_reg_496, ap_CS_fsm_state13)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state13) and (trunc_ln316_reg_496 = ap_const_lv2_3))) then 
            output_3_we0 <= ap_const_logic_1;
        else 
            output_3_we0 <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL17g_fc2_weight_int8_0_address0 <= grp_fc2_requant_Pipeline_LINEAR_REQUANT_IN_fu_195_p_ZL17g_fc2_weight_int8_0_address0;
    p_ZL17g_fc2_weight_int8_0_ce0 <= grp_fc2_requant_Pipeline_LINEAR_REQUANT_IN_fu_195_p_ZL17g_fc2_weight_int8_0_ce0;
    p_ZL17g_fc2_weight_int8_1_address0 <= grp_fc2_requant_Pipeline_LINEAR_REQUANT_IN_fu_195_p_ZL17g_fc2_weight_int8_1_address0;
    p_ZL17g_fc2_weight_int8_1_ce0 <= grp_fc2_requant_Pipeline_LINEAR_REQUANT_IN_fu_195_p_ZL17g_fc2_weight_int8_1_ce0;
    select_ln39_2_fu_410_p3 <= 
        ap_const_lv8_7F when (icmp_ln39_fu_397_p2(0) = '1') else 
        ap_const_lv8_81;
    select_ln39_fu_424_p3 <= 
        select_ln39_2_fu_410_p3 when (or_ln39_fu_418_p2(0) = '1') else 
        trunc_ln218_fu_407_p1;
    select_ln50_fu_357_p3 <= 
        shl_ln51_fu_340_p2 when (icmp_ln50_reg_566(0) = '1') else 
        ashr_ln57_fu_352_p2;
    select_ln54_fu_380_p3 <= 
        select_ln50_reg_592 when (or_ln54_fu_375_p2(0) = '1') else 
        ashr_ln55_fu_371_p2;
        sext_ln310_2_fu_274_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(grp_fc2_requant_Pipeline_LINEAR_REQUANT_IN_fu_195_acc1_V_out),23));

        sext_ln310_fu_270_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(grp_fc2_requant_Pipeline_LINEAR_REQUANT_IN_fu_195_acc0_V_out),23));

        sext_ln315_fu_284_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln315_fu_278_p2),32));

        sext_ln541_fu_297_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(acc_V_reg_515),64));

        sext_ln85_fu_300_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(g_fc2_requant_mult_load_reg_520),64));

    shl_ln51_fu_340_p2 <= std_logic_vector(shift_left(unsigned(product_reg_552),to_integer(unsigned('0' & zext_ln51_fu_337_p1(31-1 downto 0)))));
    sub_ln51_fu_328_p2 <= std_logic_vector(unsigned(ap_const_lv32_0) - unsigned(g_fc2_requant_shift_load_reg_525));
    sub_ln57_fu_333_p2 <= std_logic_vector(unsigned(product_reg_552) - unsigned(offset_reg_560));
    tmp_fu_364_p3 <= product_reg_552(63 downto 63);
    trunc_ln218_fu_407_p1 <= select_ln54_reg_597(8 - 1 downto 0);
    trunc_ln305_fu_223_p1 <= o_fu_92(7 - 1 downto 0);
    trunc_ln312_fu_245_p1 <= o_fu_92(1 - 1 downto 0);
    trunc_ln316_fu_260_p1 <= o_fu_92(2 - 1 downto 0);
    zext_ln305_fu_240_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(o_fu_92),64));
    zext_ln316_fu_432_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln2_reg_491),64));
    zext_ln51_fu_337_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sub_ln51_reg_572),64));
    zext_ln53_fu_314_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln53_reg_547),64));
    zext_ln55_fu_345_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(g_fc2_requant_shift_load_reg_525),64));
end behav;
