-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity full_pose_accel_encode_receiver_path_2_Pipeline_CONV1_CH_CONV1_KH_CONV1_KW is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    p_ZL18g_conv1_bias_int32_2_load : IN STD_LOGIC_VECTOR (31 downto 0);
    select_ln327_2 : IN STD_LOGIC_VECTOR (7 downto 0);
    sub_ln343 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_cast10_mid123 : IN STD_LOGIC_VECTOR (7 downto 0);
    notlhs_mid137 : IN STD_LOGIC_VECTOR (0 downto 0);
    zext_ln329_1 : IN STD_LOGIC_VECTOR (3 downto 0);
    input_r_address0 : OUT STD_LOGIC_VECTOR (13 downto 0);
    input_r_ce0 : OUT STD_LOGIC;
    input_r_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    acc_V_1_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    acc_V_1_out_ap_vld : OUT STD_LOGIC;
    p_ZL19g_conv1_weight_int8_2_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    p_ZL19g_conv1_weight_int8_2_ce0 : OUT STD_LOGIC;
    p_ZL19g_conv1_weight_int8_2_q0 : IN STD_LOGIC_VECTOR (7 downto 0) );
end;


architecture behav of full_pose_accel_encode_receiver_path_2_Pipeline_CONV1_CH_CONV1_KH_CONV1_KW is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv6_2D : STD_LOGIC_VECTOR (5 downto 0) := "101101";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv5_F : STD_LOGIC_VECTOR (4 downto 0) := "01111";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv11_100 : STD_LOGIC_VECTOR (10 downto 0) := "00100000000";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv3_7 : STD_LOGIC_VECTOR (2 downto 0) := "111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv5_A : STD_LOGIC_VECTOR (4 downto 0) := "01010";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter6 : BOOLEAN;
    signal ap_block_state8_pp0_stage0_iter7 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln333_fu_265_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal zext_ln329_1_cast_fu_213_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln329_1_cast_reg_844 : STD_LOGIC_VECTOR (4 downto 0);
    signal p_cast10_mid123_cast_fu_217_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal p_cast10_mid123_cast_reg_849 : STD_LOGIC_VECTOR (11 downto 0);
    signal select_ln327_2_cast_fu_221_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln327_2_cast_reg_854 : STD_LOGIC_VECTOR (8 downto 0);
    signal sub_ln343_cast_fu_225_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal sub_ln343_cast_reg_860 : STD_LOGIC_VECTOR (8 downto 0);
    signal ch_2_reg_865 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln333_reg_871 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln333_reg_871_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln333_reg_871_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln333_reg_871_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln333_reg_871_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln333_reg_871_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln333_fu_280_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln333_reg_875 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln335_fu_286_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln335_reg_881 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln335_reg_881_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln335_reg_881_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln333_1_fu_292_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln333_1_reg_892 : STD_LOGIC_VECTOR (1 downto 0);
    signal kh_3_reg_897 : STD_LOGIC_VECTOR (2 downto 0);
    signal p_cast9_fu_356_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal p_cast9_reg_902 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln343_2_fu_375_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln343_2_reg_908 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_cast9_mid1_fu_404_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal p_cast9_mid1_reg_914 : STD_LOGIC_VECTOR (10 downto 0);
    signal and_ln333_fu_421_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln333_reg_920 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln333_reg_920_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln335_fu_427_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln335_reg_927 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln335_fu_438_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln335_reg_932 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln335_reg_932_pp0_iter2_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln335_1_fu_446_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln335_1_reg_937 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln340_fu_458_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln340_reg_942 : STD_LOGIC_VECTOR (2 downto 0);
    signal icmp_fu_525_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_reg_947 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln343_fu_590_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln343_reg_952 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln343_1_fu_594_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln343_1_reg_957 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln335_2_fu_616_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal select_ln335_2_reg_962 : STD_LOGIC_VECTOR (11 downto 0);
    signal trunc_ln335_fu_623_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln335_reg_967 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp35_fu_658_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp35_reg_972 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln340_1_fu_667_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln340_1_reg_977 : STD_LOGIC_VECTOR (4 downto 0);
    signal and_ln341_1_fu_678_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln341_1_reg_982 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln343_5_fu_727_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln343_5_reg_987 : STD_LOGIC_VECTOR (9 downto 0);
    signal and_ln341_fu_736_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln341_reg_992 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln341_reg_992_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln341_reg_992_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln341_reg_992_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln343_fu_747_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal add_ln343_reg_997 : STD_LOGIC_VECTOR (13 downto 0);
    signal ap_condition_exit_pp0_iter2_stage0 : STD_LOGIC;
    signal zext_ln343_4_fu_753_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln343_fu_757_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal acc_V_1_fu_120 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_V_fu_772_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal kw_fu_124 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln337_fu_464_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal kh_fu_128 : STD_LOGIC_VECTOR (2 downto 0);
    signal indvar_flatten_fu_132 : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln335_5_fu_306_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_sig_allocacmp_indvar_flatten_load : STD_LOGIC_VECTOR (4 downto 0);
    signal ch_fu_136 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_sig_allocacmp_ch_2 : STD_LOGIC_VECTOR (1 downto 0);
    signal indvar_flatten43_fu_140 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln333_1_fu_271_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_sig_allocacmp_indvar_flatten43_load : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal add_ln335_1_fu_300_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal p_shl2_fu_339_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_shl_fu_332_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal p_shl2_cast_fu_346_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal empty_fu_350_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln343_1_fu_372_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_shl2_mid1_fu_387_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_shl_mid1_fu_380_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal p_shl2_cast_mid1_fu_394_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal p_mid115_fu_398_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln337_fu_415_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln333_fu_410_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln333_fu_365_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal or_ln335_fu_433_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln337_fu_454_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln335_fu_483_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal empty_136_fu_486_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_cast9_cast_fu_480_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal p_cast10_fu_491_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_fu_501_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_9_fu_515_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_10_fu_534_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln343_1_fu_541_p1 : STD_LOGIC_VECTOR (61 downto 0);
    signal sext_ln343_fu_531_p1 : STD_LOGIC_VECTOR (61 downto 0);
    signal select_ln333_2_fu_554_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal p_cast9_cast_mid1_fu_551_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal p_mid125_fu_563_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal empty_137_fu_495_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal rev_fu_509_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln343_3_fu_545_p2 : STD_LOGIC_VECTOR (61 downto 0);
    signal zext_ln343_2_fu_581_p1 : STD_LOGIC_VECTOR (61 downto 0);
    signal add_ln343_4_fu_584_p2 : STD_LOGIC_VECTOR (61 downto 0);
    signal zext_ln335_1_fu_598_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_mid1_fu_601_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln333_fu_559_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal p_cast10_mid1_fu_606_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal p_mid13_fu_610_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal select_ln333_3_fu_568_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_11_fu_627_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev32_fu_635_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln333_4_fu_575_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_12_fu_648_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal sext_ln340_fu_664_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln335_3_fu_641_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln341_fu_672_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_shl1_fu_688_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_shl4_cast_mid2_v_fu_707_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal or_ln333_fu_684_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln343_1_fu_695_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln343_3_fu_724_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln335_4_fu_718_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sext_ln341_fu_733_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal sext_ln335_fu_714_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal add_ln343_1_fu_741_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal p_shl3_mid2_fu_700_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_fu_787_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component full_pose_accel_mac_muladd_8s_8s_32s_32_3_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        din2 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component full_pose_accel_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mac_muladd_8s_8s_32s_32_3_1_U498 : component full_pose_accel_mac_muladd_8s_8s_32s_32_3_1
    generic map (
        ID => 1,
        NUM_STAGE => 3,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => p_ZL19g_conv1_weight_int8_2_q0,
        din1 => input_r_q0,
        din2 => acc_V_1_fu_120,
        ce => ap_const_logic_1,
        dout => grp_fu_787_p3);

    flow_control_loop_pipe_sequential_init_U : component full_pose_accel_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter6_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter2_stage0)) then 
                    ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    acc_V_1_fu_120_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    acc_V_1_fu_120 <= p_ZL18g_conv1_bias_int32_2_load;
                elsif ((ap_enable_reg_pp0_iter7 = ap_const_logic_1)) then 
                    acc_V_1_fu_120 <= acc_V_fu_772_p3;
                end if;
            end if; 
        end if;
    end process;

    ch_fu_136_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln333_fu_265_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    ch_fu_136 <= select_ln333_1_fu_292_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    ch_fu_136 <= ap_const_lv2_0;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten43_fu_140_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln333_fu_265_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten43_fu_140 <= add_ln333_1_fu_271_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten43_fu_140 <= ap_const_lv6_0;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten_fu_132_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln333_fu_265_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten_fu_132 <= select_ln335_5_fu_306_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten_fu_132 <= ap_const_lv5_0;
                end if;
            end if; 
        end if;
    end process;

    kh_fu_128_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    kh_fu_128 <= ap_const_lv3_0;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln333_reg_871 = ap_const_lv1_0))) then 
                    kh_fu_128 <= select_ln335_1_fu_446_p3;
                end if;
            end if; 
        end if;
    end process;

    kw_fu_124_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    kw_fu_124 <= ap_const_lv2_0;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln333_reg_871 = ap_const_lv1_0))) then 
                    kw_fu_124 <= add_ln337_fu_464_p2;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln333_fu_265_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                add_ln333_reg_875 <= add_ln333_fu_280_p2;
                icmp_ln335_reg_881 <= icmp_ln335_fu_286_p2;
                select_ln333_1_reg_892 <= select_ln333_1_fu_292_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln333_reg_871 = ap_const_lv1_0))) then
                add_ln335_reg_927 <= add_ln335_fu_427_p2;
                add_ln340_reg_942 <= add_ln340_fu_458_p2;
                add_ln343_2_reg_908 <= add_ln343_2_fu_375_p2;
                and_ln333_reg_920 <= and_ln333_fu_421_p2;
                    p_cast9_mid1_reg_914(10 downto 7) <= p_cast9_mid1_fu_404_p2(10 downto 7);
                select_ln335_1_reg_937 <= select_ln335_1_fu_446_p3;
                select_ln335_reg_932 <= select_ln335_fu_438_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln333_reg_871_pp0_iter1_reg = ap_const_lv1_0))) then
                add_ln340_1_reg_977 <= add_ln340_1_fu_667_p2;
                and_ln341_1_reg_982 <= and_ln341_1_fu_678_p2;
                select_ln335_2_reg_962 <= select_ln335_2_fu_616_p3;
                trunc_ln335_reg_967 <= trunc_ln335_fu_623_p1;
                trunc_ln343_1_reg_957 <= trunc_ln343_1_fu_594_p1;
                trunc_ln343_reg_952 <= trunc_ln343_fu_590_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                add_ln343_5_reg_987 <= add_ln343_5_fu_727_p2;
                add_ln343_reg_997 <= add_ln343_fu_747_p2;
                and_ln333_reg_920_pp0_iter2_reg <= and_ln333_reg_920;
                and_ln341_reg_992 <= and_ln341_fu_736_p2;
                and_ln341_reg_992_pp0_iter4_reg <= and_ln341_reg_992;
                and_ln341_reg_992_pp0_iter5_reg <= and_ln341_reg_992_pp0_iter4_reg;
                and_ln341_reg_992_pp0_iter6_reg <= and_ln341_reg_992_pp0_iter5_reg;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                icmp_ln333_reg_871_pp0_iter2_reg <= icmp_ln333_reg_871_pp0_iter1_reg;
                icmp_ln333_reg_871_pp0_iter3_reg <= icmp_ln333_reg_871_pp0_iter2_reg;
                icmp_ln333_reg_871_pp0_iter4_reg <= icmp_ln333_reg_871_pp0_iter3_reg;
                icmp_ln333_reg_871_pp0_iter5_reg <= icmp_ln333_reg_871_pp0_iter4_reg;
                icmp_ln335_reg_881_pp0_iter2_reg <= icmp_ln335_reg_881_pp0_iter1_reg;
                select_ln335_reg_932_pp0_iter2_reg <= select_ln335_reg_932;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                ch_2_reg_865 <= ap_sig_allocacmp_ch_2;
                icmp_ln333_reg_871 <= icmp_ln333_fu_265_p2;
                icmp_ln333_reg_871_pp0_iter1_reg <= icmp_ln333_reg_871;
                icmp_ln335_reg_881_pp0_iter1_reg <= icmp_ln335_reg_881;
                kh_3_reg_897 <= kh_fu_128;
                p_cast10_mid123_cast_reg_849 <= p_cast10_mid123_cast_fu_217_p1;
                    p_cast9_reg_902(10 downto 7) <= p_cast9_fu_356_p2(10 downto 7);
                select_ln327_2_cast_reg_854 <= select_ln327_2_cast_fu_221_p1;
                sub_ln343_cast_reg_860 <= sub_ln343_cast_fu_225_p1;
                    zext_ln329_1_cast_reg_844(3 downto 0) <= zext_ln329_1_cast_fu_213_p1(3 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_1 = and_ln333_reg_920) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln333_reg_871_pp0_iter1_reg = ap_const_lv1_0))) then
                icmp35_reg_972 <= icmp35_fu_658_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_lv1_0 = and_ln333_reg_920))) then
                icmp_reg_947 <= icmp_fu_525_p2;
            end if;
        end if;
    end process;
    zext_ln329_1_cast_reg_844(4) <= '0';
    p_cast9_reg_902(6 downto 0) <= "0000000";
    p_cast9_mid1_reg_914(6 downto 0) <= "0000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    acc_V_1_out <= acc_V_1_fu_120;

    acc_V_1_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln333_reg_871_pp0_iter5_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln333_reg_871_pp0_iter5_reg = ap_const_lv1_1))) then 
            acc_V_1_out_ap_vld <= ap_const_logic_1;
        else 
            acc_V_1_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    acc_V_fu_772_p3 <= 
        grp_fu_787_p3 when (and_ln341_reg_992_pp0_iter6_reg(0) = '1') else 
        acc_V_1_fu_120;
    add_ln333_1_fu_271_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten43_load) + unsigned(ap_const_lv6_1));
    add_ln333_fu_280_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_ch_2) + unsigned(ap_const_lv2_1));
    add_ln335_1_fu_300_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten_load) + unsigned(ap_const_lv5_1));
    add_ln335_fu_427_p2 <= std_logic_vector(unsigned(select_ln333_fu_365_p3) + unsigned(ap_const_lv3_1));
    add_ln337_fu_464_p2 <= std_logic_vector(unsigned(select_ln335_fu_438_p3) + unsigned(ap_const_lv2_1));
    add_ln340_1_fu_667_p2 <= std_logic_vector(signed(sext_ln340_fu_664_p1) + signed(zext_ln329_1_cast_reg_844));
    add_ln340_fu_458_p2 <= std_logic_vector(unsigned(zext_ln337_fu_454_p1) + unsigned(ap_const_lv3_7));
    add_ln343_1_fu_741_p2 <= std_logic_vector(signed(sext_ln341_fu_733_p1) + signed(sext_ln335_fu_714_p1));
    add_ln343_2_fu_375_p2 <= std_logic_vector(signed(sub_ln343_cast_reg_860) + signed(zext_ln343_1_fu_372_p1));
    add_ln343_3_fu_545_p2 <= std_logic_vector(signed(sext_ln343_1_fu_541_p1) + signed(sext_ln343_fu_531_p1));
    add_ln343_4_fu_584_p2 <= std_logic_vector(unsigned(add_ln343_3_fu_545_p2) + unsigned(zext_ln343_2_fu_581_p1));
    add_ln343_5_fu_727_p2 <= std_logic_vector(unsigned(sub_ln343_1_fu_695_p2) + unsigned(zext_ln343_3_fu_724_p1));
    add_ln343_fu_747_p2 <= std_logic_vector(unsigned(add_ln343_1_fu_741_p2) + unsigned(p_shl3_mid2_fu_700_p3));
    and_ln333_fu_421_p2 <= (xor_ln333_fu_410_p2 and icmp_ln337_fu_415_p2);
    and_ln341_1_fu_678_p2 <= (select_ln335_3_fu_641_p3 and icmp_ln341_fu_672_p2);
    and_ln341_fu_736_p2 <= (select_ln335_4_fu_718_p3 and and_ln341_1_reg_982);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage0_iter6 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state8_pp0_stage0_iter7 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln333_fu_265_p2)
    begin
        if (((icmp_ln333_fu_265_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_exit_pp0_iter2_stage0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_subdone, icmp_ln333_reg_871_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln333_reg_871_pp0_iter1_reg = ap_const_lv1_1))) then 
            ap_condition_exit_pp0_iter2_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter2_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter6_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter6_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7)
    begin
        if (((ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_ch_2_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, ch_fu_136)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_ch_2 <= ap_const_lv2_0;
        else 
            ap_sig_allocacmp_ch_2 <= ch_fu_136;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten43_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten43_fu_140)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_indvar_flatten43_load <= ap_const_lv6_0;
        else 
            ap_sig_allocacmp_indvar_flatten43_load <= indvar_flatten43_fu_140;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten_fu_132)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_indvar_flatten_load <= ap_const_lv5_0;
        else 
            ap_sig_allocacmp_indvar_flatten_load <= indvar_flatten_fu_132;
        end if; 
    end process;

    empty_136_fu_486_p2 <= std_logic_vector(signed(select_ln327_2_cast_reg_854) + signed(zext_ln335_fu_483_p1));
    empty_137_fu_495_p2 <= std_logic_vector(unsigned(p_cast9_cast_fu_480_p1) + unsigned(p_cast10_fu_491_p1));
    empty_fu_350_p2 <= std_logic_vector(unsigned(p_shl_fu_332_p3) - unsigned(p_shl2_cast_fu_346_p1));
    icmp35_fu_658_p2 <= "0" when (tmp_12_fu_648_p4 = ap_const_lv2_1) else "1";
    icmp_fu_525_p2 <= "0" when (tmp_9_fu_515_p4 = ap_const_lv2_1) else "1";
    icmp_ln333_fu_265_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten43_load = ap_const_lv6_2D) else "0";
    icmp_ln335_fu_286_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten_load = ap_const_lv5_F) else "0";
    icmp_ln337_fu_415_p2 <= "1" when (kw_fu_124 = ap_const_lv2_3) else "0";
    icmp_ln341_fu_672_p2 <= "1" when (unsigned(add_ln340_1_fu_667_p2) < unsigned(ap_const_lv5_A)) else "0";
    input_r_address0 <= zext_ln343_fu_757_p1(14 - 1 downto 0);

    input_r_ce0_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            input_r_ce0 <= ap_const_logic_1;
        else 
            input_r_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    or_ln333_fu_684_p2 <= (icmp_reg_947 or icmp_ln335_reg_881_pp0_iter2_reg);
    or_ln335_fu_433_p2 <= (icmp_ln335_reg_881 or and_ln333_fu_421_p2);
    p_ZL19g_conv1_weight_int8_2_address0 <= zext_ln343_4_fu_753_p1(10 - 1 downto 0);

    p_ZL19g_conv1_weight_int8_2_ce0_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            p_ZL19g_conv1_weight_int8_2_ce0 <= ap_const_logic_1;
        else 
            p_ZL19g_conv1_weight_int8_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;

        p_cast10_fu_491_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(empty_136_fu_486_p2),12));

        p_cast10_mid123_cast_fu_217_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_cast10_mid123),12));

        p_cast10_mid1_fu_606_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_mid1_fu_601_p2),12));

    p_cast9_cast_fu_480_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_cast9_reg_902),12));
    p_cast9_cast_mid1_fu_551_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_cast9_mid1_reg_914),12));
    p_cast9_fu_356_p2 <= std_logic_vector(unsigned(empty_fu_350_p2) + unsigned(ap_const_lv11_100));
    p_cast9_mid1_fu_404_p2 <= std_logic_vector(unsigned(p_mid115_fu_398_p2) + unsigned(ap_const_lv11_100));
    p_mid115_fu_398_p2 <= std_logic_vector(unsigned(p_shl_mid1_fu_380_p3) - unsigned(p_shl2_cast_mid1_fu_394_p1));
    p_mid125_fu_563_p2 <= std_logic_vector(unsigned(p_cast9_cast_mid1_fu_551_p1) + unsigned(p_cast10_mid123_cast_reg_849));
    p_mid13_fu_610_p2 <= std_logic_vector(unsigned(zext_ln333_fu_559_p1) + unsigned(p_cast10_mid1_fu_606_p1));
    p_mid1_fu_601_p2 <= std_logic_vector(signed(select_ln327_2_cast_reg_854) + signed(zext_ln335_1_fu_598_p1));
    p_shl1_fu_688_p3 <= (trunc_ln343_1_reg_957 & ap_const_lv2_0);
    p_shl2_cast_fu_346_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_shl2_fu_339_p3),11));
    p_shl2_cast_mid1_fu_394_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_shl2_mid1_fu_387_p3),11));
    p_shl2_fu_339_p3 <= (ch_2_reg_865 & ap_const_lv7_0);
    p_shl2_mid1_fu_387_p3 <= (add_ln333_reg_875 & ap_const_lv7_0);
    p_shl3_mid2_fu_700_p3 <= (trunc_ln335_reg_967 & ap_const_lv3_0);
    p_shl4_cast_mid2_v_fu_707_p3 <= (select_ln335_2_reg_962 & ap_const_lv1_0);
    p_shl_fu_332_p3 <= (ch_2_reg_865 & ap_const_lv9_0);
    p_shl_mid1_fu_380_p3 <= (add_ln333_reg_875 & ap_const_lv9_0);
    rev32_fu_635_p2 <= (tmp_11_fu_627_p3 xor ap_const_lv1_1);
    rev_fu_509_p2 <= (tmp_fu_501_p3 xor ap_const_lv1_1);
        select_ln327_2_cast_fu_221_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln327_2),9));

    select_ln333_1_fu_292_p3 <= 
        add_ln333_fu_280_p2 when (icmp_ln335_fu_286_p2(0) = '1') else 
        ap_sig_allocacmp_ch_2;
    select_ln333_2_fu_554_p3 <= 
        p_cast9_mid1_reg_914 when (icmp_ln335_reg_881_pp0_iter1_reg(0) = '1') else 
        p_cast9_reg_902;
    select_ln333_3_fu_568_p3 <= 
        p_mid125_fu_563_p2 when (icmp_ln335_reg_881_pp0_iter1_reg(0) = '1') else 
        empty_137_fu_495_p2;
    select_ln333_4_fu_575_p3 <= 
        notlhs_mid137 when (icmp_ln335_reg_881_pp0_iter1_reg(0) = '1') else 
        rev_fu_509_p2;
    select_ln333_fu_365_p3 <= 
        ap_const_lv3_0 when (icmp_ln335_reg_881(0) = '1') else 
        kh_fu_128;
    select_ln335_1_fu_446_p3 <= 
        add_ln335_fu_427_p2 when (and_ln333_fu_421_p2(0) = '1') else 
        select_ln333_fu_365_p3;
    select_ln335_2_fu_616_p3 <= 
        p_mid13_fu_610_p2 when (and_ln333_reg_920(0) = '1') else 
        select_ln333_3_fu_568_p3;
    select_ln335_3_fu_641_p3 <= 
        rev32_fu_635_p2 when (and_ln333_reg_920(0) = '1') else 
        select_ln333_4_fu_575_p3;
    select_ln335_4_fu_718_p3 <= 
        icmp35_reg_972 when (and_ln333_reg_920_pp0_iter2_reg(0) = '1') else 
        or_ln333_fu_684_p2;
    select_ln335_5_fu_306_p3 <= 
        ap_const_lv5_1 when (icmp_ln335_fu_286_p2(0) = '1') else 
        add_ln335_1_fu_300_p2;
    select_ln335_fu_438_p3 <= 
        ap_const_lv2_0 when (or_ln335_fu_433_p2(0) = '1') else 
        kw_fu_124;
        sext_ln335_fu_714_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_shl4_cast_mid2_v_fu_707_p3),14));

        sext_ln340_fu_664_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln340_reg_942),5));

        sext_ln341_fu_733_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln340_1_reg_977),14));

        sext_ln343_1_fu_541_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_10_fu_534_p3),62));

        sext_ln343_fu_531_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln343_2_reg_908),62));

    sub_ln343_1_fu_695_p2 <= std_logic_vector(unsigned(p_shl1_fu_688_p3) - unsigned(trunc_ln343_reg_952));
        sub_ln343_cast_fu_225_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln343),9));

    tmp_10_fu_534_p3 <= (add_ln343_2_reg_908 & ap_const_lv2_0);
    tmp_11_fu_627_p3 <= p_mid1_fu_601_p2(8 downto 8);
    tmp_12_fu_648_p4 <= p_mid1_fu_601_p2(8 downto 7);
    tmp_9_fu_515_p4 <= empty_136_fu_486_p2(8 downto 7);
    tmp_fu_501_p3 <= empty_136_fu_486_p2(8 downto 8);
    trunc_ln335_fu_623_p1 <= select_ln335_2_fu_616_p3(11 - 1 downto 0);
    trunc_ln343_1_fu_594_p1 <= add_ln343_4_fu_584_p2(8 - 1 downto 0);
    trunc_ln343_fu_590_p1 <= add_ln343_4_fu_584_p2(10 - 1 downto 0);
    xor_ln333_fu_410_p2 <= (icmp_ln335_reg_881 xor ap_const_lv1_1);
    zext_ln329_1_cast_fu_213_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln329_1),5));
    zext_ln333_fu_559_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln333_2_fu_554_p3),12));
    zext_ln335_1_fu_598_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln335_reg_927),9));
    zext_ln335_fu_483_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(kh_3_reg_897),9));
    zext_ln337_fu_454_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln335_fu_438_p3),3));
    zext_ln343_1_fu_372_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln333_1_reg_892),9));
    zext_ln343_2_fu_581_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln335_1_reg_937),62));
    zext_ln343_3_fu_724_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln335_reg_932_pp0_iter2_reg),10));
    zext_ln343_4_fu_753_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln343_5_reg_987),64));
    zext_ln343_fu_757_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln343_reg_997),64));
end behav;
