-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity full_pose_accel_adaptive_pool_flatten_receiver_2_Pipeline_POOL_IH_POOL_IW is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    select_ln447_6 : IN STD_LOGIC_VECTOR (6 downto 0);
    zext_ln457 : IN STD_LOGIC_VECTOR (2 downto 0);
    mul_ln430 : IN STD_LOGIC_VECTOR (67 downto 0);
    trunc_ln432_1 : IN STD_LOGIC_VECTOR (3 downto 0);
    zext_ln541 : IN STD_LOGIC_VECTOR (12 downto 0);
    input_r_address0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    input_r_ce0 : OUT STD_LOGIC;
    input_r_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    sum_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    sum_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of full_pose_accel_adaptive_pool_flatten_receiver_2_Pipeline_POOL_IH_POOL_IW is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv68_0 : STD_LOGIC_VECTOR (67 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv68_1 : STD_LOGIC_VECTOR (67 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv64_1 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter6 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln457_fu_165_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal zext_ln457_cast_fu_130_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln457_cast_reg_338 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln541_cast_fu_138_p1 : STD_LOGIC_VECTOR (62 downto 0);
    signal zext_ln541_cast_reg_343 : STD_LOGIC_VECTOR (62 downto 0);
    signal icmp_ln457_reg_348 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln457_reg_348_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln457_reg_348_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln457_reg_348_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln455_fu_193_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln455_reg_352 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln455_reg_352_pp0_iter2_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln541_fu_208_p1 : STD_LOGIC_VECTOR (62 downto 0);
    signal trunc_ln541_reg_357 : STD_LOGIC_VECTOR (62 downto 0);
    signal trunc_ln541_1_fu_237_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal trunc_ln541_1_reg_362 : STD_LOGIC_VECTOR (12 downto 0);
    signal trunc_ln541_2_fu_241_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln541_2_reg_367 : STD_LOGIC_VECTOR (14 downto 0);
    signal add_ln541_12_fu_268_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln541_12_reg_372 : STD_LOGIC_VECTOR (15 downto 0);
    signal input_load_reg_382 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln541_20_fu_274_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal sum_fu_64 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_1_fu_284_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal iw_fu_68 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln460_fu_212_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ih_fu_72 : STD_LOGIC_VECTOR (63 downto 0);
    signal select_ln457_fu_200_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal select_ln447_6_cast_fu_134_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal indvar_flatten_fu_76 : STD_LOGIC_VECTOR (67 downto 0);
    signal add_ln457_1_fu_170_p2 : STD_LOGIC_VECTOR (67 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal icmp_ln460_fu_188_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln457_fu_182_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln541_fu_233_p2 : STD_LOGIC_VECTOR (62 downto 0);
    signal p_shl1_fu_252_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_shl_fu_245_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln541_11_fu_262_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln541_19_fu_259_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln463_fu_281_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component full_pose_accel_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component full_pose_accel_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter1_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter5_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ih_fu_72_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    ih_fu_72 <= select_ln447_6_cast_fu_134_p1;
                elsif (((icmp_ln457_fu_165_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    ih_fu_72 <= select_ln457_fu_200_p3;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten_fu_76_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten_fu_76 <= ap_const_lv68_0;
                elsif (((icmp_ln457_fu_165_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    indvar_flatten_fu_76 <= add_ln457_1_fu_170_p2;
                end if;
            end if; 
        end if;
    end process;

    iw_fu_68_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    iw_fu_68 <= zext_ln457_cast_fu_130_p1;
                elsif (((icmp_ln457_fu_165_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    iw_fu_68 <= add_ln460_fu_212_p2;
                end if;
            end if; 
        end if;
    end process;

    sum_fu_64_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    sum_fu_64 <= ap_const_lv32_0;
                elsif ((ap_enable_reg_pp0_iter6 = ap_const_logic_1)) then 
                    sum_fu_64 <= sum_1_fu_284_p2;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                add_ln541_12_reg_372 <= add_ln541_12_fu_268_p2;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                icmp_ln457_reg_348_pp0_iter2_reg <= icmp_ln457_reg_348;
                icmp_ln457_reg_348_pp0_iter3_reg <= icmp_ln457_reg_348_pp0_iter2_reg;
                icmp_ln457_reg_348_pp0_iter4_reg <= icmp_ln457_reg_348_pp0_iter3_reg;
                input_load_reg_382 <= input_r_q0;
                select_ln455_reg_352_pp0_iter2_reg <= select_ln455_reg_352;
                trunc_ln541_1_reg_362 <= trunc_ln541_1_fu_237_p1;
                trunc_ln541_2_reg_367 <= trunc_ln541_2_fu_241_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
                icmp_ln457_reg_348 <= icmp_ln457_fu_165_p2;
                    zext_ln457_cast_reg_338(2 downto 0) <= zext_ln457_cast_fu_130_p1(2 downto 0);
                    zext_ln541_cast_reg_343(12 downto 0) <= zext_ln541_cast_fu_138_p1(12 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln457_fu_165_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                select_ln455_reg_352 <= select_ln455_fu_193_p3;
                trunc_ln541_reg_357 <= trunc_ln541_fu_208_p1;
            end if;
        end if;
    end process;
    zext_ln457_cast_reg_338(3) <= '0';
    zext_ln541_cast_reg_343(62 downto 13) <= "00000000000000000000000000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln457_1_fu_170_p2 <= std_logic_vector(unsigned(indvar_flatten_fu_76) + unsigned(ap_const_lv68_1));
    add_ln457_fu_182_p2 <= std_logic_vector(unsigned(ih_fu_72) + unsigned(ap_const_lv64_1));
    add_ln460_fu_212_p2 <= std_logic_vector(unsigned(select_ln455_fu_193_p3) + unsigned(ap_const_lv4_1));
    add_ln541_11_fu_262_p2 <= std_logic_vector(unsigned(p_shl1_fu_252_p3) + unsigned(p_shl_fu_245_p3));
    add_ln541_12_fu_268_p2 <= std_logic_vector(unsigned(add_ln541_11_fu_262_p2) + unsigned(zext_ln541_19_fu_259_p1));
    add_ln541_fu_233_p2 <= std_logic_vector(unsigned(zext_ln541_cast_reg_343) + unsigned(trunc_ln541_reg_357));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage0_iter6 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone, icmp_ln457_fu_165_p2)
    begin
        if (((icmp_ln457_fu_165_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter5_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter5_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6)
    begin
        if (((ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter1_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln457_fu_165_p2 <= "1" when (indvar_flatten_fu_76 = mul_ln430) else "0";
    icmp_ln460_fu_188_p2 <= "1" when (unsigned(iw_fu_68) < unsigned(trunc_ln432_1)) else "0";
    input_r_address0 <= zext_ln541_20_fu_274_p1(16 - 1 downto 0);

    input_r_ce0_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            input_r_ce0 <= ap_const_logic_1;
        else 
            input_r_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    p_shl1_fu_252_p3 <= (trunc_ln541_2_reg_367 & ap_const_lv1_0);
    p_shl_fu_245_p3 <= (trunc_ln541_1_reg_362 & ap_const_lv3_0);
    select_ln447_6_cast_fu_134_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln447_6),64));
    select_ln455_fu_193_p3 <= 
        iw_fu_68 when (icmp_ln460_fu_188_p2(0) = '1') else 
        zext_ln457_cast_reg_338;
    select_ln457_fu_200_p3 <= 
        ih_fu_72 when (icmp_ln460_fu_188_p2(0) = '1') else 
        add_ln457_fu_182_p2;
        sext_ln463_fu_281_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(input_load_reg_382),32));

    sum_1_fu_284_p2 <= std_logic_vector(signed(sext_ln463_fu_281_p1) + signed(sum_fu_64));
    sum_out <= sum_fu_64;

    sum_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln457_reg_348_pp0_iter4_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln457_reg_348_pp0_iter4_reg = ap_const_lv1_1))) then 
            sum_out_ap_vld <= ap_const_logic_1;
        else 
            sum_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    trunc_ln541_1_fu_237_p1 <= add_ln541_fu_233_p2(13 - 1 downto 0);
    trunc_ln541_2_fu_241_p1 <= add_ln541_fu_233_p2(15 - 1 downto 0);
    trunc_ln541_fu_208_p1 <= select_ln457_fu_200_p3(63 - 1 downto 0);
    zext_ln457_cast_fu_130_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln457),4));
    zext_ln541_19_fu_259_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln455_reg_352_pp0_iter2_reg),16));
    zext_ln541_20_fu_274_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln541_12_reg_372),64));
    zext_ln541_cast_fu_138_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln541),63));
end behav;
