-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity full_pose_accel_load_weight_blob_Pipeline_FC2_LOAD_WEIGHT_OUT_FC2_LOAD_WEIGHT_IN is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_gmem1_AWVALID : OUT STD_LOGIC;
    m_axi_gmem1_AWREADY : IN STD_LOGIC;
    m_axi_gmem1_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem1_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem1_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_WVALID : OUT STD_LOGIC;
    m_axi_gmem1_WREADY : IN STD_LOGIC;
    m_axi_gmem1_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem1_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_WLAST : OUT STD_LOGIC;
    m_axi_gmem1_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_ARVALID : OUT STD_LOGIC;
    m_axi_gmem1_ARREADY : IN STD_LOGIC;
    m_axi_gmem1_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem1_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem1_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_RVALID : IN STD_LOGIC;
    m_axi_gmem1_RREADY : OUT STD_LOGIC;
    m_axi_gmem1_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem1_RLAST : IN STD_LOGIC;
    m_axi_gmem1_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_gmem1_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_BVALID : IN STD_LOGIC;
    m_axi_gmem1_BREADY : OUT STD_LOGIC;
    m_axi_gmem1_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    weights : IN STD_LOGIC_VECTOR (63 downto 0);
    p_ZL17g_fc2_weight_int8_0_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    p_ZL17g_fc2_weight_int8_0_ce0 : OUT STD_LOGIC;
    p_ZL17g_fc2_weight_int8_0_we0 : OUT STD_LOGIC;
    p_ZL17g_fc2_weight_int8_0_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_ZL17g_fc2_weight_int8_1_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    p_ZL17g_fc2_weight_int8_1_ce0 : OUT STD_LOGIC;
    p_ZL17g_fc2_weight_int8_1_we0 : OUT STD_LOGIC;
    p_ZL17g_fc2_weight_int8_1_d0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
end;


architecture behav of full_pose_accel_load_weight_blob_Pipeline_FC2_LOAD_WEIGHT_OUT_FC2_LOAD_WEIGHT_IN is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv15_0 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000000";
    constant ap_const_lv15_4000 : STD_LOGIC_VECTOR (14 downto 0) := "100000000000000";
    constant ap_const_lv15_1 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000001";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv8_80 : STD_LOGIC_VECTOR (7 downto 0) := "10000000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv16_874C : STD_LOGIC_VECTOR (15 downto 0) := "1000011101001100";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter10 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter11 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter6 : BOOLEAN;
    signal ap_block_state8_pp0_stage0_iter7 : BOOLEAN;
    signal ap_block_state9_pp0_stage0_iter8 : BOOLEAN;
    signal ap_block_state10_pp0_stage0_iter9 : BOOLEAN;
    signal ap_block_state11_pp0_stage0_iter10 : BOOLEAN;
    signal ap_block_state12_pp0_stage0_iter11 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln243_fu_160_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal gmem1_blk_n_AR : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal gmem1_blk_n_R : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal trunc_ln243_fu_206_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln243_reg_378 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln243_reg_378_pp0_iter1_reg : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln243_reg_378_pp0_iter2_reg : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln243_reg_378_pp0_iter3_reg : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln243_reg_378_pp0_iter4_reg : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln243_reg_378_pp0_iter5_reg : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln243_reg_378_pp0_iter6_reg : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln243_reg_378_pp0_iter7_reg : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln243_reg_378_pp0_iter8_reg : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln243_reg_378_pp0_iter9_reg : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln243_reg_378_pp0_iter10_reg : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_reg_384 : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln99_fu_220_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln99_reg_389 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln99_reg_389_pp0_iter1_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln99_reg_389_pp0_iter2_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln99_reg_389_pp0_iter3_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln99_reg_389_pp0_iter4_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln99_reg_389_pp0_iter5_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln99_reg_389_pp0_iter6_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln99_reg_389_pp0_iter7_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln99_reg_389_pp0_iter8_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln99_reg_389_pp0_iter9_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal lshr_ln_reg_394 : STD_LOGIC_VECTOR (5 downto 0);
    signal lshr_ln_reg_394_pp0_iter1_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal lshr_ln_reg_394_pp0_iter2_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal lshr_ln_reg_394_pp0_iter3_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal lshr_ln_reg_394_pp0_iter4_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal lshr_ln_reg_394_pp0_iter5_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal lshr_ln_reg_394_pp0_iter6_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal lshr_ln_reg_394_pp0_iter7_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal lshr_ln_reg_394_pp0_iter8_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal lshr_ln_reg_394_pp0_iter9_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal lshr_ln_reg_394_pp0_iter10_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln247_fu_234_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln247_reg_399 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln247_reg_399_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln247_reg_399_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln247_reg_399_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln247_reg_399_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln247_reg_399_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln247_reg_399_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln247_reg_399_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln247_reg_399_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln247_reg_399_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln247_reg_399_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal gmem1_addr_reg_403 : STD_LOGIC_VECTOR (63 downto 0);
    signal word_V_reg_409 : STD_LOGIC_VECTOR (31 downto 0);
    signal bits_V_fu_332_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal bits_V_reg_414 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln247_fu_342_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal p_cast_cast_fu_306_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal i_fu_86 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln245_fu_238_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_i_load : STD_LOGIC_VECTOR (7 downto 0);
    signal o_fu_90 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln243_1_fu_198_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_sig_allocacmp_o_load : STD_LOGIC_VECTOR (7 downto 0);
    signal indvar_flatten_fu_94 : STD_LOGIC_VECTOR (14 downto 0);
    signal add_ln243_1_fu_166_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal ap_sig_allocacmp_indvar_flatten_load : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln245_fu_184_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln243_fu_178_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln243_fu_190_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal div_i_i_udiv_fu_259_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln126_fu_265_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln126_fu_269_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_1_fu_275_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal sext_ln126_fu_283_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal zext_ln126_3_fu_287_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln126_1_fu_291_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal p_cast_fu_296_p4 : STD_LOGIC_VECTOR (61 downto 0);
    signal shl_ln_fu_316_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln628_fu_323_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal lshr_ln628_fu_327_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_3_fu_336_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter8_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter9_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter10_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component full_pose_accel_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component full_pose_accel_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter10_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter10_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter10 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter11_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter11 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    i_fu_86_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln243_fu_160_p2 = ap_const_lv1_0))) then 
                    i_fu_86 <= add_ln245_fu_238_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_86 <= ap_const_lv8_0;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten_fu_94_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln243_fu_160_p2 = ap_const_lv1_0))) then 
                    indvar_flatten_fu_94 <= add_ln243_1_fu_166_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten_fu_94 <= ap_const_lv15_0;
                end if;
            end if; 
        end if;
    end process;

    o_fu_90_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln243_fu_160_p2 = ap_const_lv1_0))) then 
                    o_fu_90 <= select_ln243_1_fu_198_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    o_fu_90 <= ap_const_lv8_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
                ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
                ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
                bits_V_reg_414 <= bits_V_fu_332_p1;
                lshr_ln_reg_394_pp0_iter10_reg <= lshr_ln_reg_394_pp0_iter9_reg;
                lshr_ln_reg_394_pp0_iter2_reg <= lshr_ln_reg_394_pp0_iter1_reg;
                lshr_ln_reg_394_pp0_iter3_reg <= lshr_ln_reg_394_pp0_iter2_reg;
                lshr_ln_reg_394_pp0_iter4_reg <= lshr_ln_reg_394_pp0_iter3_reg;
                lshr_ln_reg_394_pp0_iter5_reg <= lshr_ln_reg_394_pp0_iter4_reg;
                lshr_ln_reg_394_pp0_iter6_reg <= lshr_ln_reg_394_pp0_iter5_reg;
                lshr_ln_reg_394_pp0_iter7_reg <= lshr_ln_reg_394_pp0_iter6_reg;
                lshr_ln_reg_394_pp0_iter8_reg <= lshr_ln_reg_394_pp0_iter7_reg;
                lshr_ln_reg_394_pp0_iter9_reg <= lshr_ln_reg_394_pp0_iter8_reg;
                trunc_ln243_reg_378_pp0_iter10_reg <= trunc_ln243_reg_378_pp0_iter9_reg;
                trunc_ln243_reg_378_pp0_iter2_reg <= trunc_ln243_reg_378_pp0_iter1_reg;
                trunc_ln243_reg_378_pp0_iter3_reg <= trunc_ln243_reg_378_pp0_iter2_reg;
                trunc_ln243_reg_378_pp0_iter4_reg <= trunc_ln243_reg_378_pp0_iter3_reg;
                trunc_ln243_reg_378_pp0_iter5_reg <= trunc_ln243_reg_378_pp0_iter4_reg;
                trunc_ln243_reg_378_pp0_iter6_reg <= trunc_ln243_reg_378_pp0_iter5_reg;
                trunc_ln243_reg_378_pp0_iter7_reg <= trunc_ln243_reg_378_pp0_iter6_reg;
                trunc_ln243_reg_378_pp0_iter8_reg <= trunc_ln243_reg_378_pp0_iter7_reg;
                trunc_ln243_reg_378_pp0_iter9_reg <= trunc_ln243_reg_378_pp0_iter8_reg;
                trunc_ln247_reg_399_pp0_iter10_reg <= trunc_ln247_reg_399_pp0_iter9_reg;
                trunc_ln247_reg_399_pp0_iter2_reg <= trunc_ln247_reg_399_pp0_iter1_reg;
                trunc_ln247_reg_399_pp0_iter3_reg <= trunc_ln247_reg_399_pp0_iter2_reg;
                trunc_ln247_reg_399_pp0_iter4_reg <= trunc_ln247_reg_399_pp0_iter3_reg;
                trunc_ln247_reg_399_pp0_iter5_reg <= trunc_ln247_reg_399_pp0_iter4_reg;
                trunc_ln247_reg_399_pp0_iter6_reg <= trunc_ln247_reg_399_pp0_iter5_reg;
                trunc_ln247_reg_399_pp0_iter7_reg <= trunc_ln247_reg_399_pp0_iter6_reg;
                trunc_ln247_reg_399_pp0_iter8_reg <= trunc_ln247_reg_399_pp0_iter7_reg;
                trunc_ln247_reg_399_pp0_iter9_reg <= trunc_ln247_reg_399_pp0_iter8_reg;
                trunc_ln99_reg_389_pp0_iter2_reg <= trunc_ln99_reg_389_pp0_iter1_reg;
                trunc_ln99_reg_389_pp0_iter3_reg <= trunc_ln99_reg_389_pp0_iter2_reg;
                trunc_ln99_reg_389_pp0_iter4_reg <= trunc_ln99_reg_389_pp0_iter3_reg;
                trunc_ln99_reg_389_pp0_iter5_reg <= trunc_ln99_reg_389_pp0_iter4_reg;
                trunc_ln99_reg_389_pp0_iter6_reg <= trunc_ln99_reg_389_pp0_iter5_reg;
                trunc_ln99_reg_389_pp0_iter7_reg <= trunc_ln99_reg_389_pp0_iter6_reg;
                trunc_ln99_reg_389_pp0_iter8_reg <= trunc_ln99_reg_389_pp0_iter7_reg;
                trunc_ln99_reg_389_pp0_iter9_reg <= trunc_ln99_reg_389_pp0_iter8_reg;
                word_V_reg_409 <= m_axi_gmem1_RDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                gmem1_addr_reg_403 <= p_cast_cast_fu_306_p1;
                lshr_ln_reg_394_pp0_iter1_reg <= lshr_ln_reg_394;
                trunc_ln243_reg_378_pp0_iter1_reg <= trunc_ln243_reg_378;
                trunc_ln247_reg_399_pp0_iter1_reg <= trunc_ln247_reg_399;
                trunc_ln99_reg_389_pp0_iter1_reg <= trunc_ln99_reg_389;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln243_fu_160_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                lshr_ln_reg_394 <= select_ln243_fu_190_p3(6 downto 1);
                tmp_reg_384 <= select_ln243_fu_190_p3(6 downto 2);
                trunc_ln243_reg_378 <= trunc_ln243_fu_206_p1;
                trunc_ln247_reg_399 <= trunc_ln247_fu_234_p1;
                trunc_ln99_reg_389 <= trunc_ln99_fu_220_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln126_1_fu_291_p2 <= std_logic_vector(unsigned(zext_ln126_3_fu_287_p1) + unsigned(weights));
    add_ln126_fu_269_p2 <= std_logic_vector(unsigned(zext_ln126_fu_265_p1) + unsigned(ap_const_lv16_874C));
    add_ln243_1_fu_166_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten_load) + unsigned(ap_const_lv15_1));
    add_ln243_fu_178_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_o_load) + unsigned(ap_const_lv8_1));
    add_ln245_fu_238_p2 <= std_logic_vector(unsigned(select_ln243_fu_190_p3) + unsigned(ap_const_lv8_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter9, m_axi_gmem1_ARREADY, m_axi_gmem1_RVALID)
    begin
                ap_block_pp0_stage0_11001 <= (((m_axi_gmem1_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_1)) or ((m_axi_gmem1_ARREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter9, m_axi_gmem1_ARREADY, m_axi_gmem1_RVALID)
    begin
                ap_block_pp0_stage0_subdone <= (((m_axi_gmem1_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_1)) or ((m_axi_gmem1_ARREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)));
    end process;


    ap_block_state10_pp0_stage0_iter9_assign_proc : process(m_axi_gmem1_RVALID)
    begin
                ap_block_state10_pp0_stage0_iter9 <= (m_axi_gmem1_RVALID = ap_const_logic_0);
    end process;

        ap_block_state11_pp0_stage0_iter10 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state12_pp0_stage0_iter11 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage0_iter6 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state8_pp0_stage0_iter7 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state9_pp0_stage0_iter8 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln243_fu_160_p2)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln243_fu_160_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter10_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter10_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10, ap_enable_reg_pp0_iter11)
    begin
        if (((ap_enable_reg_pp0_iter11 = ap_const_logic_0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, i_fu_86, ap_loop_init)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_sig_allocacmp_i_load <= ap_const_lv8_0;
        else 
            ap_sig_allocacmp_i_load <= i_fu_86;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten_fu_94)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_sig_allocacmp_indvar_flatten_load <= ap_const_lv15_0;
        else 
            ap_sig_allocacmp_indvar_flatten_load <= indvar_flatten_fu_94;
        end if; 
    end process;


    ap_sig_allocacmp_o_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, o_fu_90)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_sig_allocacmp_o_load <= ap_const_lv8_0;
        else 
            ap_sig_allocacmp_o_load <= o_fu_90;
        end if; 
    end process;

    bits_V_fu_332_p1 <= lshr_ln628_fu_327_p2(8 - 1 downto 0);
    div_i_i_udiv_fu_259_p3 <= (trunc_ln243_reg_378 & tmp_reg_384);

    gmem1_blk_n_AR_assign_proc : process(ap_enable_reg_pp0_iter2, m_axi_gmem1_ARREADY, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            gmem1_blk_n_AR <= m_axi_gmem1_ARREADY;
        else 
            gmem1_blk_n_AR <= ap_const_logic_1;
        end if; 
    end process;


    gmem1_blk_n_R_assign_proc : process(ap_enable_reg_pp0_iter9, m_axi_gmem1_RVALID, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            gmem1_blk_n_R <= m_axi_gmem1_RVALID;
        else 
            gmem1_blk_n_R <= ap_const_logic_1;
        end if; 
    end process;

    icmp_ln243_fu_160_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten_load = ap_const_lv15_4000) else "0";
    icmp_ln245_fu_184_p2 <= "1" when (ap_sig_allocacmp_i_load = ap_const_lv8_80) else "0";
    lshr_ln628_fu_327_p2 <= std_logic_vector(shift_right(unsigned(word_V_reg_409),to_integer(unsigned('0' & zext_ln628_fu_323_p1(31-1 downto 0)))));
    m_axi_gmem1_ARADDR <= gmem1_addr_reg_403;
    m_axi_gmem1_ARBURST <= ap_const_lv2_0;
    m_axi_gmem1_ARCACHE <= ap_const_lv4_0;
    m_axi_gmem1_ARID <= ap_const_lv1_0;
    m_axi_gmem1_ARLEN <= ap_const_lv32_1;
    m_axi_gmem1_ARLOCK <= ap_const_lv2_0;
    m_axi_gmem1_ARPROT <= ap_const_lv3_0;
    m_axi_gmem1_ARQOS <= ap_const_lv4_0;
    m_axi_gmem1_ARREGION <= ap_const_lv4_0;
    m_axi_gmem1_ARSIZE <= ap_const_lv3_0;
    m_axi_gmem1_ARUSER <= ap_const_lv1_0;

    m_axi_gmem1_ARVALID_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            m_axi_gmem1_ARVALID <= ap_const_logic_1;
        else 
            m_axi_gmem1_ARVALID <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem1_AWADDR <= ap_const_lv64_0;
    m_axi_gmem1_AWBURST <= ap_const_lv2_0;
    m_axi_gmem1_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem1_AWID <= ap_const_lv1_0;
    m_axi_gmem1_AWLEN <= ap_const_lv32_0;
    m_axi_gmem1_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem1_AWPROT <= ap_const_lv3_0;
    m_axi_gmem1_AWQOS <= ap_const_lv4_0;
    m_axi_gmem1_AWREGION <= ap_const_lv4_0;
    m_axi_gmem1_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem1_AWUSER <= ap_const_lv1_0;
    m_axi_gmem1_AWVALID <= ap_const_logic_0;
    m_axi_gmem1_BREADY <= ap_const_logic_0;

    m_axi_gmem1_RREADY_assign_proc : process(ap_enable_reg_pp0_iter9, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            m_axi_gmem1_RREADY <= ap_const_logic_1;
        else 
            m_axi_gmem1_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem1_WDATA <= ap_const_lv32_0;
    m_axi_gmem1_WID <= ap_const_lv1_0;
    m_axi_gmem1_WLAST <= ap_const_logic_0;
    m_axi_gmem1_WSTRB <= ap_const_lv4_0;
    m_axi_gmem1_WUSER <= ap_const_lv1_0;
    m_axi_gmem1_WVALID <= ap_const_logic_0;
    p_ZL17g_fc2_weight_int8_0_address0 <= zext_ln247_fu_342_p1(13 - 1 downto 0);

    p_ZL17g_fc2_weight_int8_0_ce0_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            p_ZL17g_fc2_weight_int8_0_ce0 <= ap_const_logic_1;
        else 
            p_ZL17g_fc2_weight_int8_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL17g_fc2_weight_int8_0_d0 <= bits_V_reg_414;

    p_ZL17g_fc2_weight_int8_0_we0_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_pp0_stage0_11001, trunc_ln247_reg_399_pp0_iter10_reg)
    begin
        if (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (trunc_ln247_reg_399_pp0_iter10_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            p_ZL17g_fc2_weight_int8_0_we0 <= ap_const_logic_1;
        else 
            p_ZL17g_fc2_weight_int8_0_we0 <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL17g_fc2_weight_int8_1_address0 <= zext_ln247_fu_342_p1(13 - 1 downto 0);

    p_ZL17g_fc2_weight_int8_1_ce0_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            p_ZL17g_fc2_weight_int8_1_ce0 <= ap_const_logic_1;
        else 
            p_ZL17g_fc2_weight_int8_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL17g_fc2_weight_int8_1_d0 <= bits_V_reg_414;

    p_ZL17g_fc2_weight_int8_1_we0_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_pp0_stage0_11001, trunc_ln247_reg_399_pp0_iter10_reg)
    begin
        if (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (trunc_ln247_reg_399_pp0_iter10_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            p_ZL17g_fc2_weight_int8_1_we0 <= ap_const_logic_1;
        else 
            p_ZL17g_fc2_weight_int8_1_we0 <= ap_const_logic_0;
        end if; 
    end process;

        p_cast_cast_fu_306_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_cast_fu_296_p4),64));

    p_cast_fu_296_p4 <= add_ln126_1_fu_291_p2(63 downto 2);
    select_ln243_1_fu_198_p3 <= 
        add_ln243_fu_178_p2 when (icmp_ln245_fu_184_p2(0) = '1') else 
        ap_sig_allocacmp_o_load;
    select_ln243_fu_190_p3 <= 
        ap_const_lv8_0 when (icmp_ln245_fu_184_p2(0) = '1') else 
        ap_sig_allocacmp_i_load;
        sext_ln126_fu_283_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_1_fu_275_p3),19));

    shl_ln_fu_316_p3 <= (trunc_ln99_reg_389_pp0_iter9_reg & ap_const_lv3_0);
    tmp_1_fu_275_p3 <= (add_ln126_fu_269_p2 & ap_const_lv2_0);
    tmp_3_fu_336_p3 <= (trunc_ln243_reg_378_pp0_iter10_reg & lshr_ln_reg_394_pp0_iter10_reg);
    trunc_ln243_fu_206_p1 <= select_ln243_1_fu_198_p3(7 - 1 downto 0);
    trunc_ln247_fu_234_p1 <= select_ln243_fu_190_p3(1 - 1 downto 0);
    trunc_ln99_fu_220_p1 <= select_ln243_fu_190_p3(2 - 1 downto 0);
    zext_ln126_3_fu_287_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln126_fu_283_p1),64));
    zext_ln126_fu_265_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(div_i_i_udiv_fu_259_p3),16));
    zext_ln247_fu_342_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_3_fu_336_p3),64));
    zext_ln628_fu_323_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln_fu_316_p3),32));
end behav;
