-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity full_pose_accel_conv2_receiver_1_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    input_0_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    input_0_ce0 : OUT STD_LOGIC;
    input_0_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    input_1_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    input_1_ce0 : OUT STD_LOGIC;
    input_1_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    input_2_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    input_2_ce0 : OUT STD_LOGIC;
    input_2_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    input_3_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    input_3_ce0 : OUT STD_LOGIC;
    input_3_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    input_4_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    input_4_ce0 : OUT STD_LOGIC;
    input_4_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    input_5_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    input_5_ce0 : OUT STD_LOGIC;
    input_5_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    input_6_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    input_6_ce0 : OUT STD_LOGIC;
    input_6_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    input_7_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    input_7_ce0 : OUT STD_LOGIC;
    input_7_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    output_r_address0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    output_r_ce0 : OUT STD_LOGIC;
    output_r_we0 : OUT STD_LOGIC;
    output_r_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_ZL21g_conv2_requant_shift_1_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    p_ZL21g_conv2_requant_shift_1_ce0 : OUT STD_LOGIC;
    p_ZL21g_conv2_requant_shift_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_ZL18g_conv2_bias_int32_1_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    p_ZL18g_conv2_bias_int32_1_ce0 : OUT STD_LOGIC;
    p_ZL18g_conv2_bias_int32_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_ZL20g_conv2_requant_mult_1_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    p_ZL20g_conv2_requant_mult_1_ce0 : OUT STD_LOGIC;
    p_ZL20g_conv2_requant_mult_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_ZL19g_conv2_weight_int8_1_0_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    p_ZL19g_conv2_weight_int8_1_0_ce0 : OUT STD_LOGIC;
    p_ZL19g_conv2_weight_int8_1_0_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_ZL19g_conv2_weight_int8_1_1_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    p_ZL19g_conv2_weight_int8_1_1_ce0 : OUT STD_LOGIC;
    p_ZL19g_conv2_weight_int8_1_1_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_ZL19g_conv2_weight_int8_1_2_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    p_ZL19g_conv2_weight_int8_1_2_ce0 : OUT STD_LOGIC;
    p_ZL19g_conv2_weight_int8_1_2_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_ZL19g_conv2_weight_int8_1_3_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    p_ZL19g_conv2_weight_int8_1_3_ce0 : OUT STD_LOGIC;
    p_ZL19g_conv2_weight_int8_1_3_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_ZL19g_conv2_weight_int8_1_4_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    p_ZL19g_conv2_weight_int8_1_4_ce0 : OUT STD_LOGIC;
    p_ZL19g_conv2_weight_int8_1_4_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_ZL19g_conv2_weight_int8_1_5_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    p_ZL19g_conv2_weight_int8_1_5_ce0 : OUT STD_LOGIC;
    p_ZL19g_conv2_weight_int8_1_5_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_ZL19g_conv2_weight_int8_1_6_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    p_ZL19g_conv2_weight_int8_1_6_ce0 : OUT STD_LOGIC;
    p_ZL19g_conv2_weight_int8_1_6_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_ZL19g_conv2_weight_int8_1_7_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    p_ZL19g_conv2_weight_int8_1_7_ce0 : OUT STD_LOGIC;
    p_ZL19g_conv2_weight_int8_1_7_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    grp_fu_702_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_702_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_702_p_dout0 : IN STD_LOGIC_VECTOR (63 downto 0);
    grp_fu_702_p_ce : OUT STD_LOGIC );
end;


architecture behav of full_pose_accel_conv2_receiver_1_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (18 downto 0) := "0000000000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (18 downto 0) := "0000000000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (18 downto 0) := "0000000000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (18 downto 0) := "0000000000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (18 downto 0) := "0000000000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (18 downto 0) := "0000000000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (18 downto 0) := "0000000000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (18 downto 0) := "0000000000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (18 downto 0) := "0000000000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (18 downto 0) := "0000000001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (18 downto 0) := "0000000010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (18 downto 0) := "0000000100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (18 downto 0) := "0000001000000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (18 downto 0) := "0000010000000000000";
    constant ap_ST_fsm_state15 : STD_LOGIC_VECTOR (18 downto 0) := "0000100000000000000";
    constant ap_ST_fsm_state16 : STD_LOGIC_VECTOR (18 downto 0) := "0001000000000000000";
    constant ap_ST_fsm_state17 : STD_LOGIC_VECTOR (18 downto 0) := "0010000000000000000";
    constant ap_ST_fsm_state18 : STD_LOGIC_VECTOR (18 downto 0) := "0100000000000000000";
    constant ap_ST_fsm_state19 : STD_LOGIC_VECTOR (18 downto 0) := "1000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv32_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010010";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv64_1 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv16_A000 : STD_LOGIC_VECTOR (15 downto 0) := "1010000000000000";
    constant ap_const_lv16_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    constant ap_const_lv12_500 : STD_LOGIC_VECTOR (11 downto 0) := "010100000000";
    constant ap_const_lv12_1 : STD_LOGIC_VECTOR (11 downto 0) := "000000000001";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv4_A : STD_LOGIC_VECTOR (3 downto 0) := "1010";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv9_1FF : STD_LOGIC_VECTOR (8 downto 0) := "111111111";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv31_7FFFFFFF : STD_LOGIC_VECTOR (30 downto 0) := "1111111111111111111111111111111";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv57_0 : STD_LOGIC_VECTOR (56 downto 0) := "000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv64_FFFFFFFFFFFFFF81 : STD_LOGIC_VECTOR (63 downto 0) := "1111111111111111111111111111111111111111111111111111111110000001";
    constant ap_const_lv8_7F : STD_LOGIC_VECTOR (7 downto 0) := "01111111";
    constant ap_const_lv8_81 : STD_LOGIC_VECTOR (7 downto 0) := "10000001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (18 downto 0) := "0000000000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal reg_311 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal icmp_ln378_reg_904 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_fu_315_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln50_reg_896 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal icmp_ln378_fu_372_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln376_fu_357_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln376_fu_408_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln376_reg_913 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal select_ln378_fu_448_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln378_reg_919 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln378_3_fu_456_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln378_3_reg_926 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln376_3_fu_468_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal select_ln376_3_reg_935 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal trunc_ln397_fu_474_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln397_reg_942 : STD_LOGIC_VECTOR (2 downto 0);
    signal p_mid146_fu_482_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_mid146_reg_952 : STD_LOGIC_VECTOR (8 downto 0);
    signal notlhs_mid150_fu_489_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal notlhs_mid150_reg_957 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_fu_505_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_reg_962 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln376_9_fu_542_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln376_9_reg_967 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln409_fu_549_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal add_ln409_reg_978 : STD_LOGIC_VECTOR (13 downto 0);
    signal trunc_ln409_fu_555_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal trunc_ln409_reg_983 : STD_LOGIC_VECTOR (12 downto 0);
    signal p_ZL18g_conv2_bias_int32_1_load_reg_988 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal select_ln376_4_fu_559_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln376_4_reg_993 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln409_4_fu_592_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln409_4_reg_999 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln840_25_fu_613_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln840_25_reg_1004 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal add_ln840_fu_634_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln840_reg_1019 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln840_21_fu_639_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln840_21_reg_1024 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln840_26_fu_651_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln840_26_reg_1029 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_ZL20g_conv2_requant_mult_1_load_reg_1034 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln376_fu_656_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal trunc_ln376_reg_1039 : STD_LOGIC_VECTOR (30 downto 0);
    signal total_V_fu_664_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal total_V_reg_1044 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln376_fu_669_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln541_fu_672_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln376_3_fu_681_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal add_ln376_3_reg_1059 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_CS_fsm_state13 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state13 : signal is "none";
    signal shl_ln376_fu_689_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal shl_ln376_reg_1064 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state14 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state14 : signal is "none";
    signal product_reg_1070 : STD_LOGIC_VECTOR (63 downto 0);
    signal sub_ln376_fu_695_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln376_reg_1078 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state15 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state15 : signal is "none";
    signal sub_ln57_fu_701_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal sub_ln57_reg_1083 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln376_12_fu_708_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln376_12_reg_1088 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state16 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state16 : signal is "none";
    signal add_ln55_fu_717_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln55_reg_1093 : STD_LOGIC_VECTOR (63 downto 0);
    signal select_ln50_fu_726_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal select_ln50_reg_1098 : STD_LOGIC_VECTOR (63 downto 0);
    signal select_ln54_fu_749_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal select_ln54_reg_1103 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state17 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state17 : signal is "none";
    signal tmp_50_reg_1109 : STD_LOGIC_VECTOR (56 downto 0);
    signal select_ln39_fu_793_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln39_reg_1114 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state18 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state18 : signal is "none";
    signal grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_ap_start : STD_LOGIC;
    signal grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_ap_done : STD_LOGIC;
    signal grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_ap_idle : STD_LOGIC;
    signal grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_ap_ready : STD_LOGIC;
    signal grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_input_0_address0 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_input_0_ce0 : STD_LOGIC;
    signal grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_input_1_address0 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_input_1_ce0 : STD_LOGIC;
    signal grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_input_2_address0 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_input_2_ce0 : STD_LOGIC;
    signal grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_input_3_address0 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_input_3_ce0 : STD_LOGIC;
    signal grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_input_4_address0 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_input_4_ce0 : STD_LOGIC;
    signal grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_input_5_address0 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_input_5_ce0 : STD_LOGIC;
    signal grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_input_6_address0 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_input_6_ce0 : STD_LOGIC;
    signal grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_input_7_address0 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_input_7_ce0 : STD_LOGIC;
    signal grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_p_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_p_out_ap_vld : STD_LOGIC;
    signal grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_p_out1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_p_out1_ap_vld : STD_LOGIC;
    signal grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_p_out2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_p_out2_ap_vld : STD_LOGIC;
    signal grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_p_out3 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_p_out3_ap_vld : STD_LOGIC;
    signal grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_p_out4 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_p_out4_ap_vld : STD_LOGIC;
    signal grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_p_out5 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_p_out5_ap_vld : STD_LOGIC;
    signal grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_p_out6 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_p_out6_ap_vld : STD_LOGIC;
    signal grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_add_i2513_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_add_i2513_out_ap_vld : STD_LOGIC;
    signal grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_p_ZL19g_conv2_weight_int8_1_0_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_p_ZL19g_conv2_weight_int8_1_0_ce0 : STD_LOGIC;
    signal grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_p_ZL19g_conv2_weight_int8_1_1_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_p_ZL19g_conv2_weight_int8_1_1_ce0 : STD_LOGIC;
    signal grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_p_ZL19g_conv2_weight_int8_1_2_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_p_ZL19g_conv2_weight_int8_1_2_ce0 : STD_LOGIC;
    signal grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_p_ZL19g_conv2_weight_int8_1_3_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_p_ZL19g_conv2_weight_int8_1_3_ce0 : STD_LOGIC;
    signal grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_p_ZL19g_conv2_weight_int8_1_4_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_p_ZL19g_conv2_weight_int8_1_4_ce0 : STD_LOGIC;
    signal grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_p_ZL19g_conv2_weight_int8_1_5_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_p_ZL19g_conv2_weight_int8_1_5_ce0 : STD_LOGIC;
    signal grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_p_ZL19g_conv2_weight_int8_1_6_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_p_ZL19g_conv2_weight_int8_1_6_ce0 : STD_LOGIC;
    signal grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_p_ZL19g_conv2_weight_int8_1_7_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_p_ZL19g_conv2_weight_int8_1_7_ce0 : STD_LOGIC;
    signal grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_ap_start_reg : STD_LOGIC := '0';
    signal zext_ln376_fu_349_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln376_7_fu_464_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln409_6_fu_801_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state19 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state19 : signal is "none";
    signal w_fu_140 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln380_fu_512_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal h_fu_144 : STD_LOGIC_VECTOR (7 downto 0);
    signal indvar_flatten63_fu_148 : STD_LOGIC_VECTOR (11 downto 0);
    signal select_ln378_4_fu_384_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal oc_fu_152 : STD_LOGIC_VECTOR (5 downto 0);
    signal indvar_flatten80_fu_156 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln376_4_fu_363_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln378_2_fu_378_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal icmp_ln380_fu_425_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln376_fu_420_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln376_fu_413_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal and_ln376_fu_431_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln378_fu_443_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln378_fu_437_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_cast_mid144_fu_479_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_48_fu_495_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_fu_531_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln376_8_fu_538_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal zext_ln409_fu_546_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_47_fu_572_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal p_shl_fu_565_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln409_4_fu_579_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln409_3_fu_583_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln409_5_fu_589_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln840_24_fu_607_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln840_23_fu_645_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln840_22_fu_660_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln376_11_fu_686_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln376_10_fu_705_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal shl_ln51_fu_712_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal ashr_ln57_fu_721_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_49_fu_733_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln54_fu_744_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ashr_ln55_fu_740_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal icmp_ln39_fu_766_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln42_fu_771_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln39_fu_787_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln39_8_fu_779_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln218_fu_776_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (18 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal ap_ST_fsm_state12_blk : STD_LOGIC;
    signal ap_ST_fsm_state13_blk : STD_LOGIC;
    signal ap_ST_fsm_state14_blk : STD_LOGIC;
    signal ap_ST_fsm_state15_blk : STD_LOGIC;
    signal ap_ST_fsm_state16_blk : STD_LOGIC;
    signal ap_ST_fsm_state17_blk : STD_LOGIC;
    signal ap_ST_fsm_state18_blk : STD_LOGIC;
    signal ap_ST_fsm_state19_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component full_pose_accel_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        select_ln378_5 : IN STD_LOGIC_VECTOR (7 downto 0);
        select_ln376_8 : IN STD_LOGIC_VECTOR (5 downto 0);
        trunc_ln397 : IN STD_LOGIC_VECTOR (2 downto 0);
        p_mid146 : IN STD_LOGIC_VECTOR (8 downto 0);
        notlhs_mid150 : IN STD_LOGIC_VECTOR (0 downto 0);
        notrhs_mid152 : IN STD_LOGIC_VECTOR (0 downto 0);
        zext_ln380_2 : IN STD_LOGIC_VECTOR (3 downto 0);
        input_0_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
        input_0_ce0 : OUT STD_LOGIC;
        input_0_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        input_1_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
        input_1_ce0 : OUT STD_LOGIC;
        input_1_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        input_2_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
        input_2_ce0 : OUT STD_LOGIC;
        input_2_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        input_3_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
        input_3_ce0 : OUT STD_LOGIC;
        input_3_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        input_4_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
        input_4_ce0 : OUT STD_LOGIC;
        input_4_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        input_5_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
        input_5_ce0 : OUT STD_LOGIC;
        input_5_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        input_6_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
        input_6_ce0 : OUT STD_LOGIC;
        input_6_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        input_7_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
        input_7_ce0 : OUT STD_LOGIC;
        input_7_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        p_out_ap_vld : OUT STD_LOGIC;
        p_out1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        p_out1_ap_vld : OUT STD_LOGIC;
        p_out2 : OUT STD_LOGIC_VECTOR (31 downto 0);
        p_out2_ap_vld : OUT STD_LOGIC;
        p_out3 : OUT STD_LOGIC_VECTOR (31 downto 0);
        p_out3_ap_vld : OUT STD_LOGIC;
        p_out4 : OUT STD_LOGIC_VECTOR (31 downto 0);
        p_out4_ap_vld : OUT STD_LOGIC;
        p_out5 : OUT STD_LOGIC_VECTOR (31 downto 0);
        p_out5_ap_vld : OUT STD_LOGIC;
        p_out6 : OUT STD_LOGIC_VECTOR (31 downto 0);
        p_out6_ap_vld : OUT STD_LOGIC;
        add_i2513_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        add_i2513_out_ap_vld : OUT STD_LOGIC;
        p_ZL19g_conv2_weight_int8_1_0_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_ZL19g_conv2_weight_int8_1_0_ce0 : OUT STD_LOGIC;
        p_ZL19g_conv2_weight_int8_1_0_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_ZL19g_conv2_weight_int8_1_1_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_ZL19g_conv2_weight_int8_1_1_ce0 : OUT STD_LOGIC;
        p_ZL19g_conv2_weight_int8_1_1_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_ZL19g_conv2_weight_int8_1_2_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_ZL19g_conv2_weight_int8_1_2_ce0 : OUT STD_LOGIC;
        p_ZL19g_conv2_weight_int8_1_2_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_ZL19g_conv2_weight_int8_1_3_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_ZL19g_conv2_weight_int8_1_3_ce0 : OUT STD_LOGIC;
        p_ZL19g_conv2_weight_int8_1_3_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_ZL19g_conv2_weight_int8_1_4_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_ZL19g_conv2_weight_int8_1_4_ce0 : OUT STD_LOGIC;
        p_ZL19g_conv2_weight_int8_1_4_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_ZL19g_conv2_weight_int8_1_5_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_ZL19g_conv2_weight_int8_1_5_ce0 : OUT STD_LOGIC;
        p_ZL19g_conv2_weight_int8_1_5_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_ZL19g_conv2_weight_int8_1_6_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_ZL19g_conv2_weight_int8_1_6_ce0 : OUT STD_LOGIC;
        p_ZL19g_conv2_weight_int8_1_6_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_ZL19g_conv2_weight_int8_1_7_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_ZL19g_conv2_weight_int8_1_7_ce0 : OUT STD_LOGIC;
        p_ZL19g_conv2_weight_int8_1_7_q0 : IN STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component full_pose_accel_mul_32s_32s_64_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;



begin
    grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260 : component full_pose_accel_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_ap_start,
        ap_done => grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_ap_done,
        ap_idle => grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_ap_idle,
        ap_ready => grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_ap_ready,
        select_ln378_5 => select_ln378_3_reg_926,
        select_ln376_8 => select_ln376_3_reg_935,
        trunc_ln397 => trunc_ln397_reg_942,
        p_mid146 => p_mid146_reg_952,
        notlhs_mid150 => notlhs_mid150_reg_957,
        notrhs_mid152 => icmp_reg_962,
        zext_ln380_2 => select_ln378_reg_919,
        input_0_address0 => grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_input_0_address0,
        input_0_ce0 => grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_input_0_ce0,
        input_0_q0 => input_0_q0,
        input_1_address0 => grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_input_1_address0,
        input_1_ce0 => grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_input_1_ce0,
        input_1_q0 => input_1_q0,
        input_2_address0 => grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_input_2_address0,
        input_2_ce0 => grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_input_2_ce0,
        input_2_q0 => input_2_q0,
        input_3_address0 => grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_input_3_address0,
        input_3_ce0 => grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_input_3_ce0,
        input_3_q0 => input_3_q0,
        input_4_address0 => grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_input_4_address0,
        input_4_ce0 => grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_input_4_ce0,
        input_4_q0 => input_4_q0,
        input_5_address0 => grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_input_5_address0,
        input_5_ce0 => grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_input_5_ce0,
        input_5_q0 => input_5_q0,
        input_6_address0 => grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_input_6_address0,
        input_6_ce0 => grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_input_6_ce0,
        input_6_q0 => input_6_q0,
        input_7_address0 => grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_input_7_address0,
        input_7_ce0 => grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_input_7_ce0,
        input_7_q0 => input_7_q0,
        p_out => grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_p_out,
        p_out_ap_vld => grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_p_out_ap_vld,
        p_out1 => grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_p_out1,
        p_out1_ap_vld => grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_p_out1_ap_vld,
        p_out2 => grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_p_out2,
        p_out2_ap_vld => grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_p_out2_ap_vld,
        p_out3 => grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_p_out3,
        p_out3_ap_vld => grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_p_out3_ap_vld,
        p_out4 => grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_p_out4,
        p_out4_ap_vld => grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_p_out4_ap_vld,
        p_out5 => grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_p_out5,
        p_out5_ap_vld => grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_p_out5_ap_vld,
        p_out6 => grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_p_out6,
        p_out6_ap_vld => grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_p_out6_ap_vld,
        add_i2513_out => grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_add_i2513_out,
        add_i2513_out_ap_vld => grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_add_i2513_out_ap_vld,
        p_ZL19g_conv2_weight_int8_1_0_address0 => grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_p_ZL19g_conv2_weight_int8_1_0_address0,
        p_ZL19g_conv2_weight_int8_1_0_ce0 => grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_p_ZL19g_conv2_weight_int8_1_0_ce0,
        p_ZL19g_conv2_weight_int8_1_0_q0 => p_ZL19g_conv2_weight_int8_1_0_q0,
        p_ZL19g_conv2_weight_int8_1_1_address0 => grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_p_ZL19g_conv2_weight_int8_1_1_address0,
        p_ZL19g_conv2_weight_int8_1_1_ce0 => grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_p_ZL19g_conv2_weight_int8_1_1_ce0,
        p_ZL19g_conv2_weight_int8_1_1_q0 => p_ZL19g_conv2_weight_int8_1_1_q0,
        p_ZL19g_conv2_weight_int8_1_2_address0 => grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_p_ZL19g_conv2_weight_int8_1_2_address0,
        p_ZL19g_conv2_weight_int8_1_2_ce0 => grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_p_ZL19g_conv2_weight_int8_1_2_ce0,
        p_ZL19g_conv2_weight_int8_1_2_q0 => p_ZL19g_conv2_weight_int8_1_2_q0,
        p_ZL19g_conv2_weight_int8_1_3_address0 => grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_p_ZL19g_conv2_weight_int8_1_3_address0,
        p_ZL19g_conv2_weight_int8_1_3_ce0 => grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_p_ZL19g_conv2_weight_int8_1_3_ce0,
        p_ZL19g_conv2_weight_int8_1_3_q0 => p_ZL19g_conv2_weight_int8_1_3_q0,
        p_ZL19g_conv2_weight_int8_1_4_address0 => grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_p_ZL19g_conv2_weight_int8_1_4_address0,
        p_ZL19g_conv2_weight_int8_1_4_ce0 => grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_p_ZL19g_conv2_weight_int8_1_4_ce0,
        p_ZL19g_conv2_weight_int8_1_4_q0 => p_ZL19g_conv2_weight_int8_1_4_q0,
        p_ZL19g_conv2_weight_int8_1_5_address0 => grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_p_ZL19g_conv2_weight_int8_1_5_address0,
        p_ZL19g_conv2_weight_int8_1_5_ce0 => grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_p_ZL19g_conv2_weight_int8_1_5_ce0,
        p_ZL19g_conv2_weight_int8_1_5_q0 => p_ZL19g_conv2_weight_int8_1_5_q0,
        p_ZL19g_conv2_weight_int8_1_6_address0 => grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_p_ZL19g_conv2_weight_int8_1_6_address0,
        p_ZL19g_conv2_weight_int8_1_6_ce0 => grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_p_ZL19g_conv2_weight_int8_1_6_ce0,
        p_ZL19g_conv2_weight_int8_1_6_q0 => p_ZL19g_conv2_weight_int8_1_6_q0,
        p_ZL19g_conv2_weight_int8_1_7_address0 => grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_p_ZL19g_conv2_weight_int8_1_7_address0,
        p_ZL19g_conv2_weight_int8_1_7_ce0 => grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_p_ZL19g_conv2_weight_int8_1_7_ce0,
        p_ZL19g_conv2_weight_int8_1_7_q0 => p_ZL19g_conv2_weight_int8_1_7_q0);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
                    grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_ap_ready = ap_const_logic_1)) then 
                    grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    h_fu_144_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                h_fu_144 <= ap_const_lv8_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
                h_fu_144 <= select_ln378_3_reg_926;
            end if; 
        end if;
    end process;

    indvar_flatten63_fu_148_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                indvar_flatten63_fu_148 <= ap_const_lv12_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln376_fu_357_p2 = ap_const_lv1_0))) then 
                indvar_flatten63_fu_148 <= select_ln378_4_fu_384_p3;
            end if; 
        end if;
    end process;

    indvar_flatten80_fu_156_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                indvar_flatten80_fu_156 <= ap_const_lv16_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln376_fu_357_p2 = ap_const_lv1_0))) then 
                indvar_flatten80_fu_156 <= add_ln376_4_fu_363_p2;
            end if; 
        end if;
    end process;

    oc_fu_152_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                oc_fu_152 <= ap_const_lv6_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
                oc_fu_152 <= select_ln376_3_fu_468_p3;
            end if; 
        end if;
    end process;

    w_fu_140_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                w_fu_140 <= ap_const_lv4_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
                w_fu_140 <= add_ln380_fu_512_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state13)) then
                add_ln376_3_reg_1059 <= add_ln376_3_fu_681_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                add_ln376_reg_913 <= add_ln376_fu_408_p2;
                select_ln378_3_reg_926 <= select_ln378_3_fu_456_p3;
                select_ln378_reg_919 <= select_ln378_fu_448_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state8)) then
                add_ln409_4_reg_999 <= add_ln409_4_fu_592_p2;
                add_ln840_25_reg_1004 <= add_ln840_25_fu_613_p2;
                p_ZL18g_conv2_bias_int32_1_load_reg_988 <= p_ZL18g_conv2_bias_int32_1_q0;
                select_ln376_4_reg_993 <= select_ln376_4_fu_559_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state7)) then
                add_ln409_reg_978 <= add_ln409_fu_549_p2;
                trunc_ln409_reg_983 <= trunc_ln409_fu_555_p1;
                    zext_ln376_9_reg_967(5 downto 0) <= zext_ln376_9_fu_542_p1(5 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state16)) then
                add_ln55_reg_1093 <= add_ln55_fu_717_p2;
                select_ln50_reg_1098 <= select_ln50_fu_726_p3;
                    zext_ln376_12_reg_1088(31 downto 0) <= zext_ln376_12_fu_708_p1(31 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state9)) then
                add_ln840_21_reg_1024 <= add_ln840_21_fu_639_p2;
                add_ln840_26_reg_1029 <= add_ln840_26_fu_651_p2;
                add_ln840_reg_1019 <= add_ln840_fu_634_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln376_fu_357_p2 = ap_const_lv1_0))) then
                icmp_ln378_reg_904 <= icmp_ln378_fu_372_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                icmp_ln50_reg_896 <= grp_fu_315_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
                icmp_reg_962 <= icmp_fu_505_p2;
                notlhs_mid150_reg_957 <= notlhs_mid150_fu_489_p2;
                p_mid146_reg_952 <= p_mid146_fu_482_p2;
                select_ln376_3_reg_935 <= select_ln376_3_fu_468_p3;
                trunc_ln397_reg_942 <= trunc_ln397_fu_474_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state10)) then
                p_ZL20g_conv2_requant_mult_1_load_reg_1034 <= p_ZL20g_conv2_requant_mult_1_q0;
                total_V_reg_1044 <= total_V_fu_664_p2;
                trunc_ln376_reg_1039 <= trunc_ln376_fu_656_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state14)) then
                product_reg_1070 <= grp_fu_702_p_dout0;
                shl_ln376_reg_1064 <= shl_ln376_fu_689_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state3) or ((ap_const_logic_1 = ap_CS_fsm_state7) and (icmp_ln378_reg_904 = ap_const_lv1_1)))) then
                reg_311 <= p_ZL21g_conv2_requant_shift_1_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state18)) then
                select_ln39_reg_1114 <= select_ln39_fu_793_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state17)) then
                select_ln54_reg_1103 <= select_ln54_fu_749_p3;
                tmp_50_reg_1109 <= select_ln54_fu_749_p3(63 downto 7);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((select_ln376_4_reg_993 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state15))) then
                sub_ln376_reg_1078 <= sub_ln376_fu_695_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((select_ln376_4_reg_993 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state15))) then
                sub_ln57_reg_1083 <= sub_ln57_fu_701_p2;
            end if;
        end if;
    end process;
    zext_ln376_9_reg_967(63 downto 6) <= "0000000000000000000000000000000000000000000000000000000000";
    zext_ln376_12_reg_1088(63 downto 32) <= "00000000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state7, ap_CS_fsm_state4, icmp_ln376_fu_357_p2, grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_ap_done)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln376_fu_357_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                if (((grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then
                    ap_NS_fsm <= ap_ST_fsm_state8;
                else
                    ap_NS_fsm <= ap_ST_fsm_state7;
                end if;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state12;
            when ap_ST_fsm_state12 => 
                ap_NS_fsm <= ap_ST_fsm_state13;
            when ap_ST_fsm_state13 => 
                ap_NS_fsm <= ap_ST_fsm_state14;
            when ap_ST_fsm_state14 => 
                ap_NS_fsm <= ap_ST_fsm_state15;
            when ap_ST_fsm_state15 => 
                ap_NS_fsm <= ap_ST_fsm_state16;
            when ap_ST_fsm_state16 => 
                ap_NS_fsm <= ap_ST_fsm_state17;
            when ap_ST_fsm_state17 => 
                ap_NS_fsm <= ap_ST_fsm_state18;
            when ap_ST_fsm_state18 => 
                ap_NS_fsm <= ap_ST_fsm_state19;
            when ap_ST_fsm_state19 => 
                ap_NS_fsm <= ap_ST_fsm_state2;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXXXXXXX";
        end case;
    end process;
    add_ln376_3_fu_681_p2 <= std_logic_vector(unsigned(trunc_ln376_reg_1039) + unsigned(ap_const_lv31_7FFFFFFF));
    add_ln376_4_fu_363_p2 <= std_logic_vector(unsigned(indvar_flatten80_fu_156) + unsigned(ap_const_lv16_1));
    add_ln376_fu_408_p2 <= std_logic_vector(unsigned(oc_fu_152) + unsigned(ap_const_lv6_1));
    add_ln378_2_fu_378_p2 <= std_logic_vector(unsigned(indvar_flatten63_fu_148) + unsigned(ap_const_lv12_1));
    add_ln378_fu_437_p2 <= std_logic_vector(unsigned(select_ln376_fu_413_p3) + unsigned(ap_const_lv8_1));
    add_ln380_fu_512_p2 <= std_logic_vector(unsigned(select_ln378_reg_919) + unsigned(ap_const_lv4_1));
    add_ln409_3_fu_583_p2 <= std_logic_vector(unsigned(p_shl_fu_565_p3) + unsigned(zext_ln409_4_fu_579_p1));
    add_ln409_4_fu_592_p2 <= std_logic_vector(unsigned(add_ln409_3_fu_583_p2) + unsigned(zext_ln409_5_fu_589_p1));
    add_ln409_fu_549_p2 <= std_logic_vector(unsigned(zext_ln376_8_fu_538_p1) + unsigned(zext_ln409_fu_546_p1));
    add_ln55_fu_717_p2 <= std_logic_vector(unsigned(shl_ln376_reg_1064) + unsigned(product_reg_1070));
    add_ln840_21_fu_639_p2 <= std_logic_vector(unsigned(grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_add_i2513_out) + unsigned(grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_p_out5));
    add_ln840_22_fu_660_p2 <= std_logic_vector(unsigned(add_ln840_21_reg_1024) + unsigned(add_ln840_reg_1019));
    add_ln840_23_fu_645_p2 <= std_logic_vector(unsigned(grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_p_out4) + unsigned(grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_p_out3));
    add_ln840_24_fu_607_p2 <= std_logic_vector(unsigned(grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_p_out1) + unsigned(grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_p_out));
    add_ln840_25_fu_613_p2 <= std_logic_vector(unsigned(add_ln840_24_fu_607_p2) + unsigned(grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_p_out2));
    add_ln840_26_fu_651_p2 <= std_logic_vector(unsigned(add_ln840_25_reg_1004) + unsigned(add_ln840_23_fu_645_p2));
    add_ln840_fu_634_p2 <= std_logic_vector(unsigned(p_ZL18g_conv2_bias_int32_1_load_reg_988) + unsigned(grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_p_out6));
    and_ln376_fu_431_p2 <= (xor_ln376_fu_420_p2 and icmp_ln380_fu_425_p2);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state13 <= ap_CS_fsm(12);
    ap_CS_fsm_state14 <= ap_CS_fsm(13);
    ap_CS_fsm_state15 <= ap_CS_fsm(14);
    ap_CS_fsm_state16 <= ap_CS_fsm(15);
    ap_CS_fsm_state17 <= ap_CS_fsm(16);
    ap_CS_fsm_state18 <= ap_CS_fsm(17);
    ap_CS_fsm_state19 <= ap_CS_fsm(18);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);
    ap_ST_fsm_state10_blk <= ap_const_logic_0;
    ap_ST_fsm_state11_blk <= ap_const_logic_0;
    ap_ST_fsm_state12_blk <= ap_const_logic_0;
    ap_ST_fsm_state13_blk <= ap_const_logic_0;
    ap_ST_fsm_state14_blk <= ap_const_logic_0;
    ap_ST_fsm_state15_blk <= ap_const_logic_0;
    ap_ST_fsm_state16_blk <= ap_const_logic_0;
    ap_ST_fsm_state17_blk <= ap_const_logic_0;
    ap_ST_fsm_state18_blk <= ap_const_logic_0;
    ap_ST_fsm_state19_blk <= ap_const_logic_0;

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;

    ap_ST_fsm_state7_blk_assign_proc : process(grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_ap_done)
    begin
        if ((grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state7_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state7_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state8_blk <= ap_const_logic_0;
    ap_ST_fsm_state9_blk <= ap_const_logic_0;

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state4, icmp_ln376_fu_357_p2)
    begin
        if ((((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln376_fu_357_p2 = ap_const_lv1_1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state4, icmp_ln376_fu_357_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln376_fu_357_p2 = ap_const_lv1_1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    ashr_ln55_fu_740_p2 <= std_logic_vector(shift_right(signed(add_ln55_reg_1093),to_integer(unsigned('0' & zext_ln376_12_reg_1088(31-1 downto 0)))));
    ashr_ln57_fu_721_p2 <= std_logic_vector(shift_right(signed(sub_ln57_reg_1083),to_integer(unsigned('0' & zext_ln376_12_fu_708_p1(31-1 downto 0)))));
    grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_ap_start <= grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_ap_start_reg;
    grp_fu_315_p2 <= "1" when (signed(reg_311) < signed(ap_const_lv32_1)) else "0";
    grp_fu_702_p_ce <= ap_const_logic_1;
    grp_fu_702_p_din0 <= sext_ln376_fu_669_p1(32 - 1 downto 0);
    grp_fu_702_p_din1 <= sext_ln541_fu_672_p1(32 - 1 downto 0);
    icmp_fu_505_p2 <= "0" when (tmp_48_fu_495_p4 = ap_const_lv2_1) else "1";
    icmp_ln376_fu_357_p2 <= "1" when (indvar_flatten80_fu_156 = ap_const_lv16_A000) else "0";
    icmp_ln378_fu_372_p2 <= "1" when (indvar_flatten63_fu_148 = ap_const_lv12_500) else "0";
    icmp_ln380_fu_425_p2 <= "1" when (w_fu_140 = ap_const_lv4_A) else "0";
    icmp_ln39_fu_766_p2 <= "1" when (signed(tmp_50_reg_1109) > signed(ap_const_lv57_0)) else "0";
    icmp_ln42_fu_771_p2 <= "1" when (signed(select_ln54_reg_1103) < signed(ap_const_lv64_FFFFFFFFFFFFFF81)) else "0";
    input_0_address0 <= grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_input_0_address0;
    input_0_ce0 <= grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_input_0_ce0;
    input_1_address0 <= grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_input_1_address0;
    input_1_ce0 <= grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_input_1_ce0;
    input_2_address0 <= grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_input_2_address0;
    input_2_ce0 <= grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_input_2_ce0;
    input_3_address0 <= grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_input_3_address0;
    input_3_ce0 <= grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_input_3_ce0;
    input_4_address0 <= grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_input_4_address0;
    input_4_ce0 <= grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_input_4_ce0;
    input_5_address0 <= grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_input_5_address0;
    input_5_ce0 <= grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_input_5_ce0;
    input_6_address0 <= grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_input_6_address0;
    input_6_ce0 <= grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_input_6_ce0;
    input_7_address0 <= grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_input_7_address0;
    input_7_ce0 <= grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_input_7_ce0;
    notlhs_mid150_fu_489_p2 <= "0" when (select_ln378_3_reg_926 = ap_const_lv8_0) else "1";
    or_ln378_fu_443_p2 <= (icmp_ln378_reg_904 or and_ln376_fu_431_p2);
    or_ln39_fu_787_p2 <= (icmp_ln42_fu_771_p2 or icmp_ln39_fu_766_p2);
    or_ln54_fu_744_p2 <= (tmp_49_fu_733_p3 or select_ln376_4_reg_993);
    output_r_address0 <= zext_ln409_6_fu_801_p1(16 - 1 downto 0);

    output_r_ce0_assign_proc : process(ap_CS_fsm_state19)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state19)) then 
            output_r_ce0 <= ap_const_logic_1;
        else 
            output_r_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    output_r_d0 <= select_ln39_reg_1114;

    output_r_we0_assign_proc : process(ap_CS_fsm_state19)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state19)) then 
            output_r_we0 <= ap_const_logic_1;
        else 
            output_r_we0 <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL18g_conv2_bias_int32_1_address0 <= zext_ln376_9_fu_542_p1(5 - 1 downto 0);

    p_ZL18g_conv2_bias_int32_1_ce0_assign_proc : process(ap_CS_fsm_state7, grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_ap_done)
    begin
        if (((grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
            p_ZL18g_conv2_bias_int32_1_ce0 <= ap_const_logic_1;
        else 
            p_ZL18g_conv2_bias_int32_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL19g_conv2_weight_int8_1_0_address0 <= grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_p_ZL19g_conv2_weight_int8_1_0_address0;
    p_ZL19g_conv2_weight_int8_1_0_ce0 <= grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_p_ZL19g_conv2_weight_int8_1_0_ce0;
    p_ZL19g_conv2_weight_int8_1_1_address0 <= grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_p_ZL19g_conv2_weight_int8_1_1_address0;
    p_ZL19g_conv2_weight_int8_1_1_ce0 <= grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_p_ZL19g_conv2_weight_int8_1_1_ce0;
    p_ZL19g_conv2_weight_int8_1_2_address0 <= grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_p_ZL19g_conv2_weight_int8_1_2_address0;
    p_ZL19g_conv2_weight_int8_1_2_ce0 <= grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_p_ZL19g_conv2_weight_int8_1_2_ce0;
    p_ZL19g_conv2_weight_int8_1_3_address0 <= grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_p_ZL19g_conv2_weight_int8_1_3_address0;
    p_ZL19g_conv2_weight_int8_1_3_ce0 <= grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_p_ZL19g_conv2_weight_int8_1_3_ce0;
    p_ZL19g_conv2_weight_int8_1_4_address0 <= grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_p_ZL19g_conv2_weight_int8_1_4_address0;
    p_ZL19g_conv2_weight_int8_1_4_ce0 <= grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_p_ZL19g_conv2_weight_int8_1_4_ce0;
    p_ZL19g_conv2_weight_int8_1_5_address0 <= grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_p_ZL19g_conv2_weight_int8_1_5_address0;
    p_ZL19g_conv2_weight_int8_1_5_ce0 <= grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_p_ZL19g_conv2_weight_int8_1_5_ce0;
    p_ZL19g_conv2_weight_int8_1_6_address0 <= grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_p_ZL19g_conv2_weight_int8_1_6_address0;
    p_ZL19g_conv2_weight_int8_1_6_ce0 <= grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_p_ZL19g_conv2_weight_int8_1_6_ce0;
    p_ZL19g_conv2_weight_int8_1_7_address0 <= grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_p_ZL19g_conv2_weight_int8_1_7_address0;
    p_ZL19g_conv2_weight_int8_1_7_ce0 <= grp_conv2_receiver_1_Pipeline_CONV2_IC_CONV2_KH_CONV2_KW_fu_260_p_ZL19g_conv2_weight_int8_1_7_ce0;
    p_ZL20g_conv2_requant_mult_1_address0 <= zext_ln376_9_reg_967(5 - 1 downto 0);

    p_ZL20g_conv2_requant_mult_1_ce0_assign_proc : process(ap_CS_fsm_state9)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            p_ZL20g_conv2_requant_mult_1_ce0 <= ap_const_logic_1;
        else 
            p_ZL20g_conv2_requant_mult_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    p_ZL21g_conv2_requant_shift_1_address0_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state6, zext_ln376_9_reg_967, ap_CS_fsm_state9, zext_ln376_fu_349_p1, zext_ln376_7_fu_464_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            p_ZL21g_conv2_requant_shift_1_address0 <= zext_ln376_9_reg_967(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            p_ZL21g_conv2_requant_shift_1_address0 <= zext_ln376_7_fu_464_p1(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            p_ZL21g_conv2_requant_shift_1_address0 <= zext_ln376_fu_349_p1(5 - 1 downto 0);
        else 
            p_ZL21g_conv2_requant_shift_1_address0 <= "XXXXX";
        end if; 
    end process;


    p_ZL21g_conv2_requant_shift_1_ce0_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state6, ap_CS_fsm_state9)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            p_ZL21g_conv2_requant_shift_1_ce0 <= ap_const_logic_1;
        else 
            p_ZL21g_conv2_requant_shift_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    p_cast_mid144_fu_479_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln378_3_reg_926),9));
    p_mid146_fu_482_p2 <= std_logic_vector(unsigned(p_cast_mid144_fu_479_p1) + unsigned(ap_const_lv9_1FF));
    p_shl_fu_565_p3 <= (trunc_ln409_reg_983 & ap_const_lv3_0);
    select_ln376_3_fu_468_p3 <= 
        add_ln376_reg_913 when (icmp_ln378_reg_904(0) = '1') else 
        oc_fu_152;
    select_ln376_4_fu_559_p3 <= 
        grp_fu_315_p2 when (icmp_ln378_reg_904(0) = '1') else 
        icmp_ln50_reg_896;
    select_ln376_fu_413_p3 <= 
        ap_const_lv8_0 when (icmp_ln378_reg_904(0) = '1') else 
        h_fu_144;
    select_ln378_3_fu_456_p3 <= 
        add_ln378_fu_437_p2 when (and_ln376_fu_431_p2(0) = '1') else 
        select_ln376_fu_413_p3;
    select_ln378_4_fu_384_p3 <= 
        ap_const_lv12_1 when (icmp_ln378_fu_372_p2(0) = '1') else 
        add_ln378_2_fu_378_p2;
    select_ln378_fu_448_p3 <= 
        ap_const_lv4_0 when (or_ln378_fu_443_p2(0) = '1') else 
        w_fu_140;
    select_ln39_8_fu_779_p3 <= 
        ap_const_lv8_7F when (icmp_ln39_fu_766_p2(0) = '1') else 
        ap_const_lv8_81;
    select_ln39_fu_793_p3 <= 
        select_ln39_8_fu_779_p3 when (or_ln39_fu_787_p2(0) = '1') else 
        trunc_ln218_fu_776_p1;
    select_ln50_fu_726_p3 <= 
        shl_ln51_fu_712_p2 when (select_ln376_4_reg_993(0) = '1') else 
        ashr_ln57_fu_721_p2;
    select_ln54_fu_749_p3 <= 
        select_ln50_reg_1098 when (or_ln54_fu_744_p2(0) = '1') else 
        ashr_ln55_fu_740_p2;
        sext_ln376_fu_669_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_ZL20g_conv2_requant_mult_1_load_reg_1034),64));

        sext_ln541_fu_672_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(total_V_reg_1044),64));

    shl_ln376_fu_689_p2 <= std_logic_vector(shift_left(unsigned(ap_const_lv64_1),to_integer(unsigned('0' & zext_ln376_11_fu_686_p1(31-1 downto 0)))));
    shl_ln51_fu_712_p2 <= std_logic_vector(shift_left(unsigned(product_reg_1070),to_integer(unsigned('0' & zext_ln376_10_fu_705_p1(31-1 downto 0)))));
    sub_ln376_fu_695_p2 <= std_logic_vector(unsigned(ap_const_lv32_0) - unsigned(reg_311));
    sub_ln57_fu_701_p2 <= std_logic_vector(unsigned(product_reg_1070) - unsigned(shl_ln376_reg_1064));
    tmp_47_fu_572_p3 <= (add_ln409_reg_978 & ap_const_lv1_0);
    tmp_48_fu_495_p4 <= p_mid146_fu_482_p2(8 downto 7);
    tmp_49_fu_733_p3 <= product_reg_1070(63 downto 63);
    tmp_fu_531_p3 <= (select_ln376_3_reg_935 & ap_const_lv7_0);
    total_V_fu_664_p2 <= std_logic_vector(unsigned(add_ln840_26_reg_1029) + unsigned(add_ln840_22_fu_660_p2));
    trunc_ln218_fu_776_p1 <= select_ln54_reg_1103(8 - 1 downto 0);
    trunc_ln376_fu_656_p1 <= p_ZL21g_conv2_requant_shift_1_q0(31 - 1 downto 0);
    trunc_ln397_fu_474_p1 <= select_ln376_3_fu_468_p3(3 - 1 downto 0);
    trunc_ln409_fu_555_p1 <= add_ln409_fu_549_p2(13 - 1 downto 0);
    xor_ln376_fu_420_p2 <= (icmp_ln378_reg_904 xor ap_const_lv1_1);
    zext_ln376_10_fu_705_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sub_ln376_reg_1078),64));
    zext_ln376_11_fu_686_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln376_3_reg_1059),64));
    zext_ln376_12_fu_708_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(reg_311),64));
    zext_ln376_7_fu_464_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln376_reg_913),64));
    zext_ln376_8_fu_538_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_531_p3),14));
    zext_ln376_9_fu_542_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln376_3_reg_935),64));
    zext_ln376_fu_349_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(oc_fu_152),64));
    zext_ln409_4_fu_579_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_47_fu_572_p3),16));
    zext_ln409_5_fu_589_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln378_reg_919),16));
    zext_ln409_6_fu_801_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln409_4_reg_999),64));
    zext_ln409_fu_546_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln378_3_reg_926),14));
end behav;
