-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity full_pose_accel_encode_receiver_path_0_Pipeline_CONV1_CH_CONV1_KH_CONV1_KW is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    p_ZL18g_conv1_bias_int32_0_load : IN STD_LOGIC_VECTOR (31 downto 0);
    select_ln327_10 : IN STD_LOGIC_VECTOR (7 downto 0);
    sub_ln343 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_cast8_mid123 : IN STD_LOGIC_VECTOR (7 downto 0);
    notlhs_mid137 : IN STD_LOGIC_VECTOR (0 downto 0);
    zext_ln329_3 : IN STD_LOGIC_VECTOR (3 downto 0);
    input_r_address0 : OUT STD_LOGIC_VECTOR (13 downto 0);
    input_r_ce0 : OUT STD_LOGIC;
    input_r_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    acc_V_5_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    acc_V_5_out_ap_vld : OUT STD_LOGIC;
    p_ZL19g_conv1_weight_int8_0_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    p_ZL19g_conv1_weight_int8_0_ce0 : OUT STD_LOGIC;
    p_ZL19g_conv1_weight_int8_0_q0 : IN STD_LOGIC_VECTOR (7 downto 0) );
end;


architecture behav of full_pose_accel_encode_receiver_path_0_Pipeline_CONV1_CH_CONV1_KH_CONV1_KW is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv6_2D : STD_LOGIC_VECTOR (5 downto 0) := "101101";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv5_F : STD_LOGIC_VECTOR (4 downto 0) := "01111";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv3_7 : STD_LOGIC_VECTOR (2 downto 0) := "111";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv5_A : STD_LOGIC_VECTOR (4 downto 0) := "01010";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter6 : BOOLEAN;
    signal ap_block_state8_pp0_stage0_iter7 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln333_fu_260_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal zext_ln329_3_cast_fu_211_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln329_3_cast_reg_830 : STD_LOGIC_VECTOR (4 downto 0);
    signal p_cast8_mid123_cast_fu_215_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal p_cast8_mid123_cast_reg_835 : STD_LOGIC_VECTOR (11 downto 0);
    signal select_ln327_10_cast_fu_219_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln327_10_cast_reg_840 : STD_LOGIC_VECTOR (8 downto 0);
    signal sub_ln343_cast_fu_223_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal sub_ln343_cast_reg_846 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln333_reg_851 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln333_reg_851_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln333_reg_851_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln333_reg_851_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln333_reg_851_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln333_reg_851_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln335_fu_275_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln335_reg_855 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln335_reg_855_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln335_reg_855_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal kh_5_reg_867 : STD_LOGIC_VECTOR (2 downto 0);
    signal ch_4_reg_872 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln333_fu_314_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln333_reg_878 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln343_10_fu_338_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln343_10_reg_884 : STD_LOGIC_VECTOR (8 downto 0);
    signal and_ln333_fu_354_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln333_reg_890 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln333_reg_890_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln335_fu_360_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln335_reg_897 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln335_fu_371_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln335_reg_902 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln335_reg_902_pp0_iter2_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln335_11_fu_379_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln335_11_reg_907 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln340_fu_391_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln340_reg_912 : STD_LOGIC_VECTOR (2 downto 0);
    signal icmp_fu_488_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_reg_917 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln343_fu_576_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln343_reg_922 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln343_3_fu_580_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln343_3_reg_927 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln335_12_fu_602_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal select_ln335_12_reg_932 : STD_LOGIC_VECTOR (11 downto 0);
    signal trunc_ln335_fu_609_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln335_reg_937 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp35_fu_644_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp35_reg_942 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln340_3_fu_653_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln340_3_reg_947 : STD_LOGIC_VECTOR (4 downto 0);
    signal and_ln341_3_fu_664_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln341_3_reg_952 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln343_13_fu_713_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln343_13_reg_957 : STD_LOGIC_VECTOR (9 downto 0);
    signal and_ln341_fu_722_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln341_reg_962 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln341_reg_962_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln341_reg_962_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln341_reg_962_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln343_fu_733_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal add_ln343_reg_967 : STD_LOGIC_VECTOR (13 downto 0);
    signal ap_condition_exit_pp0_iter2_stage0 : STD_LOGIC;
    signal zext_ln343_14_fu_739_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln343_fu_743_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal acc_V_5_fu_118 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_V_fu_758_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal kw_fu_122 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln337_fu_397_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal kh_fu_126 : STD_LOGIC_VECTOR (2 downto 0);
    signal indvar_flatten_fu_130 : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln335_15_fu_287_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_sig_allocacmp_indvar_flatten_load : STD_LOGIC_VECTOR (4 downto 0);
    signal ch_fu_134 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln333_9_fu_327_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal indvar_flatten43_fu_138 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln333_3_fu_266_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_sig_allocacmp_indvar_flatten43_load : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal add_ln335_3_fu_281_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln343_11_fu_334_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln337_fu_348_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln333_fu_343_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln333_fu_320_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal or_ln335_fu_366_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln337_fu_387_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal p_shl_fu_418_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal p_shl2_fu_429_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_shl_cast_fu_425_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal p_shl2_cast_fu_436_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln335_fu_446_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal empty_140_fu_449_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal empty_fu_440_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal p_cast8_fu_454_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_fu_464_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_29_fu_478_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_30_fu_497_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln343_3_fu_504_p1 : STD_LOGIC_VECTOR (61 downto 0);
    signal sext_ln343_fu_494_p1 : STD_LOGIC_VECTOR (61 downto 0);
    signal p_shl_mid1_fu_514_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal p_shl2_mid1_fu_525_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_shl_cast_mid1_fu_521_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal p_shl2_cast_mid1_fu_532_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal p_mid115_fu_536_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal p_mid125_fu_549_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal empty_141_fu_458_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal rev_fu_472_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln343_11_fu_508_p2 : STD_LOGIC_VECTOR (61 downto 0);
    signal zext_ln343_12_fu_567_p1 : STD_LOGIC_VECTOR (61 downto 0);
    signal add_ln343_12_fu_570_p2 : STD_LOGIC_VECTOR (61 downto 0);
    signal zext_ln335_3_fu_584_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_mid1_fu_587_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln333_10_fu_542_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal p_cast8_mid1_fu_592_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal p_mid13_fu_596_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal select_ln333_11_fu_554_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_31_fu_613_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev32_fu_621_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln333_12_fu_561_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_32_fu_634_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal sext_ln340_fu_650_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln335_13_fu_627_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln341_fu_658_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_shl4_fu_674_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_shl4_cast_mid2_v_fu_693_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal or_ln333_fu_670_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln343_3_fu_681_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln343_13_fu_710_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln335_14_fu_704_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sext_ln341_fu_719_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal sext_ln335_fu_700_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal add_ln343_3_fu_727_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal p_shl3_mid2_fu_686_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_fu_773_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component full_pose_accel_mac_muladd_8s_8s_32s_32_3_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        din2 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component full_pose_accel_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mac_muladd_8s_8s_32s_32_3_1_U256 : component full_pose_accel_mac_muladd_8s_8s_32s_32_3_1
    generic map (
        ID => 1,
        NUM_STAGE => 3,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => p_ZL19g_conv1_weight_int8_0_q0,
        din1 => input_r_q0,
        din2 => acc_V_5_fu_118,
        ce => ap_const_logic_1,
        dout => grp_fu_773_p3);

    flow_control_loop_pipe_sequential_init_U : component full_pose_accel_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter6_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter2_stage0)) then 
                    ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    acc_V_5_fu_118_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    acc_V_5_fu_118 <= p_ZL18g_conv1_bias_int32_0_load;
                elsif ((ap_enable_reg_pp0_iter7 = ap_const_logic_1)) then 
                    acc_V_5_fu_118 <= acc_V_fu_758_p3;
                end if;
            end if; 
        end if;
    end process;

    ch_fu_134_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    ch_fu_134 <= ap_const_lv2_0;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln333_reg_851 = ap_const_lv1_0))) then 
                    ch_fu_134 <= select_ln333_9_fu_327_p3;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten43_fu_138_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln333_fu_260_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten43_fu_138 <= add_ln333_3_fu_266_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten43_fu_138 <= ap_const_lv6_0;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten_fu_130_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln333_fu_260_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten_fu_130 <= select_ln335_15_fu_287_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten_fu_130 <= ap_const_lv5_0;
                end if;
            end if; 
        end if;
    end process;

    kh_fu_126_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    kh_fu_126 <= ap_const_lv3_0;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln333_reg_851 = ap_const_lv1_0))) then 
                    kh_fu_126 <= select_ln335_11_fu_379_p3;
                end if;
            end if; 
        end if;
    end process;

    kw_fu_122_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    kw_fu_122 <= ap_const_lv2_0;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln333_reg_851 = ap_const_lv1_0))) then 
                    kw_fu_122 <= add_ln337_fu_397_p2;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln333_reg_851 = ap_const_lv1_0))) then
                add_ln333_reg_878 <= add_ln333_fu_314_p2;
                add_ln335_reg_897 <= add_ln335_fu_360_p2;
                add_ln340_reg_912 <= add_ln340_fu_391_p2;
                add_ln343_10_reg_884 <= add_ln343_10_fu_338_p2;
                and_ln333_reg_890 <= and_ln333_fu_354_p2;
                select_ln335_11_reg_907 <= select_ln335_11_fu_379_p3;
                select_ln335_reg_902 <= select_ln335_fu_371_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln333_reg_851_pp0_iter1_reg = ap_const_lv1_0))) then
                add_ln340_3_reg_947 <= add_ln340_3_fu_653_p2;
                and_ln341_3_reg_952 <= and_ln341_3_fu_664_p2;
                select_ln335_12_reg_932 <= select_ln335_12_fu_602_p3;
                trunc_ln335_reg_937 <= trunc_ln335_fu_609_p1;
                trunc_ln343_3_reg_927 <= trunc_ln343_3_fu_580_p1;
                trunc_ln343_reg_922 <= trunc_ln343_fu_576_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                add_ln343_13_reg_957 <= add_ln343_13_fu_713_p2;
                add_ln343_reg_967 <= add_ln343_fu_733_p2;
                and_ln333_reg_890_pp0_iter2_reg <= and_ln333_reg_890;
                and_ln341_reg_962 <= and_ln341_fu_722_p2;
                and_ln341_reg_962_pp0_iter4_reg <= and_ln341_reg_962;
                and_ln341_reg_962_pp0_iter5_reg <= and_ln341_reg_962_pp0_iter4_reg;
                and_ln341_reg_962_pp0_iter6_reg <= and_ln341_reg_962_pp0_iter5_reg;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                icmp_ln333_reg_851_pp0_iter2_reg <= icmp_ln333_reg_851_pp0_iter1_reg;
                icmp_ln333_reg_851_pp0_iter3_reg <= icmp_ln333_reg_851_pp0_iter2_reg;
                icmp_ln333_reg_851_pp0_iter4_reg <= icmp_ln333_reg_851_pp0_iter3_reg;
                icmp_ln333_reg_851_pp0_iter5_reg <= icmp_ln333_reg_851_pp0_iter4_reg;
                icmp_ln335_reg_855_pp0_iter2_reg <= icmp_ln335_reg_855_pp0_iter1_reg;
                select_ln335_reg_902_pp0_iter2_reg <= select_ln335_reg_902;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                ch_4_reg_872 <= ch_fu_134;
                icmp_ln333_reg_851 <= icmp_ln333_fu_260_p2;
                icmp_ln333_reg_851_pp0_iter1_reg <= icmp_ln333_reg_851;
                icmp_ln335_reg_855_pp0_iter1_reg <= icmp_ln335_reg_855;
                kh_5_reg_867 <= kh_fu_126;
                p_cast8_mid123_cast_reg_835 <= p_cast8_mid123_cast_fu_215_p1;
                select_ln327_10_cast_reg_840 <= select_ln327_10_cast_fu_219_p1;
                sub_ln343_cast_reg_846 <= sub_ln343_cast_fu_223_p1;
                    zext_ln329_3_cast_reg_830(3 downto 0) <= zext_ln329_3_cast_fu_211_p1(3 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_1 = and_ln333_reg_890) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln333_reg_851_pp0_iter1_reg = ap_const_lv1_0))) then
                icmp35_reg_942 <= icmp35_fu_644_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln333_fu_260_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln335_reg_855 <= icmp_ln335_fu_275_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_lv1_0 = and_ln333_reg_890))) then
                icmp_reg_917 <= icmp_fu_488_p2;
            end if;
        end if;
    end process;
    zext_ln329_3_cast_reg_830(4) <= '0';

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    acc_V_5_out <= acc_V_5_fu_118;

    acc_V_5_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln333_reg_851_pp0_iter5_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln333_reg_851_pp0_iter5_reg = ap_const_lv1_1))) then 
            acc_V_5_out_ap_vld <= ap_const_logic_1;
        else 
            acc_V_5_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    acc_V_fu_758_p3 <= 
        grp_fu_773_p3 when (and_ln341_reg_962_pp0_iter6_reg(0) = '1') else 
        acc_V_5_fu_118;
    add_ln333_3_fu_266_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten43_load) + unsigned(ap_const_lv6_1));
    add_ln333_fu_314_p2 <= std_logic_vector(unsigned(ch_fu_134) + unsigned(ap_const_lv2_1));
    add_ln335_3_fu_281_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten_load) + unsigned(ap_const_lv5_1));
    add_ln335_fu_360_p2 <= std_logic_vector(unsigned(select_ln333_fu_320_p3) + unsigned(ap_const_lv3_1));
    add_ln337_fu_397_p2 <= std_logic_vector(unsigned(select_ln335_fu_371_p3) + unsigned(ap_const_lv2_1));
    add_ln340_3_fu_653_p2 <= std_logic_vector(signed(sext_ln340_fu_650_p1) + signed(zext_ln329_3_cast_reg_830));
    add_ln340_fu_391_p2 <= std_logic_vector(unsigned(zext_ln337_fu_387_p1) + unsigned(ap_const_lv3_7));
    add_ln343_10_fu_338_p2 <= std_logic_vector(signed(sub_ln343_cast_reg_846) + signed(zext_ln343_11_fu_334_p1));
    add_ln343_11_fu_508_p2 <= std_logic_vector(signed(sext_ln343_3_fu_504_p1) + signed(sext_ln343_fu_494_p1));
    add_ln343_12_fu_570_p2 <= std_logic_vector(unsigned(add_ln343_11_fu_508_p2) + unsigned(zext_ln343_12_fu_567_p1));
    add_ln343_13_fu_713_p2 <= std_logic_vector(unsigned(sub_ln343_3_fu_681_p2) + unsigned(zext_ln343_13_fu_710_p1));
    add_ln343_3_fu_727_p2 <= std_logic_vector(signed(sext_ln341_fu_719_p1) + signed(sext_ln335_fu_700_p1));
    add_ln343_fu_733_p2 <= std_logic_vector(unsigned(add_ln343_3_fu_727_p2) + unsigned(p_shl3_mid2_fu_686_p3));
    and_ln333_fu_354_p2 <= (xor_ln333_fu_343_p2 and icmp_ln337_fu_348_p2);
    and_ln341_3_fu_664_p2 <= (select_ln335_13_fu_627_p3 and icmp_ln341_fu_658_p2);
    and_ln341_fu_722_p2 <= (select_ln335_14_fu_704_p3 and and_ln341_3_reg_952);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage0_iter6 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state8_pp0_stage0_iter7 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln333_fu_260_p2)
    begin
        if (((icmp_ln333_fu_260_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_exit_pp0_iter2_stage0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_subdone, icmp_ln333_reg_851_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln333_reg_851_pp0_iter1_reg = ap_const_lv1_1))) then 
            ap_condition_exit_pp0_iter2_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter2_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter6_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter6_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7)
    begin
        if (((ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten43_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten43_fu_138)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_indvar_flatten43_load <= ap_const_lv6_0;
        else 
            ap_sig_allocacmp_indvar_flatten43_load <= indvar_flatten43_fu_138;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten_fu_130)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_indvar_flatten_load <= ap_const_lv5_0;
        else 
            ap_sig_allocacmp_indvar_flatten_load <= indvar_flatten_fu_130;
        end if; 
    end process;

    empty_140_fu_449_p2 <= std_logic_vector(signed(select_ln327_10_cast_reg_840) + signed(zext_ln335_fu_446_p1));
    empty_141_fu_458_p2 <= std_logic_vector(unsigned(empty_fu_440_p2) + unsigned(p_cast8_fu_454_p1));
    empty_fu_440_p2 <= std_logic_vector(unsigned(p_shl_cast_fu_425_p1) - unsigned(p_shl2_cast_fu_436_p1));
    icmp35_fu_644_p2 <= "0" when (tmp_32_fu_634_p4 = ap_const_lv2_1) else "1";
    icmp_fu_488_p2 <= "0" when (tmp_29_fu_478_p4 = ap_const_lv2_1) else "1";
    icmp_ln333_fu_260_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten43_load = ap_const_lv6_2D) else "0";
    icmp_ln335_fu_275_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten_load = ap_const_lv5_F) else "0";
    icmp_ln337_fu_348_p2 <= "1" when (kw_fu_122 = ap_const_lv2_3) else "0";
    icmp_ln341_fu_658_p2 <= "1" when (unsigned(add_ln340_3_fu_653_p2) < unsigned(ap_const_lv5_A)) else "0";
    input_r_address0 <= zext_ln343_fu_743_p1(14 - 1 downto 0);

    input_r_ce0_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            input_r_ce0 <= ap_const_logic_1;
        else 
            input_r_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    or_ln333_fu_670_p2 <= (icmp_reg_917 or icmp_ln335_reg_855_pp0_iter2_reg);
    or_ln335_fu_366_p2 <= (icmp_ln335_reg_855 or and_ln333_fu_354_p2);
    p_ZL19g_conv1_weight_int8_0_address0 <= zext_ln343_14_fu_739_p1(10 - 1 downto 0);

    p_ZL19g_conv1_weight_int8_0_ce0_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            p_ZL19g_conv1_weight_int8_0_ce0 <= ap_const_logic_1;
        else 
            p_ZL19g_conv1_weight_int8_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;

        p_cast8_fu_454_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(empty_140_fu_449_p2),12));

        p_cast8_mid123_cast_fu_215_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_cast8_mid123),12));

        p_cast8_mid1_fu_592_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_mid1_fu_587_p2),12));

    p_mid115_fu_536_p2 <= std_logic_vector(unsigned(p_shl_cast_mid1_fu_521_p1) - unsigned(p_shl2_cast_mid1_fu_532_p1));
    p_mid125_fu_549_p2 <= std_logic_vector(unsigned(p_mid115_fu_536_p2) + unsigned(p_cast8_mid123_cast_reg_835));
    p_mid13_fu_596_p2 <= std_logic_vector(unsigned(select_ln333_10_fu_542_p3) + unsigned(p_cast8_mid1_fu_592_p1));
    p_mid1_fu_587_p2 <= std_logic_vector(signed(select_ln327_10_cast_reg_840) + signed(zext_ln335_3_fu_584_p1));
    p_shl2_cast_fu_436_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_shl2_fu_429_p3),12));
    p_shl2_cast_mid1_fu_532_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_shl2_mid1_fu_525_p3),12));
    p_shl2_fu_429_p3 <= (ch_4_reg_872 & ap_const_lv7_0);
    p_shl2_mid1_fu_525_p3 <= (add_ln333_reg_878 & ap_const_lv7_0);
    p_shl3_mid2_fu_686_p3 <= (trunc_ln335_reg_937 & ap_const_lv3_0);
    p_shl4_cast_mid2_v_fu_693_p3 <= (select_ln335_12_reg_932 & ap_const_lv1_0);
    p_shl4_fu_674_p3 <= (trunc_ln343_3_reg_927 & ap_const_lv2_0);
    p_shl_cast_fu_425_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_shl_fu_418_p3),12));
    p_shl_cast_mid1_fu_521_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_shl_mid1_fu_514_p3),12));
    p_shl_fu_418_p3 <= (ch_4_reg_872 & ap_const_lv9_0);
    p_shl_mid1_fu_514_p3 <= (add_ln333_reg_878 & ap_const_lv9_0);
    rev32_fu_621_p2 <= (tmp_31_fu_613_p3 xor ap_const_lv1_1);
    rev_fu_472_p2 <= (tmp_fu_464_p3 xor ap_const_lv1_1);
        select_ln327_10_cast_fu_219_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln327_10),9));

    select_ln333_10_fu_542_p3 <= 
        p_mid115_fu_536_p2 when (icmp_ln335_reg_855_pp0_iter1_reg(0) = '1') else 
        empty_fu_440_p2;
    select_ln333_11_fu_554_p3 <= 
        p_mid125_fu_549_p2 when (icmp_ln335_reg_855_pp0_iter1_reg(0) = '1') else 
        empty_141_fu_458_p2;
    select_ln333_12_fu_561_p3 <= 
        notlhs_mid137 when (icmp_ln335_reg_855_pp0_iter1_reg(0) = '1') else 
        rev_fu_472_p2;
    select_ln333_9_fu_327_p3 <= 
        add_ln333_fu_314_p2 when (icmp_ln335_reg_855(0) = '1') else 
        ch_fu_134;
    select_ln333_fu_320_p3 <= 
        ap_const_lv3_0 when (icmp_ln335_reg_855(0) = '1') else 
        kh_fu_126;
    select_ln335_11_fu_379_p3 <= 
        add_ln335_fu_360_p2 when (and_ln333_fu_354_p2(0) = '1') else 
        select_ln333_fu_320_p3;
    select_ln335_12_fu_602_p3 <= 
        p_mid13_fu_596_p2 when (and_ln333_reg_890(0) = '1') else 
        select_ln333_11_fu_554_p3;
    select_ln335_13_fu_627_p3 <= 
        rev32_fu_621_p2 when (and_ln333_reg_890(0) = '1') else 
        select_ln333_12_fu_561_p3;
    select_ln335_14_fu_704_p3 <= 
        icmp35_reg_942 when (and_ln333_reg_890_pp0_iter2_reg(0) = '1') else 
        or_ln333_fu_670_p2;
    select_ln335_15_fu_287_p3 <= 
        ap_const_lv5_1 when (icmp_ln335_fu_275_p2(0) = '1') else 
        add_ln335_3_fu_281_p2;
    select_ln335_fu_371_p3 <= 
        ap_const_lv2_0 when (or_ln335_fu_366_p2(0) = '1') else 
        kw_fu_122;
        sext_ln335_fu_700_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_shl4_cast_mid2_v_fu_693_p3),14));

        sext_ln340_fu_650_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln340_reg_912),5));

        sext_ln341_fu_719_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln340_3_reg_947),14));

        sext_ln343_3_fu_504_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_30_fu_497_p3),62));

        sext_ln343_fu_494_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln343_10_reg_884),62));

    sub_ln343_3_fu_681_p2 <= std_logic_vector(unsigned(p_shl4_fu_674_p3) - unsigned(trunc_ln343_reg_922));
        sub_ln343_cast_fu_223_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln343),9));

    tmp_29_fu_478_p4 <= empty_140_fu_449_p2(8 downto 7);
    tmp_30_fu_497_p3 <= (add_ln343_10_reg_884 & ap_const_lv2_0);
    tmp_31_fu_613_p3 <= p_mid1_fu_587_p2(8 downto 8);
    tmp_32_fu_634_p4 <= p_mid1_fu_587_p2(8 downto 7);
    tmp_fu_464_p3 <= empty_140_fu_449_p2(8 downto 8);
    trunc_ln335_fu_609_p1 <= select_ln335_12_fu_602_p3(11 - 1 downto 0);
    trunc_ln343_3_fu_580_p1 <= add_ln343_12_fu_570_p2(8 - 1 downto 0);
    trunc_ln343_fu_576_p1 <= add_ln343_12_fu_570_p2(10 - 1 downto 0);
    xor_ln333_fu_343_p2 <= (icmp_ln335_reg_855 xor ap_const_lv1_1);
    zext_ln329_3_cast_fu_211_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln329_3),5));
    zext_ln335_3_fu_584_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln335_reg_897),9));
    zext_ln335_fu_446_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(kh_5_reg_867),9));
    zext_ln337_fu_387_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln335_fu_371_p3),3));
    zext_ln343_11_fu_334_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln333_9_fu_327_p3),9));
    zext_ln343_12_fu_567_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln335_11_reg_907),62));
    zext_ln343_13_fu_710_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln335_reg_902_pp0_iter2_reg),10));
    zext_ln343_14_fu_739_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln343_13_reg_957),64));
    zext_ln343_fu_743_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln343_reg_967),64));
end behav;
